# Generated by Django 4.2 on 2025-12-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('field_number', models.CharField(max_length=50, unique=True)),
                ('county', models.CharField(max_length=100)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('township', models.CharField(blank=True, max_length=50)),
                ('range_value', models.CharField(blank=True, max_length=50)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_long', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('total_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_crop', models.CharField(max_length=100)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PesticideProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epa_registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('active_ingredients', models.TextField()),
                ('formulation_type', models.CharField(blank=True, max_length=100)),
                ('restricted_use', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='PesticideApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('acres_treated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(choices=[('gal', 'Gallons'), ('lbs', 'Pounds'), ('oz', 'Ounces'), ('pt', 'Pints'), ('qt', 'Quarts')], max_length=20)),
                ('application_method', models.CharField(choices=[('Ground Spray', 'Ground Spray'), ('Aerial Application', 'Aerial Application'), ('Chemigation', 'Chemigation'), ('Soil Injection', 'Soil Injection'), ('Broadcast', 'Broadcast Application')], max_length=100)),
                ('target_pest', models.CharField(blank=True, max_length=200)),
                ('applicator_name', models.CharField(max_length=200)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('wind_direction', models.CharField(blank=True, choices=[('N', 'North'), ('NE', 'Northeast'), ('E', 'East'), ('SE', 'Southeast'), ('S', 'South'), ('SW', 'Southwest'), ('W', 'West'), ('NW', 'Northwest')], max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_signature', 'Pending Signature'), ('complete', 'Complete'), ('submitted', 'Submitted to PUR')], default='pending_signature', max_length=20)),
                ('submitted_to_pur', models.BooleanField(default=False)),
                ('pur_submission_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='api.field')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='api.pesticideproduct')),
            ],
            options={
                'ordering': ['-application_date', '-created_at'],
            },
        ),
    ]
