# Generated by Django 4.2 on 2025-12-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('farm_number', models.CharField(blank=True, help_text='Internal farm ID or permit number', max_length=50)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('operator_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('county', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='field',
            name='field_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='field',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='api.farm'),
            preserve_default=False,
        ),
    ]
