# Generated by Django 6.0 on 2025-12-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
