# Generated by Django 4.2 on 2025-12-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_farm_alter_field_field_number_field_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='api.farm'),
        ),
    ]
