# Generated by Django 4.2 on 2025-12-17 21:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_field_number_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('product_code', models.CharField(blank=True, max_length=50)),
                ('nitrogen_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Nitrogen (N) %')),
                ('phosphorus_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Phosphate (P2O5) %')),
                ('potassium_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Potash (K2O) %')),
                ('nitrate_nitrogen_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ammoniacal_nitrogen_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('urea_nitrogen_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('slow_release_nitrogen_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calcium_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('magnesium_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sulfur_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('iron_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('zinc_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('manganese_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('boron_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('form', models.CharField(choices=[('granular', 'Granular'), ('liquid', 'Liquid'), ('soluble', 'Water Soluble'), ('organic', 'Organic'), ('foliar', 'Foliar'), ('controlled_release', 'Controlled Release'), ('suspension', 'Suspension')], default='granular', max_length=20)),
                ('density_lbs_per_gallon', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('is_organic', models.BooleanField(default=False)),
                ('omri_listed', models.BooleanField(default=False)),
                ('cdfa_organic_registered', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_products', to='api.company')),
            ],
            options={
                'verbose_name': 'Fertilizer Product',
                'verbose_name_plural': 'Fertilizer Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NutrientApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('rate_unit', models.CharField(choices=[('lbs_acre', 'lbs/acre'), ('tons_acre', 'tons/acre'), ('gal_acre', 'gallons/acre'), ('oz_acre', 'oz/acre'), ('lbs_1000sqft', 'lbs/1000 sq ft'), ('units_acre', 'units/acre'), ('kg_ha', 'kg/ha'), ('L_ha', 'L/ha')], default='lbs_acre', max_length=20)),
                ('acres_treated', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate_lbs_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_product_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lbs_nitrogen_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_lbs_nitrogen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lbs_phosphorus_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lbs_potassium_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('application_method', models.CharField(choices=[('broadcast', 'Broadcast'), ('banded', 'Banded'), ('foliar', 'Foliar Spray'), ('fertigation', 'Fertigation'), ('injection', 'Soil Injection'), ('sidedress', 'Sidedress'), ('topdress', 'Topdress'), ('incorporated', 'Pre-plant Incorporated'), ('drip', 'Drip/Micro-irrigation'), ('aerial', 'Aerial Application')], default='broadcast', max_length=20)),
                ('applied_by', models.CharField(blank=True, max_length=100)),
                ('custom_applicator', models.BooleanField(default=False)),
                ('applicator_company', models.CharField(blank=True, max_length=100)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_unit', models.CharField(blank=True, max_length=20)),
                ('total_product_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrient_applications_created', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_applications', to='api.field')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='api.fertilizerproduct')),
                ('water_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrient_applications', to='api.watersource')),
            ],
            options={
                'verbose_name': 'Nutrient Application',
                'verbose_name_plural': 'Nutrient Applications',
                'ordering': ['-application_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutrientPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('crop', models.CharField(max_length=100)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yield_unit', models.CharField(blank=True, max_length=30)),
                ('planned_nitrogen_lbs_acre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('soil_nitrogen_credit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('irrigation_water_nitrogen', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('organic_matter_credit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('coalition_name', models.CharField(blank=True, max_length=100)),
                ('coalition_member_id', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100)),
                ('prepared_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_plans', to='api.field')),
            ],
            options={
                'verbose_name': 'Nutrient Plan',
                'verbose_name_plural': 'Nutrient Plans',
                'ordering': ['-year', 'field__name'],
                'unique_together': {('field', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='nutrientapplication',
            index=models.Index(fields=['application_date'], name='api_nutrien_applica_9f0a94_idx'),
        ),
        migrations.AddIndex(
            model_name='nutrientapplication',
            index=models.Index(fields=['field', 'application_date'], name='api_nutrien_field_i_8b3be3_idx'),
        ),
        migrations.AddIndex(
            model_name='fertilizerproduct',
            index=models.Index(fields=['name'], name='api_fertili_name_5c33e9_idx'),
        ),
        migrations.AddIndex(
            model_name='fertilizerproduct',
            index=models.Index(fields=['nitrogen_pct'], name='api_fertili_nitroge_3b21ea_idx'),
        ),
        migrations.AddIndex(
            model_name='fertilizerproduct',
            index=models.Index(fields=['active'], name='api_fertili_active_ec1793_idx'),
        ),
    ]
