# Generated by Django 4.2 on 2025-12-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_well_wellreading_waterallocation_metercalibration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apn', models.CharField(help_text='County assessor parcel number (e.g., 123-0-456-789)', max_length=50, verbose_name='Assessor Parcel Number')),
                ('acreage', models.DecimalField(blank=True, decimal_places=2, help_text='Acreage of this parcel', max_digits=10, null=True)),
                ('ownership_type', models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('managed', 'Managed')], default='owned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='api.farm')),
            ],
            options={
                'verbose_name': 'Farm Parcel',
                'verbose_name_plural': 'Farm Parcels',
                'ordering': ['apn'],
                'unique_together': {('farm', 'apn')},
            },
        ),
    ]
