# Generated by Django 4.2 on 2025-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_nutrient_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='estimated_total_acres',
            field=models.IntegerField(blank=True, help_text='Estimated total acreage across all farms', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether the company has completed initial setup'),
        ),
        migrations.AddField(
            model_name='company',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='When onboarding was completed', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='onboarding_step',
            field=models.CharField(choices=[('company_info', 'Company Info'), ('boundary', 'Farm Boundary'), ('fields', 'Fields'), ('water', 'Water Sources'), ('complete', 'Complete'), ('skipped', 'Skipped')], default='company_info', help_text='Current step in the onboarding process', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_crop',
            field=models.CharField(blank=True, help_text='Primary crop type for this company', max_length=50),
        ),
    ]
