# Generated by Django 4.2 on 2025-12-10 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_field_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Well #1', 'North Pond'", max_length=200)),
                ('source_type', models.CharField(choices=[('well', 'Well'), ('municipal', 'Municipal/Public'), ('surface', 'Surface Water (pond, stream, etc.)'), ('other', 'Other')], max_length=20)),
                ('location_description', models.TextField(blank=True, help_text='Physical location or GPS coordinates')),
                ('used_for_irrigation', models.BooleanField(default=True)),
                ('used_for_washing', models.BooleanField(default=False)),
                ('used_for_pesticide_mixing', models.BooleanField(default=False)),
                ('test_frequency_days', models.IntegerField(default=365, help_text='How often to test (365 = annually, 90 = quarterly)')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='water_sources', to='api.farm')),
                ('fields_served', models.ManyToManyField(blank=True, related_name='water_sources', to='api.field')),
            ],
            options={
                'ordering': ['farm', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WaterTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('test_type', models.CharField(choices=[('microbial', 'Microbial (E. coli/Coliform)'), ('chemical', 'Chemical Analysis'), ('both', 'Microbial & Chemical')], max_length=20)),
                ('lab_name', models.CharField(blank=True, help_text='Testing laboratory', max_length=200)),
                ('lab_certification_number', models.CharField(blank=True, max_length=100)),
                ('ecoli_result', models.DecimalField(blank=True, decimal_places=2, help_text='E. coli count (CFU or MPN per 100mL)', max_digits=10, null=True)),
                ('total_coliform_result', models.DecimalField(blank=True, decimal_places=2, help_text='Total coliform count', max_digits=10, null=True)),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nitrate_level', models.DecimalField(blank=True, decimal_places=2, help_text='mg/L', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Results'), ('pass', 'Pass'), ('fail', 'Fail - Action Required')], default='pending', max_length=20)),
                ('corrective_actions', models.TextField(blank=True, help_text='Actions taken if test failed (e.g., stopped use, re-treatment, re-test)')),
                ('retest_date', models.DateField(blank=True, null=True)),
                ('lab_report_file', models.FileField(blank=True, null=True, upload_to='water_tests/')),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_tests', to='api.watersource')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
