# Generated by Django 4.2 on 2025-12-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_watersource_watertest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesticideproduct',
            options={'ordering': ['product_name'], 'verbose_name': 'Pesticide Product', 'verbose_name_plural': 'Pesticide Products'},
        ),
        migrations.AddField(
            model_name='pesticideapplication',
            name='applicator_license_no',
            field=models.CharField(blank=True, help_text='California Department of Pesticide Regulation license number', max_length=50),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this product actively used on your farm?'),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='active_status_california',
            field=models.BooleanField(default=True, help_text='Currently registered for use in California?'),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='approved_crops',
            field=models.TextField(blank=True, help_text='Comma-separated list of approved crops/sites'),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='buffer_zone_feet',
            field=models.IntegerField(blank=True, help_text='Buffer zone distance in feet', null=True),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='buffer_zone_required',
            field=models.BooleanField(default=False, help_text='Requires buffer zones?'),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='california_registration_number',
            field=models.CharField(blank=True, help_text='California DPR registration number (if different from EPA)', max_length=50),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit (for cost tracking)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='density_specific_gravity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Specific gravity or density (for conversions)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='endangered_species_restrictions',
            field=models.BooleanField(default=False, help_text='Has endangered species restrictions?'),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='formulation_code',
            field=models.CharField(blank=True, help_text='EPA formulation code (e.g., EC, WP, G)', max_length=10),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='groundwater_advisory',
            field=models.BooleanField(default=False, help_text='Has groundwater advisory?'),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='is_fumigant',
            field=models.BooleanField(default=False, help_text='Is this a fumigant product?'),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='label_url',
            field=models.URLField(blank=True, help_text='URL to product label PDF'),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='max_applications_per_season',
            field=models.IntegerField(blank=True, help_text='Maximum number of applications per season', null=True),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='max_rate_per_application',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum rate per application', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='max_rate_unit',
            field=models.CharField(blank=True, choices=[('lbs/acre', 'lbs/acre'), ('gal/acre', 'gal/acre'), ('oz/acre', 'oz/acre'), ('fl oz/acre', 'fl oz/acre'), ('kg/ha', 'kg/ha'), ('L/ha', 'L/ha')], help_text='Unit for max rate', max_length=20),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or special instructions'),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='phi_days',
            field=models.IntegerField(blank=True, help_text='Pre-Harvest Interval in days', null=True),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='product_status',
            field=models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', help_text='Current product status', max_length=20),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='product_type',
            field=models.CharField(blank=True, choices=[('insecticide', 'Insecticide'), ('herbicide', 'Herbicide'), ('fungicide', 'Fungicide'), ('fumigant', 'Fumigant'), ('adjuvant', 'Adjuvant'), ('plant_growth_regulator', 'Plant Growth Regulator'), ('rodenticide', 'Rodenticide'), ('other', 'Other')], help_text='Primary product type', max_length=50),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='rei_days',
            field=models.IntegerField(blank=True, help_text='Alternative REI in days (some products use days)', null=True),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='rei_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Re-Entry Interval in hours (e.g., 12, 24, 48)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='sds_url',
            field=models.URLField(blank=True, help_text='URL to Safety Data Sheet'),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='Additional keywords for searching (auto-populated)'),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='signal_word',
            field=models.CharField(blank=True, choices=[('DANGER', 'Danger'), ('WARNING', 'Warning'), ('CAUTION', 'Caution'), ('NONE', 'None')], help_text='Signal word from label', max_length=20),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='unit_size',
            field=models.CharField(blank=True, help_text="Standard unit size (e.g., '2.5 gallon jug', '50 lb bag')", max_length=50),
        ),
        migrations.AlterField(
            model_name='pesticideproduct',
            name='active_ingredients',
            field=models.TextField(blank=True, help_text='Active ingredient(s) and percentages'),
        ),
        migrations.AlterField(
            model_name='pesticideproduct',
            name='epa_registration_number',
            field=models.CharField(help_text='EPA Registration Number (e.g., 12345-678)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pesticideproduct',
            name='formulation_type',
            field=models.CharField(blank=True, help_text='e.g., EC, WP, G, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='pesticideproduct',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer/registrant name', max_length=200),
        ),
        migrations.AlterField(
            model_name='pesticideproduct',
            name='product_name',
            field=models.CharField(help_text='Product trade name', max_length=200),
        ),
        migrations.AlterField(
            model_name='pesticideproduct',
            name='restricted_use',
            field=models.BooleanField(default=False, help_text='Restricted Use Pesticide (RUP)'),
        ),
        migrations.AddIndex(
            model_name='pesticideproduct',
            index=models.Index(fields=['epa_registration_number'], name='api_pestici_epa_reg_a75ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='pesticideproduct',
            index=models.Index(fields=['product_name'], name='api_pestici_product_d79a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='pesticideproduct',
            index=models.Index(fields=['product_type'], name='api_pestici_product_d46387_idx'),
        ),
        migrations.AddIndex(
            model_name='pesticideproduct',
            index=models.Index(fields=['active'], name='api_pestici_active_46e045_idx'),
        ),
    ]
