# Generated by Django 4.2 on 2025-12-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_estimated_total_acres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='county',
            field=models.CharField(blank=True, help_text='California county - determines County Ag Commissioner for PUR reporting', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='federal_tax_id',
            field=models.CharField(blank=True, help_text='EIN/Federal Tax ID (optional, for internal records)', max_length=20, verbose_name='Federal Tax ID'),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the company'),
        ),
        migrations.AddField(
            model_name='company',
            name='pca_license',
            field=models.CharField(blank=True, help_text='Pest Control Advisor license number', max_length=50, verbose_name='PCA License'),
        ),
        migrations.AddField(
            model_name='company',
            name='qac_license',
            field=models.CharField(blank=True, help_text='Qualified Applicator Certificate number', max_length=50, verbose_name='QAC License'),
        ),
        migrations.AddField(
            model_name='company',
            name='qal_license',
            field=models.CharField(blank=True, help_text='Qualified Applicator License number', max_length=50, verbose_name='QAL License'),
        ),
        migrations.AddField(
            model_name='company',
            name='state_tax_id',
            field=models.CharField(blank=True, help_text='CA State Tax ID (optional)', max_length=20, verbose_name='State Tax ID'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL'),
        ),
    ]
