# Generated by Django 4.2 on 2025-12-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_buyer_harvest_laborcontractor_harvestload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude coordinate (e.g., 36.7378)', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='farm',
            name='gps_long',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude coordinate (e.g., -119.7871)', max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='field',
            name='boundary_geojson',
            field=models.JSONField(blank=True, help_text='Field boundary polygon in GeoJSON format', null=True, verbose_name='Boundary GeoJSON'),
        ),
        migrations.AddField(
            model_name='field',
            name='calculated_acres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acreage calculated from drawn boundary', max_digits=10, null=True, verbose_name='Calculated Acres'),
        ),
    ]
