# Generated by Django 4.2 on 2026-01-16 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_harvest_system_improvements_sprint1'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Cached latitude for weather lookup', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Cached longitude for weather lookup', max_digits=10)),
                ('weather_data', models.JSONField(default=dict, help_text='Current weather data from API')),
                ('forecast_data', models.JSONField(blank=True, default=dict, help_text='7-day forecast data from API', null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True, help_text='When weather data was last fetched')),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_cache', to='api.farm')),
            ],
            options={
                'verbose_name': 'Weather Cache',
                'verbose_name_plural': 'Weather Caches',
            },
        ),
    ]
