# Generated by Django 4.2 on 2026-01-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_irrigation_scheduling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Common name (e.g., 'Navel Orange', 'Hass Avocado')", max_length=100)),
                ('scientific_name', models.CharField(blank=True, help_text='Scientific/botanical name', max_length=200)),
                ('variety', models.CharField(blank=True, help_text='Specific variety or cultivar', max_length=100)),
                ('category', models.CharField(choices=[('citrus', 'Citrus'), ('deciduous_fruit', 'Deciduous Fruit'), ('subtropical', 'Subtropical'), ('vine', 'Vine'), ('row_crop', 'Row Crop'), ('vegetable', 'Vegetable'), ('nut', 'Nut'), ('berry', 'Berry'), ('other', 'Other')], default='other', help_text='Crop category for grouping', max_length=30)),
                ('crop_type', models.CharField(choices=[('tree', 'Tree'), ('vine', 'Vine'), ('bush', 'Bush'), ('row', 'Row Crop'), ('perennial', 'Perennial'), ('annual', 'Annual')], default='tree', help_text='Plant type (tree, vine, row crop, etc.)', max_length=20)),
                ('typical_spacing_row_ft', models.DecimalField(blank=True, decimal_places=1, help_text='Typical row spacing in feet', max_digits=5, null=True)),
                ('typical_spacing_tree_ft', models.DecimalField(blank=True, decimal_places=1, help_text='Typical in-row/tree spacing in feet', max_digits=5, null=True)),
                ('typical_root_depth_inches', models.IntegerField(blank=True, help_text='Typical root depth for irrigation calculations', null=True)),
                ('years_to_maturity', models.IntegerField(blank=True, help_text='Typical years from planting to full production', null=True)),
                ('productive_lifespan_years', models.IntegerField(blank=True, help_text='Expected productive lifespan', null=True)),
                ('kc_mature', models.DecimalField(blank=True, decimal_places=2, help_text='Mature crop coefficient (Kc) for ET calculations', max_digits=3, null=True)),
                ('kc_young', models.DecimalField(blank=True, decimal_places=2, help_text='Young tree/vine crop coefficient', max_digits=3, null=True)),
                ('typical_harvest_months', models.CharField(blank=True, help_text="Typical harvest window (e.g., 'Nov-Apr')", max_length=100)),
                ('default_bin_weight_lbs', models.IntegerField(default=900, help_text='Default bin weight for harvest calculations')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rootstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Rootstock name (e.g., 'Carrizo Citrange', '1103P')", max_length=100)),
                ('code', models.CharField(blank=True, help_text='Common abbreviation or code', max_length=50)),
                ('primary_category', models.CharField(choices=[('citrus', 'Citrus'), ('deciduous_fruit', 'Deciduous Fruit'), ('subtropical', 'Subtropical'), ('vine', 'Vine'), ('row_crop', 'Row Crop'), ('vegetable', 'Vegetable'), ('nut', 'Nut'), ('berry', 'Berry'), ('other', 'Other')], default='citrus', help_text='Primary crop category', max_length=30)),
                ('vigor', models.CharField(blank=True, choices=[('dwarf', 'Dwarf'), ('semi_dwarf', 'Semi-Dwarf'), ('standard', 'Standard'), ('vigorous', 'Vigorous')], help_text='Growth vigor classification', max_length=20)),
                ('disease_resistance', models.TextField(blank=True, help_text='Known disease resistances')),
                ('soil_tolerance', models.TextField(blank=True, help_text='Soil condition tolerances (salinity, pH, drainage)')),
                ('cold_hardiness', models.CharField(blank=True, help_text='Cold hardiness rating', max_length=50)),
                ('drought_tolerance', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rootstock',
                'verbose_name_plural': 'Rootstocks',
                'ordering': ['primary_category', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='cimisdatacache',
            name='api_cimisda_source_idx',
        ),
        migrations.RemoveIndex(
            model_name='irrigationrecommendation',
            name='api_irrigat_zone_re_idx',
        ),
        migrations.RemoveIndex(
            model_name='irrigationrecommendation',
            name='api_irrigat_status_idx',
        ),
        migrations.RenameIndex(
            model_name='irrigationzone',
            new_name='api_irrigat_field_i_01f3a8_idx',
            old_name='api_irrigat_field_i_idx',
        ),
        migrations.RenameIndex(
            model_name='quarantinestatus',
            new_name='api_quarant_farm_id_f5cad6_idx',
            old_name='api_quarant_farm_id_idx',
        ),
        migrations.RenameIndex(
            model_name='quarantinestatus',
            new_name='api_quarant_field_i_f4191b_idx',
            old_name='api_quarant_field_i_idx',
        ),
        migrations.RenameIndex(
            model_name='quarantinestatus',
            new_name='api_quarant_last_ch_6e4f27_idx',
            old_name='api_quarant_last_ch_idx',
        ),
        migrations.AddField(
            model_name='field',
            name='expected_yield_per_acre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield per acre (crop-appropriate units)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('drip', 'Drip'), ('micro_sprinkler', 'Micro-Sprinkler'), ('sprinkler', 'Sprinkler'), ('flood', 'Flood'), ('furrow', 'Furrow'), ('none', 'None/Dryland')], help_text='Primary irrigation method', max_length=20),
        ),
        migrations.AddField(
            model_name='field',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='field',
            name='organic_cert_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='organic_cert_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='field',
            name='organic_certifier',
            field=models.CharField(blank=True, help_text='Organic certification agency', max_length=100),
        ),
        migrations.AddField(
            model_name='field',
            name='organic_status',
            field=models.CharField(choices=[('conventional', 'Conventional'), ('transitional', 'Transitional'), ('certified', 'Certified Organic')], default='conventional', max_length=20),
        ),
        migrations.AddField(
            model_name='field',
            name='row_orientation',
            field=models.CharField(blank=True, choices=[('ns', 'North-South'), ('ew', 'East-West'), ('ne_sw', 'Northeast-Southwest'), ('nw_se', 'Northwest-Southeast')], help_text='Row orientation for sun exposure', max_length=10),
        ),
        migrations.AddField(
            model_name='field',
            name='row_spacing_ft',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Row spacing in feet', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('sandy', 'Sandy'), ('sandy_loam', 'Sandy Loam'), ('loam', 'Loam'), ('clay_loam', 'Clay Loam'), ('clay', 'Clay'), ('silty_loam', 'Silty Loam'), ('silty_clay', 'Silty Clay')], help_text='Predominant soil type', max_length=30),
        ),
        migrations.AddField(
            model_name='field',
            name='tree_count',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of trees/plants', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='tree_spacing_ft',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='In-row/tree spacing in feet', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='trees_per_acre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tree/plant density (calculated or manual)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='trellis_system',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('vertical_shoot', 'Vertical Shoot Position (VSP)'), ('lyre', 'Lyre/U-Shape'), ('geneva_double', 'Geneva Double Curtain'), ('high_wire', 'High Wire'), ('pergola', 'Pergola/Arbor'), ('espalier', 'Espalier'), ('stake', 'Stake'), ('other', 'Other')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='field',
            name='year_planted',
            field=models.IntegerField(blank=True, help_text='Year trees/vines were planted (alternative to planting_date)', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='yield_unit',
            field=models.CharField(blank=True, default='bins', help_text='Unit for yield (bins, lbs, tons, boxes, etc.)', max_length=30),
        ),
        migrations.AlterField(
            model_name='field',
            name='current_crop',
            field=models.CharField(blank=True, help_text="Legacy text field - use 'crop' ForeignKey instead", max_length=100),
        ),
        migrations.AddIndex(
            model_name='irrigationzone',
            index=models.Index(fields=['active'], name='api_irrigat_active_a49db3_idx'),
        ),
        migrations.AddField(
            model_name='rootstock',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Null for system defaults', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rootstocks', to='api.company'),
        ),
        migrations.AddField(
            model_name='rootstock',
            name='compatible_crops',
            field=models.ManyToManyField(blank=True, help_text='Crops this rootstock is typically used with', related_name='compatible_rootstocks', to='api.crop'),
        ),
        migrations.AddField(
            model_name='crop',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Null for system defaults, set for custom company crops', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='api.company'),
        ),
        migrations.AddField(
            model_name='field',
            name='crop',
            field=models.ForeignKey(blank=True, help_text='Primary crop planted in this field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='api.crop'),
        ),
        migrations.AddField(
            model_name='field',
            name='rootstock',
            field=models.ForeignKey(blank=True, help_text='Rootstock variety (for tree/vine crops)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='api.rootstock'),
        ),
        migrations.AddIndex(
            model_name='rootstock',
            index=models.Index(fields=['name'], name='api_rootsto_name_779d12_idx'),
        ),
        migrations.AddIndex(
            model_name='rootstock',
            index=models.Index(fields=['primary_category'], name='api_rootsto_primary_a07311_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['name'], name='api_crop_name_ada5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['category'], name='api_crop_categor_d9b7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['active'], name='api_crop_active_12cfa6_idx'),
        ),
    ]
