# Generated by Django 4.2 on 2026-01-17 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_fix_satellite_rls_policy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detectedtree',
            new_name='api_detecte_field_i_c78d1f_idx',
            old_name='api_detect_field_s_1j2k3l_idx',
        ),
        migrations.RenameIndex(
            model_name='detectedtree',
            new_name='api_detecte_detecti_a746b7_idx',
            old_name='api_detect_detecti_4m5n6o_idx',
        ),
        migrations.RenameIndex(
            model_name='detectedtree',
            new_name='api_detecte_latitud_a264e3_idx',
            old_name='api_detect_lat_lng_7p8q9r_idx',
        ),
        migrations.RenameIndex(
            model_name='satelliteimage',
            new_name='api_satelli_company_5f310f_idx',
            old_name='api_satelli_company_4b8e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='satelliteimage',
            new_name='api_satelli_capture_054194_idx',
            old_name='api_satelli_capture_0c2a3f_idx',
        ),
        migrations.RenameIndex(
            model_name='treedetectionrun',
            new_name='api_treedet_field_i_c954b5_idx',
            old_name='api_treede_field_i_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='treedetectionrun',
            new_name='api_treedet_satelli_f66862_idx',
            old_name='api_treede_satelli_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='treedetectionrun',
            new_name='api_treedet_created_d6b3f1_idx',
            old_name='api_treede_created_7g8h9i_idx',
        ),
    ]
