# Generated by Django 4.2 on 2026-01-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_lidar_integration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lidardetectedtree',
            new_name='api_lidar_d_process_d38be0_idx',
            old_name='api_lidar_d_process_7d8e9f_idx',
        ),
        migrations.RenameIndex(
            model_name='lidardetectedtree',
            new_name='api_lidar_d_field_i_02587e_idx',
            old_name='api_lidar_d_field_i_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='lidardetectedtree',
            new_name='api_lidar_d_latitud_07ef6b_idx',
            old_name='api_lidar_d_latitud_d4e5f6_idx',
        ),
    ]
