# Generated by Django 4.2 - Unified Tree Identity System

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_rename_api_lidar_d_process_7d8e9f_idx_api_lidar_d_process_d38be0_idx_and_more'),
    ]

    operations = [
        # Tree - Master tree identity that persists across detection runs
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('height_m', models.FloatField(blank=True, null=True)),
                ('canopy_diameter_m', models.FloatField(blank=True, null=True)),
                ('canopy_area_sqm', models.FloatField(blank=True, null=True)),
                ('latest_ndvi', models.FloatField(blank=True, null=True)),
                ('ground_elevation_m', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(
                    choices=[
                        ('active', 'Active'),
                        ('dead', 'Dead'),
                        ('missing', 'Missing'),
                        ('uncertain', 'Uncertain'),
                        ('removed', 'Removed'),
                    ],
                    default='active',
                    max_length=20
                )),
                ('identity_confidence', models.CharField(
                    choices=[
                        ('high', 'High'),
                        ('medium', 'Medium'),
                        ('low', 'Low'),
                    ],
                    default='medium',
                    max_length=10
                )),
                ('satellite_observation_count', models.PositiveIntegerField(default=0)),
                ('lidar_observation_count', models.PositiveIntegerField(default=0)),
                ('first_observed', models.DateField()),
                ('last_observed', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='verified_trees',
                    to=settings.AUTH_USER_MODEL
                )),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('tree_label', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('inferred_row', models.PositiveIntegerField(blank=True, null=True)),
                ('inferred_position', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='trees',
                    to='api.field'
                )),
            ],
            options={
                'db_table': 'api_tree',
                'verbose_name': 'Tree',
                'verbose_name_plural': 'Trees',
                'ordering': ['-last_observed', 'id'],
            },
        ),

        # TreeMatchingRun - Records each execution of tree matching algorithm
        migrations.CreateModel(
            name='TreeMatchingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_distance_threshold_m', models.FloatField(default=3.0)),
                ('canopy_weight', models.FloatField(default=0.3)),
                ('ndvi_weight', models.FloatField(default=0.3)),
                ('distance_weight', models.FloatField(default=0.4)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('running', 'Running'),
                        ('completed', 'Completed'),
                        ('failed', 'Failed'),
                    ],
                    default='pending',
                    max_length=20
                )),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('trees_matched', models.IntegerField(blank=True, null=True)),
                ('new_trees_created', models.IntegerField(blank=True, null=True)),
                ('trees_marked_missing', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tree_matching_runs',
                    to='api.field'
                )),
                ('lidar_run', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='tree_matching_runs',
                    to='api.lidarprocessingrun'
                )),
                ('satellite_run', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='tree_matching_runs',
                    to='api.treedetectionrun'
                )),
                ('triggered_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='triggered_tree_matching_runs',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'api_tree_matching_run',
                'verbose_name': 'Tree Matching Run',
                'verbose_name_plural': 'Tree Matching Runs',
                'ordering': ['-created_at'],
            },
        ),

        # TreeObservation - Links Tree to specific detections from satellite or LiDAR
        migrations.CreateModel(
            name='TreeObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(
                    choices=[
                        ('satellite', 'Satellite'),
                        ('lidar', 'LiDAR'),
                        ('manual', 'Manual'),
                    ],
                    max_length=20
                )),
                ('match_method', models.CharField(
                    choices=[
                        ('spatial', 'Spatial'),
                        ('manual', 'Manual'),
                        ('initial', 'Initial'),
                    ],
                    default='spatial',
                    max_length=20
                )),
                ('match_distance_m', models.FloatField(blank=True, null=True)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('observation_date', models.DateField(db_index=True)),
                ('observed_latitude', models.FloatField()),
                ('observed_longitude', models.FloatField()),
                ('observed_height_m', models.FloatField(blank=True, null=True)),
                ('observed_canopy_diameter_m', models.FloatField(blank=True, null=True)),
                ('observed_canopy_area_sqm', models.FloatField(blank=True, null=True)),
                ('observed_ndvi', models.FloatField(blank=True, null=True)),
                ('observed_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lidar_detection', models.OneToOneField(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tree_observation',
                    to='api.lidardetectedtree'
                )),
                ('matching_run', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='observations',
                    to='api.treematchingrun'
                )),
                ('satellite_detection', models.OneToOneField(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tree_observation',
                    to='api.detectedtree'
                )),
                ('tree', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='observations',
                    to='api.tree'
                )),
            ],
            options={
                'db_table': 'api_tree_observation',
                'verbose_name': 'Tree Observation',
                'verbose_name_plural': 'Tree Observations',
                'ordering': ['-observation_date', '-created_at'],
            },
        ),

        # Indexes for Tree model
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['field', 'status'], name='api_tree_field_i_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['field', 'last_observed'], name='api_tree_field_i_lastobs_idx'),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['latitude', 'longitude'], name='api_tree_lat_lng_idx'),
        ),

        # Indexes for TreeObservation model
        migrations.AddIndex(
            model_name='treeobservation',
            index=models.Index(fields=['tree', 'observation_date'], name='api_treeobs_tree_date_idx'),
        ),
        migrations.AddIndex(
            model_name='treeobservation',
            index=models.Index(fields=['source_type', 'observation_date'], name='api_treeobs_source_date_idx'),
        ),

        # Indexes for TreeMatchingRun model
        migrations.AddIndex(
            model_name='treematchingrun',
            index=models.Index(fields=['field', 'status'], name='api_treematch_field_status_idx'),
        ),
    ]
