# Generated by Django 4.2 - Tree Feedback System for ML Training

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_populate_tree_identities'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(
                    choices=[
                        ('false_positive', 'False Positive - Not a Tree'),
                        ('false_negative', 'False Negative - Missed/Wrong Status'),
                        ('misidentification', 'Misidentification - Wrong Tree Matched'),
                        ('location_error', 'Location Error - Position Incorrect'),
                        ('attribute_error', 'Attribute Error - Measurements Wrong'),
                        ('verified_correct', 'Verified Correct'),
                    ],
                    max_length=30
                )),
                ('notes', models.TextField(blank=True, help_text='Explanation of the issue')),
                ('suggested_latitude', models.FloatField(blank=True, null=True, help_text='Suggested corrected latitude')),
                ('suggested_longitude', models.FloatField(blank=True, null=True, help_text='Suggested corrected longitude')),
                ('suggested_corrections', models.JSONField(blank=True, default=dict, help_text='Key-value pairs of suggested attribute corrections')),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending Review'),
                        ('accepted', 'Accepted'),
                        ('rejected', 'Rejected'),
                    ],
                    default='pending',
                    max_length=20
                )),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes from reviewer about resolution')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exported_for_training', models.BooleanField(default=False, help_text='Whether this feedback has been exported for ML training')),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('tree', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='feedback',
                    to='api.tree'
                )),
                ('observation', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='feedback',
                    to='api.treeobservation',
                    help_text='Specific observation being flagged (optional)'
                )),
                ('created_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='tree_feedback_created',
                    to=settings.AUTH_USER_MODEL
                )),
                ('resolved_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='resolved_tree_feedback',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'api_tree_feedback',
                'verbose_name': 'Tree Feedback',
                'verbose_name_plural': 'Tree Feedback',
                'ordering': ['-created_at'],
            },
        ),
        # Indexes
        migrations.AddIndex(
            model_name='treefeedback',
            index=models.Index(fields=['tree', 'feedback_type'], name='api_treefb_tree_type_idx'),
        ),
        migrations.AddIndex(
            model_name='treefeedback',
            index=models.Index(fields=['status', 'created_at'], name='api_treefb_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='treefeedback',
            index=models.Index(fields=['exported_for_training'], name='api_treefb_exported_idx'),
        ),
    ]
