# Generated by Django 4.2 - Satellite Kc Adjustment Configuration

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds configuration fields to IrrigationZone for satellite-based
    crop coefficient (Kc) adjustments.

    These fields allow the irrigation scheduler to use satellite-derived
    canopy coverage and NDVI data to dynamically adjust Kc values.
    """

    dependencies = [
        ('api', '0022_tree_feedback'),
    ]

    operations = [
        # Satellite Kc adjustment configuration
        migrations.AddField(
            model_name='irrigationzone',
            name='use_satellite_kc_adjustment',
            field=models.BooleanField(
                default=True,
                help_text='Use satellite canopy data to adjust crop coefficients'
            ),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='reference_canopy_coverage',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Override expected mature canopy coverage for this zone (%). '
                          'If blank, uses crop-specific defaults based on tree age.',
                max_digits=5,
                null=True,
            ),
        ),

        # NDVI stress response configuration
        migrations.AddField(
            model_name='irrigationzone',
            name='ndvi_stress_modifier_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Increase water for stressed vegetation based on NDVI'
            ),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='ndvi_healthy_threshold',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.75'),
                help_text='NDVI values above this are considered healthy (no adjustment)',
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='ndvi_stress_multiplier',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('1.10'),
                help_text='Multiply Kc by this factor when vegetation is stressed',
                max_digits=3,
            ),
        ),
    ]
