# Generated by Django 4.2 on 2026-01-19 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_satellite_kc_adjustment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'verbose_name': 'Tree', 'verbose_name_plural': 'Trees'},
        ),
        migrations.AlterModelOptions(
            name='treeobservation',
            options={'verbose_name': 'Tree Observation', 'verbose_name_plural': 'Tree Observations'},
        ),
        migrations.RemoveIndex(
            model_name='tree',
            name='api_tree_field_i_lastobs_idx',
        ),
        migrations.RemoveIndex(
            model_name='treematchingrun',
            name='api_treematch_field_status_idx',
        ),
        migrations.RenameIndex(
            model_name='tree',
            new_name='api_tree_field_status_idx',
            old_name='api_tree_field_i_status_idx',
        ),
        migrations.RenameIndex(
            model_name='tree',
            new_name='api_tree_lat_lon_idx',
            old_name='api_tree_lat_lng_idx',
        ),
        migrations.RemoveField(
            model_name='treematchingrun',
            name='canopy_weight',
        ),
        migrations.RemoveField(
            model_name='treematchingrun',
            name='distance_weight',
        ),
        migrations.RemoveField(
            model_name='treematchingrun',
            name='ndvi_weight',
        ),
        migrations.RemoveField(
            model_name='treeobservation',
            name='matching_run',
        ),
        migrations.RemoveField(
            model_name='treeobservation',
            name='observed_canopy_area_sqm',
        ),
        migrations.AddField(
            model_name='treematchingrun',
            name='observations_created',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treematchingrun',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Full matching parameters used'),
        ),
        migrations.AddField(
            model_name='treematchingrun',
            name='processing_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='canopy_area_sqm',
            field=models.FloatField(blank=True, help_text='Best estimate canopy area in sq meters (from LiDAR)', null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='canopy_diameter_m',
            field=models.FloatField(blank=True, help_text='Best estimate canopy diameter in meters', null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='field',
            field=models.ForeignKey(help_text='Field containing this tree', on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='api.field'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='first_observed',
            field=models.DateField(help_text='Date tree was first detected'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='ground_elevation_m',
            field=models.FloatField(blank=True, help_text='Ground elevation at tree base in meters', null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='height_m',
            field=models.FloatField(blank=True, help_text='Best estimate tree height in meters (from LiDAR)', null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='identity_confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Confidence in tree identity across observations', max_length=10),
        ),
        migrations.AlterField(
            model_name='tree',
            name='inferred_position',
            field=models.PositiveIntegerField(blank=True, help_text='Inferred position within row', null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='inferred_row',
            field=models.PositiveIntegerField(blank=True, help_text='Inferred row number in field', null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='User has manually verified this tree identity'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='last_observed',
            field=models.DateField(help_text='Date of most recent detection'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='latest_ndvi',
            field=models.FloatField(blank=True, help_text='Most recent NDVI value (from satellite)', null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='latitude',
            field=models.FloatField(help_text='Best-estimate tree center latitude (WGS84)'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lidar_observation_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of LiDAR detection observations'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='longitude',
            field=models.FloatField(help_text='Best-estimate tree center longitude (WGS84)'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='satellite_observation_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of satellite detection observations'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dead', 'Dead/Removed'), ('missing', 'Missing (Not in Recent Detections)'), ('uncertain', 'Uncertain')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='tree_label',
            field=models.CharField(blank=True, help_text="Optional user-assigned label (e.g., 'Row-3-Tree-15')", max_length=50),
        ),
        migrations.AlterField(
            model_name='tree',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for external references', unique=True),
        ),
        migrations.AlterField(
            model_name='treematchingrun',
            name='lidar_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_runs', to='api.lidarprocessingrun'),
        ),
        migrations.AlterField(
            model_name='treematchingrun',
            name='match_distance_threshold_m',
            field=models.FloatField(default=3.0, help_text='Maximum distance for tree matching (meters)'),
        ),
        migrations.AlterField(
            model_name='treematchingrun',
            name='satellite_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_runs', to='api.treedetectionrun'),
        ),
        migrations.AlterField(
            model_name='treematchingrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='treematchingrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treeobservation',
            name='match_confidence',
            field=models.FloatField(blank=True, help_text='Match confidence score (0-1)', null=True),
        ),
        migrations.AlterField(
            model_name='treeobservation',
            name='match_distance_m',
            field=models.FloatField(blank=True, help_text='Distance to tree center when matched (meters)', null=True),
        ),
        migrations.AlterField(
            model_name='treeobservation',
            name='match_method',
            field=models.CharField(choices=[('spatial', 'Spatial Proximity'), ('manual', 'Manual Assignment'), ('algorithm', 'Algorithm Match')], default='spatial', max_length=20),
        ),
        migrations.AlterField(
            model_name='treeobservation',
            name='observation_date',
            field=models.DateField(help_text='Date of the detection run'),
        ),
        migrations.AlterField(
            model_name='treeobservation',
            name='observed_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='treeobservation',
            name='source_type',
            field=models.CharField(choices=[('satellite', 'Satellite'), ('lidar', 'LiDAR')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['field', 'inferred_row', 'inferred_position'], name='api_tree_row_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['last_observed'], name='api_tree_last_obs_idx'),
        ),
        migrations.AddConstraint(
            model_name='tree',
            constraint=models.UniqueConstraint(condition=models.Q(('tree_label__gt', '')), fields=('field', 'tree_label'), name='unique_tree_label_per_field'),
        ),
    ]
