# Generated by Django 4.2 on 2026-01-19
# Disease Prevention Platform - Phase 1 Models

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_compliancedeadline_wpstrainingrecord_and_more'),
    ]

    operations = [
        # =================================================================
        # EXTERNAL DETECTION MODEL
        # Stores official disease detections from CDFA, USDA, etc.
        # =================================================================
        migrations.CreateModel(
            name='ExternalDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Source tracking
                ('source', models.CharField(
                    max_length=50,
                    choices=[
                        ('cdfa', 'California Dept of Food & Agriculture'),
                        ('usda', 'USDA APHIS'),
                        ('county_ag', 'County Agricultural Commissioner'),
                        ('uc_anr', 'UC Agriculture & Natural Resources'),
                        ('manual', 'Manual Entry'),
                    ],
                    help_text="Source of the detection data"
                )),
                ('source_id', models.CharField(
                    max_length=100,
                    blank=True,
                    help_text="External reference ID from source system"
                )),
                # Disease info
                ('disease_type', models.CharField(
                    max_length=50,
                    choices=[
                        ('hlb', 'Huanglongbing (Citrus Greening)'),
                        ('acp', 'Asian Citrus Psyllid'),
                        ('ctvd', 'Citrus Tristeza Virus'),
                        ('cyvcv', 'Citrus Yellow Vein Clearing Virus'),
                        ('canker', 'Citrus Canker'),
                        ('phytophthora', 'Phytophthora Root Rot'),
                        ('laurel_wilt', 'Laurel Wilt'),
                        ('other', 'Other'),
                    ],
                    help_text="Type of disease or pest detected"
                )),
                ('disease_name', models.CharField(
                    max_length=200,
                    help_text="Human-readable disease name"
                )),
                # Location
                ('latitude', models.DecimalField(
                    max_digits=10,
                    decimal_places=7,
                    help_text="Detection latitude coordinate"
                )),
                ('longitude', models.DecimalField(
                    max_digits=10,
                    decimal_places=7,
                    help_text="Detection longitude coordinate"
                )),
                ('county', models.CharField(
                    max_length=100,
                    help_text="County where detection occurred"
                )),
                ('city', models.CharField(
                    max_length=100,
                    blank=True,
                    help_text="City/locality of detection"
                )),
                ('location_type', models.CharField(
                    max_length=50,
                    choices=[
                        ('residential', 'Residential/Backyard'),
                        ('commercial', 'Commercial Grove'),
                        ('nursery', 'Nursery'),
                        ('unknown', 'Unknown'),
                    ],
                    default='unknown',
                    help_text="Type of location where detected"
                )),
                # Dates
                ('detection_date', models.DateField(
                    help_text="Date the detection was confirmed"
                )),
                ('reported_date', models.DateField(
                    help_text="Date reported to authorities"
                )),
                ('fetched_at', models.DateTimeField(
                    auto_now_add=True,
                    help_text="When this record was imported"
                )),
                # Status
                ('is_active', models.BooleanField(
                    default=True,
                    help_text="False if detection site has been eradicated"
                )),
                ('eradication_date', models.DateField(
                    null=True,
                    blank=True,
                    help_text="Date of confirmed eradication"
                )),
                # Metadata
                ('notes', models.TextField(
                    blank=True,
                    help_text="Additional notes about the detection"
                )),
                ('raw_data', models.JSONField(
                    default=dict,
                    help_text="Original API response or source data"
                )),
            ],
            options={
                'verbose_name': 'External Detection',
                'verbose_name_plural': 'External Detections',
                'ordering': ['-detection_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='externaldetection',
            constraint=models.UniqueConstraint(
                fields=['source', 'source_id'],
                name='unique_external_detection_source',
                condition=models.Q(source_id__gt=''),
            ),
        ),
        migrations.AddIndex(
            model_name='externaldetection',
            index=models.Index(fields=['disease_type', 'is_active'], name='idx_extdet_disease_active'),
        ),
        migrations.AddIndex(
            model_name='externaldetection',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_extdet_coords'),
        ),
        migrations.AddIndex(
            model_name='externaldetection',
            index=models.Index(fields=['county'], name='idx_extdet_county'),
        ),

        # =================================================================
        # DISEASE ALERT RULE MODEL
        # Configurable rules for generating disease alerts
        # =================================================================
        migrations.CreateModel(
            name='DiseaseAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    max_length=100,
                    help_text="Name for this alert rule"
                )),
                ('description', models.TextField(
                    blank=True,
                    help_text="Description of what this rule does"
                )),
                ('rule_type', models.CharField(
                    max_length=50,
                    choices=[
                        ('proximity', 'Proximity Alert'),
                        ('ndvi_threshold', 'NDVI Threshold'),
                        ('ndvi_change', 'NDVI Change Rate'),
                        ('canopy_loss', 'Canopy Loss'),
                        ('tree_count_change', 'Tree Count Change'),
                        ('regional_trend', 'Regional Trend'),
                    ],
                    help_text="Type of alert rule"
                )),
                ('conditions', models.JSONField(
                    default=dict,
                    help_text="Rule conditions (e.g., {disease_types: ['hlb'], radius_miles: 5})"
                )),
                ('alert_priority', models.CharField(
                    max_length=20,
                    choices=[
                        ('critical', 'Critical'),
                        ('high', 'High'),
                        ('medium', 'Medium'),
                        ('low', 'Low'),
                    ],
                    help_text="Priority level for alerts generated by this rule"
                )),
                ('send_email', models.BooleanField(
                    default=True,
                    help_text="Send email notification"
                )),
                ('send_sms', models.BooleanField(
                    default=False,
                    help_text="Send SMS notification"
                )),
                ('send_immediately', models.BooleanField(
                    default=False,
                    help_text="Send immediately vs. in daily digest"
                )),
                ('is_active', models.BooleanField(
                    default=True,
                    help_text="Rule is actively being evaluated"
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='disease_alert_rules',
                    to='api.company'
                )),
                ('created_by', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_disease_rules',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Disease Alert Rule',
                'verbose_name_plural': 'Disease Alert Rules',
                'ordering': ['name'],
            },
        ),

        # =================================================================
        # DISEASE ANALYSIS RUN MODEL
        # Tracks health analysis runs for fields (similar to TreeDetectionRun)
        # =================================================================
        migrations.CreateModel(
            name='DiseaseAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Processing status
                ('status', models.CharField(
                    max_length=20,
                    choices=[
                        ('pending', 'Pending'),
                        ('processing', 'Processing'),
                        ('completed', 'Completed'),
                        ('failed', 'Failed'),
                    ],
                    default='pending',
                    help_text="Current processing status"
                )),
                ('error_message', models.TextField(
                    blank=True,
                    help_text="Error details if analysis failed"
                )),
                # Analysis parameters
                ('analysis_type', models.CharField(
                    max_length=50,
                    choices=[
                        ('ndvi_trend', 'NDVI Trend Analysis'),
                        ('anomaly_detection', 'Anomaly Detection'),
                        ('full', 'Full Health Analysis'),
                    ],
                    default='full',
                    help_text="Type of analysis performed"
                )),
                ('parameters', models.JSONField(
                    default=dict,
                    help_text="Analysis parameters (thresholds, lookback period, etc.)"
                )),
                # Results - Field Level
                ('avg_ndvi', models.DecimalField(
                    max_digits=4,
                    decimal_places=3,
                    null=True,
                    help_text="Average NDVI value across field"
                )),
                ('ndvi_change_30d', models.DecimalField(
                    max_digits=5,
                    decimal_places=3,
                    null=True,
                    help_text="NDVI change vs. 30 days ago"
                )),
                ('ndvi_change_90d', models.DecimalField(
                    max_digits=5,
                    decimal_places=3,
                    null=True,
                    help_text="NDVI change vs. 90 days ago"
                )),
                ('canopy_coverage_percent', models.DecimalField(
                    max_digits=5,
                    decimal_places=2,
                    null=True,
                    help_text="Canopy coverage percentage"
                )),
                ('canopy_change_30d', models.DecimalField(
                    max_digits=5,
                    decimal_places=2,
                    null=True,
                    help_text="Canopy change vs. 30 days ago"
                )),
                # Results - Tree Level Aggregates
                ('total_trees_analyzed', models.IntegerField(
                    default=0,
                    help_text="Total trees included in analysis"
                )),
                ('trees_healthy', models.IntegerField(
                    default=0,
                    help_text="Trees with NDVI >= 0.65"
                )),
                ('trees_mild_stress', models.IntegerField(
                    default=0,
                    help_text="Trees with NDVI 0.55-0.65"
                )),
                ('trees_moderate_stress', models.IntegerField(
                    default=0,
                    help_text="Trees with NDVI 0.45-0.55"
                )),
                ('trees_severe_stress', models.IntegerField(
                    default=0,
                    help_text="Trees with NDVI < 0.45"
                )),
                ('trees_declining', models.IntegerField(
                    default=0,
                    help_text="Trees with NDVI drop > 15% in 90d"
                )),
                # Risk Assessment
                ('health_score', models.IntegerField(
                    null=True,
                    help_text="Overall health score 0-100"
                )),
                ('risk_level', models.CharField(
                    max_length=20,
                    choices=[
                        ('low', 'Low'),
                        ('moderate', 'Moderate'),
                        ('high', 'High'),
                        ('critical', 'Critical'),
                    ],
                    null=True,
                    blank=True,
                    help_text="Risk level based on health analysis"
                )),
                ('risk_factors', models.JSONField(
                    default=list,
                    help_text="List of identified risk factors"
                )),
                # Anomaly Detection
                ('anomaly_zones', models.JSONField(
                    default=list,
                    help_text="GeoJSON features of stress clusters"
                )),
                ('anomaly_count', models.IntegerField(
                    default=0,
                    help_text="Number of anomaly zones detected"
                )),
                # Recommendations
                ('recommendations', models.JSONField(
                    default=list,
                    help_text="List of recommended actions"
                )),
                # Timestamps
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(
                    null=True,
                    help_text="When analysis completed"
                )),
                # Review
                ('review_notes', models.TextField(
                    blank=True,
                    help_text="Notes from user review"
                )),
                # Relationships
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='disease_analyses',
                    to='api.company'
                )),
                ('field', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='disease_analyses',
                    to='api.field'
                )),
                ('satellite_image', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='disease_analyses',
                    to='api.satelliteimage'
                )),
                ('tree_detection_run', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='disease_analyses',
                    to='api.treedetectionrun'
                )),
                ('reviewed_by', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='reviewed_disease_analyses',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Disease Analysis Run',
                'verbose_name_plural': 'Disease Analysis Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='diseaseanalysisrun',
            index=models.Index(fields=['company', 'status'], name='idx_disanalysis_co_status'),
        ),
        migrations.AddIndex(
            model_name='diseaseanalysisrun',
            index=models.Index(fields=['field', '-created_at'], name='idx_disanalysis_field_date'),
        ),

        # =================================================================
        # DISEASE ALERT MODEL
        # User notifications for disease threats
        # =================================================================
        migrations.CreateModel(
            name='DiseaseAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(
                    max_length=50,
                    choices=[
                        ('proximity_hlb', 'HLB Detected Nearby'),
                        ('proximity_acp', 'ACP Activity Nearby'),
                        ('proximity_other', 'Other Disease Nearby'),
                        ('ndvi_anomaly', 'NDVI Anomaly Detected'),
                        ('tree_decline', 'Tree Decline Detected'),
                        ('canopy_loss', 'Canopy Loss Detected'),
                        ('regional_trend', 'Regional Health Trend'),
                        ('scouting_verified', 'Verified Scouting Report'),
                    ],
                    help_text="Type of disease alert"
                )),
                ('priority', models.CharField(
                    max_length=20,
                    choices=[
                        ('critical', 'Critical'),
                        ('high', 'High'),
                        ('medium', 'Medium'),
                        ('low', 'Low'),
                    ],
                    help_text="Alert priority level"
                )),
                ('title', models.CharField(
                    max_length=200,
                    help_text="Alert title"
                )),
                ('message', models.TextField(
                    help_text="Detailed alert message"
                )),
                # Context
                ('distance_miles', models.DecimalField(
                    max_digits=6,
                    decimal_places=2,
                    null=True,
                    blank=True,
                    help_text="Distance to threat in miles"
                )),
                # Actions
                ('recommended_actions', models.JSONField(
                    default=list,
                    help_text="List of recommended actions"
                )),
                ('action_url', models.CharField(
                    max_length=500,
                    blank=True,
                    help_text="Frontend URL for action"
                )),
                ('action_label', models.CharField(
                    max_length=100,
                    blank=True,
                    help_text="Label for action button"
                )),
                # Status
                ('is_active', models.BooleanField(
                    default=True,
                    help_text="Alert is currently active"
                )),
                ('is_acknowledged', models.BooleanField(
                    default=False,
                    help_text="User has acknowledged alert"
                )),
                ('acknowledged_at', models.DateTimeField(
                    null=True,
                    blank=True,
                    help_text="When alert was acknowledged"
                )),
                # Notifications
                ('email_sent', models.BooleanField(
                    default=False,
                    help_text="Email notification sent"
                )),
                ('email_sent_at', models.DateTimeField(
                    null=True,
                    blank=True,
                    help_text="When email was sent"
                )),
                ('sms_sent', models.BooleanField(
                    default=False,
                    help_text="SMS notification sent"
                )),
                ('sms_sent_at', models.DateTimeField(
                    null=True,
                    blank=True,
                    help_text="When SMS was sent"
                )),
                # Timestamps
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(
                    null=True,
                    blank=True,
                    help_text="Auto-dismiss after this time"
                )),
                # Relationships
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='disease_alerts',
                    to='api.company'
                )),
                ('farm', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='disease_alerts',
                    to='api.farm'
                )),
                ('field', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='disease_alerts',
                    to='api.field'
                )),
                ('related_detection', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='alerts',
                    to='api.externaldetection'
                )),
                ('related_analysis', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='alerts',
                    to='api.diseaseanalysisrun'
                )),
                ('acknowledged_by', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='acknowledged_disease_alerts',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Disease Alert',
                'verbose_name_plural': 'Disease Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='diseasealert',
            index=models.Index(fields=['company', 'is_active', 'priority'], name='idx_disalert_co_active_pri'),
        ),
        migrations.AddIndex(
            model_name='diseasealert',
            index=models.Index(fields=['alert_type', 'created_at'], name='idx_disalert_type_created'),
        ),

        # =================================================================
        # SCOUTING REPORT MODEL
        # User-submitted disease/pest observations
        # =================================================================
        migrations.CreateModel(
            name='ScoutingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Location
                ('latitude', models.DecimalField(
                    max_digits=10,
                    decimal_places=7,
                    help_text="Report latitude"
                )),
                ('longitude', models.DecimalField(
                    max_digits=10,
                    decimal_places=7,
                    help_text="Report longitude"
                )),
                # Report type
                ('report_type', models.CharField(
                    max_length=50,
                    choices=[
                        ('disease_symptom', 'Disease Symptom'),
                        ('pest_sighting', 'Pest Sighting'),
                        ('tree_decline', 'Tree Decline'),
                        ('tree_death', 'Tree Death'),
                        ('acp_sighting', 'Asian Citrus Psyllid'),
                        ('other', 'Other'),
                    ],
                    help_text="Type of observation"
                )),
                # Symptom checklist
                ('symptoms', models.JSONField(
                    default=dict,
                    help_text="Symptom checklist (e.g., {yellowing_asymmetric: true, ...})"
                )),
                ('severity', models.CharField(
                    max_length=20,
                    choices=[
                        ('low', 'Low - Minor/Isolated'),
                        ('medium', 'Medium - Several Trees'),
                        ('high', 'High - Significant Area'),
                    ],
                    help_text="Severity of observation"
                )),
                ('affected_tree_count', models.IntegerField(
                    null=True,
                    blank=True,
                    help_text="Estimated number of affected trees"
                )),
                ('notes', models.TextField(
                    blank=True,
                    help_text="Additional notes"
                )),
                # AI Analysis
                ('ai_analysis_status', models.CharField(
                    max_length=20,
                    choices=[
                        ('pending', 'Pending'),
                        ('processing', 'Processing'),
                        ('completed', 'Completed'),
                        ('skipped', 'Skipped'),
                    ],
                    default='pending',
                    help_text="Status of AI photo analysis"
                )),
                ('ai_diagnosis', models.JSONField(
                    default=dict,
                    help_text="AI diagnosis results (e.g., {disease: confidence, ...})"
                )),
                # Verification
                ('status', models.CharField(
                    max_length=20,
                    choices=[
                        ('submitted', 'Submitted'),
                        ('under_review', 'Under Review'),
                        ('verified', 'Verified'),
                        ('false_alarm', 'False Alarm'),
                        ('inconclusive', 'Inconclusive'),
                    ],
                    default='submitted',
                    help_text="Verification status"
                )),
                ('verification_notes', models.TextField(
                    blank=True,
                    help_text="Notes from verification"
                )),
                # Sharing
                ('share_anonymously', models.BooleanField(
                    default=True,
                    help_text="Share location anonymously on regional map"
                )),
                ('is_public', models.BooleanField(
                    default=False,
                    help_text="Visible to other platform users"
                )),
                # Timestamps
                ('observed_date', models.DateField(
                    help_text="Date observation was made"
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                # Relationships
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='scouting_reports',
                    to='api.company'
                )),
                ('reported_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='scouting_reports',
                    to=settings.AUTH_USER_MODEL
                )),
                ('farm', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='scouting_reports',
                    to='api.farm'
                )),
                ('field', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='scouting_reports',
                    to='api.field'
                )),
                ('verified_by', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='verified_scouting_reports',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Scouting Report',
                'verbose_name_plural': 'Scouting Reports',
                'ordering': ['-created_at'],
            },
        ),

        # =================================================================
        # SCOUTING PHOTO MODEL
        # Photos attached to scouting reports
        # =================================================================
        migrations.CreateModel(
            name='ScoutingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(
                    upload_to='scouting/%Y/%m/',
                    help_text="Scouting photo"
                )),
                ('caption', models.CharField(
                    max_length=200,
                    blank=True,
                    help_text="Photo caption"
                )),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='photos',
                    to='api.scoutingreport'
                )),
            ],
            options={
                'verbose_name': 'Scouting Photo',
                'verbose_name_plural': 'Scouting Photos',
            },
        ),

        # =================================================================
        # TREE HEALTH RECORD MODEL
        # Tracks health metrics for individual trees over time
        # =================================================================
        migrations.CreateModel(
            name='TreeHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Tree identification
                ('tree_id', models.CharField(
                    max_length=50,
                    help_text="Stable tree identifier across detection runs"
                )),
                ('latitude', models.DecimalField(
                    max_digits=10,
                    decimal_places=7,
                    help_text="Tree latitude"
                )),
                ('longitude', models.DecimalField(
                    max_digits=10,
                    decimal_places=7,
                    help_text="Tree longitude"
                )),
                # Current state
                ('current_ndvi', models.DecimalField(
                    max_digits=4,
                    decimal_places=3,
                    null=True,
                    help_text="Most recent NDVI value"
                )),
                ('current_canopy_diameter_m', models.DecimalField(
                    max_digits=4,
                    decimal_places=2,
                    null=True,
                    help_text="Current canopy diameter in meters"
                )),
                ('last_updated', models.DateTimeField(
                    auto_now=True,
                    help_text="When record was last updated"
                )),
                # Trend data
                ('ndvi_history', models.JSONField(
                    default=list,
                    help_text="Historical NDVI values [{date, value}, ...]"
                )),
                ('canopy_history', models.JSONField(
                    default=list,
                    help_text="Historical canopy values"
                )),
                ('ndvi_trend', models.CharField(
                    max_length=20,
                    choices=[
                        ('improving', 'Improving'),
                        ('stable', 'Stable'),
                        ('declining', 'Declining'),
                        ('rapid_decline', 'Rapid Decline'),
                    ],
                    default='stable',
                    help_text="NDVI trend over time"
                )),
                # Health status
                ('health_status', models.CharField(
                    max_length=20,
                    choices=[
                        ('healthy', 'Healthy'),
                        ('mild_stress', 'Mild Stress'),
                        ('moderate_stress', 'Moderate Stress'),
                        ('severe_stress', 'Severe Stress'),
                        ('dead', 'Dead/Removed'),
                    ],
                    default='healthy',
                    help_text="Current health status"
                )),
                # Flags
                ('flagged_for_inspection', models.BooleanField(
                    default=False,
                    help_text="Tree flagged for ground inspection"
                )),
                ('flag_reason', models.TextField(
                    blank=True,
                    help_text="Reason for flagging"
                )),
                ('inspected', models.BooleanField(
                    default=False,
                    help_text="Tree has been ground-inspected"
                )),
                ('inspection_date', models.DateField(
                    null=True,
                    blank=True,
                    help_text="Date of last inspection"
                )),
                ('inspection_notes', models.TextField(
                    blank=True,
                    help_text="Inspection findings"
                )),
                # Relationships
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tree_health_records',
                    to='api.company'
                )),
                ('field', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tree_health_records',
                    to='api.field'
                )),
                ('last_detection_run', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+',
                    to='api.treedetectionrun'
                )),
            ],
            options={
                'verbose_name': 'Tree Health Record',
                'verbose_name_plural': 'Tree Health Records',
            },
        ),
        migrations.AddConstraint(
            model_name='treehealthrecord',
            constraint=models.UniqueConstraint(
                fields=['field', 'tree_id'],
                name='unique_tree_health_field_treeid',
            ),
        ),
        migrations.AddIndex(
            model_name='treehealthrecord',
            index=models.Index(fields=['field', 'health_status'], name='idx_treehealth_field_status'),
        ),
        migrations.AddIndex(
            model_name='treehealthrecord',
            index=models.Index(fields=['flagged_for_inspection'], name='idx_treehealth_flagged'),
        ),

        # =================================================================
        # FIELD MODEL EXTENSIONS
        # Add disease monitoring fields to existing Field model
        # =================================================================
        migrations.AddField(
            model_name='field',
            name='disease_monitoring_enabled',
            field=models.BooleanField(
                default=True,
                help_text="Enable disease monitoring for this field"
            ),
        ),
        migrations.AddField(
            model_name='field',
            name='last_health_analysis_date',
            field=models.DateField(
                null=True,
                blank=True,
                help_text="Date of last disease health analysis"
            ),
        ),
        migrations.AddField(
            model_name='field',
            name='current_health_score',
            field=models.IntegerField(
                null=True,
                blank=True,
                help_text="Current health score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name='field',
            name='current_risk_level',
            field=models.CharField(
                max_length=20,
                blank=True,
                help_text="Current disease risk level"
            ),
        ),
        migrations.AddField(
            model_name='field',
            name='baseline_ndvi',
            field=models.DecimalField(
                max_digits=4,
                decimal_places=3,
                null=True,
                blank=True,
                help_text="Baseline NDVI from first analysis"
            ),
        ),
        migrations.AddField(
            model_name='field',
            name='baseline_canopy_coverage',
            field=models.DecimalField(
                max_digits=5,
                decimal_places=2,
                null=True,
                blank=True,
                help_text="Baseline canopy coverage from first analysis"
            ),
        ),
        migrations.AddField(
            model_name='field',
            name='baseline_established_date',
            field=models.DateField(
                null=True,
                blank=True,
                help_text="Date baseline was established"
            ),
        ),
        migrations.AddField(
            model_name='field',
            name='last_health_analysis',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='latest_for_field',
                to='api.diseaseanalysisrun',
                help_text="Most recent disease analysis run"
            ),
        ),
    ]
