# Generated by Django 4.2 on 2026-01-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_disease_prevention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='baseline_canopy_coverage',
        ),
        migrations.RemoveField(
            model_name='field',
            name='baseline_established_date',
        ),
        migrations.RemoveField(
            model_name='field',
            name='baseline_ndvi',
        ),
        migrations.RemoveField(
            model_name='field',
            name='current_health_score',
        ),
        migrations.RemoveField(
            model_name='field',
            name='current_risk_level',
        ),
        migrations.RemoveField(
            model_name='field',
            name='disease_monitoring_enabled',
        ),
        migrations.RemoveField(
            model_name='field',
            name='last_health_analysis',
        ),
        migrations.RemoveField(
            model_name='field',
            name='last_health_analysis_date',
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='action_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='alert_type',
            field=models.CharField(choices=[('proximity_hlb', 'HLB Detected Nearby'), ('proximity_acp', 'ACP Activity Nearby'), ('proximity_other', 'Other Disease Nearby'), ('ndvi_anomaly', 'NDVI Anomaly Detected'), ('tree_decline', 'Tree Decline Detected'), ('canopy_loss', 'Canopy Loss Detected'), ('regional_trend', 'Regional Health Trend'), ('scouting_verified', 'Verified Scouting Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='distance_miles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='recommended_actions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diseasealertrule',
            name='alert_priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20),
        ),
        migrations.AlterField(
            model_name='diseasealertrule',
            name='conditions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='diseasealertrule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diseasealertrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diseasealertrule',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diseasealertrule',
            name='rule_type',
            field=models.CharField(choices=[('proximity', 'Proximity Alert'), ('ndvi_threshold', 'NDVI Threshold'), ('ndvi_change', 'NDVI Change Rate'), ('canopy_loss', 'Canopy Loss'), ('tree_count_change', 'Tree Count Change'), ('regional_trend', 'Regional Trend')], max_length=50),
        ),
        migrations.AlterField(
            model_name='diseasealertrule',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diseasealertrule',
            name='send_immediately',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diseasealertrule',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='analysis_type',
            field=models.CharField(choices=[('ndvi_trend', 'NDVI Trend Analysis'), ('anomaly_detection', 'Anomaly Detection'), ('full', 'Full Health Analysis')], default='full', max_length=50),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='anomaly_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='anomaly_zones',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='avg_ndvi',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='canopy_change_30d',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='canopy_coverage_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='health_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='ndvi_change_30d',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='ndvi_change_90d',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='risk_factors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='total_trees_analyzed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='trees_declining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='trees_healthy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='trees_mild_stress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='trees_moderate_stress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diseaseanalysisrun',
            name='trees_severe_stress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='county',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='detection_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='disease_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='disease_type',
            field=models.CharField(choices=[('hlb', 'Huanglongbing (Citrus Greening)'), ('acp', 'Asian Citrus Psyllid'), ('ctvd', 'Citrus Tristeza Virus'), ('cyvcv', 'Citrus Yellow Vein Clearing Virus'), ('canker', 'Citrus Canker'), ('phytophthora', 'Phytophthora Root Rot'), ('laurel_wilt', 'Laurel Wilt'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='eradication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='location_type',
            field=models.CharField(choices=[('residential', 'Residential/Backyard'), ('commercial', 'Commercial Grove'), ('nursery', 'Nursery'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='reported_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='source',
            field=models.CharField(choices=[('cdfa', 'California Dept of Food & Agriculture'), ('usda', 'USDA APHIS'), ('county_ag', 'County Agricultural Commissioner'), ('uc_anr', 'UC Agriculture & Natural Resources'), ('manual', 'Manual Entry')], max_length=50),
        ),
        migrations.AlterField(
            model_name='externaldetection',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scoutingphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scoutingphoto',
            name='image',
            field=models.ImageField(upload_to='scouting/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='affected_tree_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='ai_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='ai_diagnosis',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='observed_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='report_type',
            field=models.CharField(choices=[('disease_symptom', 'Disease Symptom'), ('pest_sighting', 'Pest Sighting'), ('tree_decline', 'Tree Decline'), ('tree_death', 'Tree Death'), ('acp_sighting', 'Asian Citrus Psyllid'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='severity',
            field=models.CharField(choices=[('low', 'Low - Minor/Isolated'), ('medium', 'Medium - Several Trees'), ('high', 'High - Significant Area')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='share_anonymously',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('false_alarm', 'False Alarm'), ('inconclusive', 'Inconclusive')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='symptoms',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='scoutingreport',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='canopy_history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='current_canopy_diameter_m',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='current_ndvi',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='flagged_for_inspection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('mild_stress', 'Mild Stress'), ('moderate_stress', 'Moderate Stress'), ('severe_stress', 'Severe Stress'), ('dead', 'Dead/Removed')], default='healthy', max_length=20),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='inspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='inspection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='ndvi_history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='ndvi_trend',
            field=models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining'), ('rapid_decline', 'Rapid Decline')], default='stable', max_length=20),
        ),
        migrations.AlterField(
            model_name='treehealthrecord',
            name='tree_id',
            field=models.CharField(max_length=50),
        ),
    ]
