# Generated by Django 4.2 on 2026-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_field_baseline_canopy_coverage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('hlb', 'HLB Quarantine'), ('acp', 'ACP Quarantine'), ('eradication', 'Eradication Area'), ('buffer', 'Buffer Zone'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('boundary', models.JSONField(help_text='GeoJSON Polygon geometry for the quarantine boundary')),
                ('source', models.CharField(default='cdfa', max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('established_date', models.DateField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('expires_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='California', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quarantine Zone',
                'verbose_name_plural': 'Quarantine Zones',
                'ordering': ['-established_date'],
            },
        ),
        migrations.AddIndex(
            model_name='quarantinezone',
            index=models.Index(fields=['zone_type', 'is_active'], name='idx_qzone_type_active'),
        ),
        migrations.AddIndex(
            model_name='quarantinezone',
            index=models.Index(fields=['county'], name='idx_qzone_county'),
        ),
        migrations.AddConstraint(
            model_name='quarantinezone',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__gt', '')), fields=('source', 'source_id'), name='unique_quarantine_zone_source'),
        ),
    ]
