# Generated by Django 4.2 on 2026-01-21
# Packinghouse Pool Tracking System
# For California citrus cooperative packinghouses with pool marketing arrangements.

from django.db import migrations, models
import django.db.models.deletion


def build_rls_policies_sql():
    """
    Build SQL to create RLS policies for packinghouse tables.

    RLS Chain:
    - Packinghouse: direct company_id
    - Pool: via packinghouse.company_id
    - PackinghouseDelivery: via pool.packinghouse.company_id
    - PackoutReport: via pool.packinghouse.company_id
    - PackoutGradeLine: via packout_report.pool.packinghouse.company_id
    - PoolSettlement: via pool.packinghouse.company_id
    - SettlementGradeLine: via settlement.pool.packinghouse.company_id
    - SettlementDeduction: via settlement.pool.packinghouse.company_id
    - GrowerLedgerEntry: via packinghouse.company_id
    """

    sql_statements = []

    # Packinghouse - direct company_id
    sql_statements.append("""
        ALTER TABLE api_packinghouse ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_packinghouse;

        CREATE POLICY tenant_isolation ON api_packinghouse
            FOR ALL
            USING (
                company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
            );

        ALTER TABLE api_packinghouse FORCE ROW LEVEL SECURITY;
    """)

    # Pool - via packinghouse.company_id
    sql_statements.append("""
        ALTER TABLE api_pool ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_pool;

        CREATE POLICY tenant_isolation ON api_pool
            FOR ALL
            USING (
                packinghouse_id IN (
                    SELECT id FROM api_packinghouse
                    WHERE company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_pool FORCE ROW LEVEL SECURITY;
    """)

    # PackinghouseDelivery - via pool.packinghouse.company_id
    sql_statements.append("""
        ALTER TABLE api_packinghousedelivery ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_packinghousedelivery;

        CREATE POLICY tenant_isolation ON api_packinghousedelivery
            FOR ALL
            USING (
                pool_id IN (
                    SELECT p.id FROM api_pool p
                    JOIN api_packinghouse ph ON p.packinghouse_id = ph.id
                    WHERE ph.company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_packinghousedelivery FORCE ROW LEVEL SECURITY;
    """)

    # PackoutReport - via pool.packinghouse.company_id
    sql_statements.append("""
        ALTER TABLE api_packoutreport ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_packoutreport;

        CREATE POLICY tenant_isolation ON api_packoutreport
            FOR ALL
            USING (
                pool_id IN (
                    SELECT p.id FROM api_pool p
                    JOIN api_packinghouse ph ON p.packinghouse_id = ph.id
                    WHERE ph.company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_packoutreport FORCE ROW LEVEL SECURITY;
    """)

    # PackoutGradeLine - via packout_report.pool.packinghouse.company_id
    sql_statements.append("""
        ALTER TABLE api_packoutgradeline ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_packoutgradeline;

        CREATE POLICY tenant_isolation ON api_packoutgradeline
            FOR ALL
            USING (
                packout_report_id IN (
                    SELECT pr.id FROM api_packoutreport pr
                    JOIN api_pool p ON pr.pool_id = p.id
                    JOIN api_packinghouse ph ON p.packinghouse_id = ph.id
                    WHERE ph.company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_packoutgradeline FORCE ROW LEVEL SECURITY;
    """)

    # PoolSettlement - via pool.packinghouse.company_id
    sql_statements.append("""
        ALTER TABLE api_poolsettlement ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_poolsettlement;

        CREATE POLICY tenant_isolation ON api_poolsettlement
            FOR ALL
            USING (
                pool_id IN (
                    SELECT p.id FROM api_pool p
                    JOIN api_packinghouse ph ON p.packinghouse_id = ph.id
                    WHERE ph.company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_poolsettlement FORCE ROW LEVEL SECURITY;
    """)

    # SettlementGradeLine - via settlement.pool.packinghouse.company_id
    sql_statements.append("""
        ALTER TABLE api_settlementgradeline ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_settlementgradeline;

        CREATE POLICY tenant_isolation ON api_settlementgradeline
            FOR ALL
            USING (
                settlement_id IN (
                    SELECT s.id FROM api_poolsettlement s
                    JOIN api_pool p ON s.pool_id = p.id
                    JOIN api_packinghouse ph ON p.packinghouse_id = ph.id
                    WHERE ph.company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_settlementgradeline FORCE ROW LEVEL SECURITY;
    """)

    # SettlementDeduction - via settlement.pool.packinghouse.company_id
    sql_statements.append("""
        ALTER TABLE api_settlementdeduction ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_settlementdeduction;

        CREATE POLICY tenant_isolation ON api_settlementdeduction
            FOR ALL
            USING (
                settlement_id IN (
                    SELECT s.id FROM api_poolsettlement s
                    JOIN api_pool p ON s.pool_id = p.id
                    JOIN api_packinghouse ph ON p.packinghouse_id = ph.id
                    WHERE ph.company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_settlementdeduction FORCE ROW LEVEL SECURITY;
    """)

    # GrowerLedgerEntry - via packinghouse.company_id
    sql_statements.append("""
        ALTER TABLE api_growerledgerentry ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_growerledgerentry;

        CREATE POLICY tenant_isolation ON api_growerledgerentry
            FOR ALL
            USING (
                packinghouse_id IN (
                    SELECT id FROM api_packinghouse
                    WHERE company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_growerledgerentry FORCE ROW LEVEL SECURITY;
    """)

    return "\n".join(sql_statements)


def build_disable_rls_sql():
    """Generate SQL to remove all RLS policies (for rollback)."""

    tables = [
        'api_packinghouse',
        'api_pool',
        'api_packinghousedelivery',
        'api_packoutreport',
        'api_packoutgradeline',
        'api_poolsettlement',
        'api_settlementgradeline',
        'api_settlementdeduction',
        'api_growerledgerentry',
    ]

    sql_statements = []
    for table in tables:
        sql_statements.append(f"""
            DROP POLICY IF EXISTS tenant_isolation ON {table};
            ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;
        """)

    return "\n".join(sql_statements)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_fix_auditlog_rls_coalesce'),
    ]

    operations = [
        # =================================================================
        # PACKINGHOUSE MODEL
        # =================================================================
        migrations.CreateModel(
            name='Packinghouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full packinghouse name (e.g., "Saticoy Lemon Association")', max_length=200)),
                ('short_code', models.CharField(blank=True, help_text='Abbreviation (e.g., "SLA", "VPOA")', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='CA', max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('grower_id', models.CharField(blank=True, help_text='Your grower ID with this packinghouse (e.g., "THACR641")', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company that owns this packinghouse record', on_delete=django.db.models.deletion.CASCADE, related_name='packinghouses', to='api.company')),
            ],
            options={
                'verbose_name': 'Packinghouse',
                'verbose_name_plural': 'Packinghouses',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='packinghouse',
            index=models.Index(fields=['company', 'is_active'], name='idx_pkghs_co_active'),
        ),

        # =================================================================
        # POOL MODEL
        # =================================================================
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(help_text='Packinghouse pool identifier (e.g., "2520000 D2 POOL")', max_length=50)),
                ('name', models.CharField(help_text='Friendly name for the pool', max_length=200)),
                ('commodity', models.CharField(help_text='e.g., "LEMONS", "NAVELS", "TANGERINES"', max_length=50)),
                ('variety', models.CharField(blank=True, help_text='e.g., "CARA NAVELS", "PIXIES"', max_length=50)),
                ('season', models.CharField(help_text='e.g., "2024-2025"', max_length=20)),
                ('pool_type', models.CharField(choices=[('fresh', 'Fresh Market'), ('juice', 'Juice/Processing'), ('mixed', 'Mixed')], default='fresh', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('settled', 'Settled')], default='active', max_length=20)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packinghouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='api.packinghouse')),
            ],
            options={
                'verbose_name': 'Pool',
                'verbose_name_plural': 'Pools',
                'ordering': ['-season', 'commodity', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(fields=['packinghouse', 'pool_id'], name='unique_pool_packinghouse_poolid'),
        ),
        migrations.AddIndex(
            model_name='pool',
            index=models.Index(fields=['packinghouse', 'status'], name='idx_pool_pkghs_status'),
        ),
        migrations.AddIndex(
            model_name='pool',
            index=models.Index(fields=['season', 'commodity'], name='idx_pool_season_comm'),
        ),

        # =================================================================
        # PACKINGHOUSE DELIVERY MODEL
        # =================================================================
        migrations.CreateModel(
            name='PackinghouseDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='Receiving ticket number (e.g., "182622")', max_length=50)),
                ('delivery_date', models.DateField()),
                ('bins', models.DecimalField(decimal_places=2, help_text='Number of bins delivered', max_digits=10)),
                ('field_boxes', models.DecimalField(blank=True, decimal_places=2, help_text='Field box count if different from bins', max_digits=10, null=True)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, help_text='Total weight in pounds', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.pool')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packinghouse_deliveries', to='api.field')),
                ('harvest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packinghouse_deliveries', to='api.harvest')),
            ],
            options={
                'verbose_name': 'Packinghouse Delivery',
                'verbose_name_plural': 'Packinghouse Deliveries',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='packinghousedelivery',
            constraint=models.UniqueConstraint(fields=['pool', 'ticket_number'], name='unique_delivery_pool_ticket'),
        ),
        migrations.AddIndex(
            model_name='packinghousedelivery',
            index=models.Index(fields=['pool', 'delivery_date'], name='idx_pkgdel_pool_date'),
        ),
        migrations.AddIndex(
            model_name='packinghousedelivery',
            index=models.Index(fields=['field', 'delivery_date'], name='idx_pkgdel_field_date'),
        ),

        # =================================================================
        # PACKOUT REPORT MODEL
        # =================================================================
        migrations.CreateModel(
            name='PackoutReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(help_text='Date of the packout report')),
                ('period_start', models.DateField(help_text='Start of fruit packing period')),
                ('period_end', models.DateField(help_text='End of fruit packing period')),
                ('run_numbers', models.CharField(blank=True, help_text='Run numbers covered (e.g., "2535499" or "2535579, 2535591")', max_length=200)),
                ('bins_this_period', models.DecimalField(decimal_places=2, help_text='Bins packed this period', max_digits=10)),
                ('bins_cumulative', models.DecimalField(decimal_places=2, help_text='Cumulative bins for pool to date', max_digits=10)),
                ('total_packed_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of fruit packed (vs. juice/cull)', max_digits=5, null=True)),
                ('house_avg_packed_percent', models.DecimalField(blank=True, decimal_places=2, help_text='House average pack percentage for comparison', max_digits=5, null=True)),
                ('juice_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cull_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quality_notes', models.TextField(blank=True, help_text='Quality observations (e.g., "Wind Scar", "Scale")')),
                ('grade_data_json', models.JSONField(default=dict, help_text='Complete grade breakdown data from report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packout_reports', to='api.pool')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packout_reports', to='api.field')),
            ],
            options={
                'verbose_name': 'Packout Report',
                'verbose_name_plural': 'Packout Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.AddIndex(
            model_name='packoutreport',
            index=models.Index(fields=['pool', '-report_date'], name='idx_packout_pool_date'),
        ),
        migrations.AddIndex(
            model_name='packoutreport',
            index=models.Index(fields=['field', '-report_date'], name='idx_packout_field_date'),
        ),

        # =================================================================
        # PACKOUT GRADE LINE MODEL
        # =================================================================
        migrations.CreateModel(
            name='PackoutGradeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(help_text='Grade designation (e.g., "SUNKIST", "CHOICE", "STANDARD", "JUICE")', max_length=20)),
                ('size', models.CharField(blank=True, help_text='Size code (e.g., "075", "088", "113")', max_length=10)),
                ('unit_of_measure', models.CharField(choices=[('CARTON', 'Cartons'), ('BIN', 'Bins'), ('LBS', 'Pounds')], default='CARTON', max_length=20)),
                ('quantity_this_period', models.DecimalField(decimal_places=2, help_text='Quantity packed this period', max_digits=10)),
                ('percent_this_period', models.DecimalField(decimal_places=2, help_text='Percentage of pack this period', max_digits=5)),
                ('quantity_cumulative', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percent_cumulative', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('house_avg_percent', models.DecimalField(blank=True, decimal_places=2, help_text='House average percentage for comparison', max_digits=5, null=True)),
                ('packout_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_lines', to='api.packoutreport')),
            ],
            options={
                'verbose_name': 'Packout Grade Line',
                'verbose_name_plural': 'Packout Grade Lines',
                'ordering': ['grade', 'size'],
            },
        ),

        # =================================================================
        # POOL SETTLEMENT MODEL
        # =================================================================
        migrations.CreateModel(
            name='PoolSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(help_text='Date of settlement statement')),
                ('total_bins', models.DecimalField(decimal_places=2, help_text='Total bins in settlement', max_digits=10)),
                ('total_cartons', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_credits', models.DecimalField(decimal_places=2, help_text='Total gross credits (sales)', max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, help_text='Total deductions (packing, assessments, etc.)', max_digits=12)),
                ('net_return', models.DecimalField(decimal_places=2, help_text='Net return (credits - deductions)', max_digits=12)),
                ('prior_advances', models.DecimalField(decimal_places=2, default=0, help_text='Prior advances paid to grower', max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Final amount due (net return - prior advances)', max_digits=12)),
                ('net_per_bin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_per_carton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_per_lb', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('net_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('house_avg_per_bin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('house_avg_per_carton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fresh_fruit_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage packed as fresh fruit', max_digits=5, null=True)),
                ('products_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage going to products/juice', max_digits=5, null=True)),
                ('settlement_data_json', models.JSONField(default=dict, help_text='Complete settlement data for reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='api.pool')),
                ('field', models.ForeignKey(blank=True, help_text='Specific field, or null for grower summary across all blocks', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_settlements', to='api.field')),
            ],
            options={
                'verbose_name': 'Pool Settlement',
                'verbose_name_plural': 'Pool Settlements',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.AddIndex(
            model_name='poolsettlement',
            index=models.Index(fields=['pool', '-statement_date'], name='idx_settle_pool_date'),
        ),
        migrations.AddIndex(
            model_name='poolsettlement',
            index=models.Index(fields=['field', '-statement_date'], name='idx_settle_field_date'),
        ),

        # =================================================================
        # SETTLEMENT GRADE LINE MODEL
        # =================================================================
        migrations.CreateModel(
            name='SettlementGradeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(help_text='Grade designation (e.g., "SK DOMESTIC", "CH DOMESTIC", "JUICE")', max_length=20)),
                ('size', models.CharField(blank=True, help_text='Size code (e.g., "048", "056", "072")', max_length=10)),
                ('unit_of_measure', models.CharField(choices=[('CARTON', 'Cartons'), ('BIN', 'Bins'), ('LBS', 'Pounds')], default='CARTON', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in this grade/size', max_digits=10)),
                ('percent_of_total', models.DecimalField(decimal_places=2, help_text='Percentage of total pack', max_digits=5)),
                ('fob_rate', models.DecimalField(decimal_places=6, help_text='FOB price per unit (high precision: 21.75359773)', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total credit for this line', max_digits=12)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_lines', to='api.poolsettlement')),
            ],
            options={
                'verbose_name': 'Settlement Grade Line',
                'verbose_name_plural': 'Settlement Grade Lines',
                'ordering': ['grade', 'size'],
            },
        ),

        # =================================================================
        # SETTLEMENT DEDUCTION MODEL
        # =================================================================
        migrations.CreateModel(
            name='SettlementDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('packing', 'Packing Charges'), ('assessment', 'Assessments'), ('pick_haul', 'Pick & Haul'), ('capital', 'Capital Funds'), ('marketing', 'Marketing'), ('other', 'Other')], help_text='Deduction category', max_length=50)),
                ('description', models.CharField(help_text='Description (e.g., "DOOR CHARGE", "SUNKIST MARKETING")', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity basis', max_digits=12)),
                ('unit_of_measure', models.CharField(help_text='Unit (BIN, CTN, LBS, etc.)', max_length=20)),
                ('rate', models.DecimalField(decimal_places=7, help_text='Rate per unit (high precision)', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total deduction amount', max_digits=12)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='api.poolsettlement')),
            ],
            options={
                'verbose_name': 'Settlement Deduction',
                'verbose_name_plural': 'Settlement Deductions',
                'ordering': ['category', 'description'],
            },
        ),

        # =================================================================
        # GROWER LEDGER ENTRY MODEL
        # =================================================================
        migrations.CreateModel(
            name='GrowerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(help_text='Transaction date')),
                ('posted_date', models.DateField(blank=True, help_text='Date posted to account', null=True)),
                ('entry_type', models.CharField(choices=[('advance', 'Advance'), ('pool_close', 'Pool Close'), ('adjustment', 'Adjustment'), ('refund', 'Refund'), ('payment', 'Payment'), ('capital_equity', 'Capital/Equity')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Reference number (e.g., "APM-SL-09588", "00265")', max_length=50)),
                ('description', models.CharField(help_text='Transaction description', max_length=200)),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Amount owed to grower', max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid or offset', max_digits=12)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, help_text='Running balance after this entry', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packinghouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.packinghouse')),
                ('pool', models.ForeignKey(blank=True, help_text='Associated pool, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.pool')),
            ],
            options={
                'verbose_name': 'Grower Ledger Entry',
                'verbose_name_plural': 'Grower Ledger Entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='growerledgerentry',
            index=models.Index(fields=['packinghouse', '-entry_date'], name='idx_ledger_pkghs_date'),
        ),
        migrations.AddIndex(
            model_name='growerledgerentry',
            index=models.Index(fields=['entry_type'], name='idx_ledger_type'),
        ),

        # =================================================================
        # ROW-LEVEL SECURITY POLICIES
        # =================================================================
        migrations.RunSQL(
            sql=build_rls_policies_sql(),
            reverse_sql=build_disable_rls_sql(),
        ),
    ]
