# Generated by Django 4.2 on 2026-01-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_packinghousestatement_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('export', 'Exported Data'), ('submit', 'Submitted Report'), ('invite', 'Sent Invitation'), ('invite_accept', 'Accepted Invitation')], max_length=20),
        ),
    ]
