# Generated by Django 4.2 on 2026-01-23
# FSMA Food Safety Compliance Module
# Visitor logs, facility cleaning, safety meetings, fertilizer inventory,
# PHI compliance verification, and audit binder generation.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal
from django.core.validators import MinValueValidator


def build_rls_policies_sql():
    """
    Build SQL to create RLS policies for FSMA tables.

    RLS Chain:
    - UserSignature: via user.current_company_id
    - FacilityLocation: direct company_id
    - FacilityCleaningLog: via facility.company_id
    - VisitorLog: direct company_id
    - SafetyMeeting: direct company_id
    - SafetyMeetingAttendee: via meeting.company_id
    - FertilizerInventory: direct company_id
    - FertilizerInventoryTransaction: via inventory.company_id
    - MonthlyInventorySnapshot: direct company_id
    - PHIComplianceCheck: via harvest.field.farm.company_id
    - AuditBinder: direct company_id
    """

    sql_statements = []

    # UserSignature - via user relationship (special case - check user's company memberships)
    # Note: This uses a simpler approach - signatures are user-specific, not company-specific
    sql_statements.append("""
        ALTER TABLE api_usersignature ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_usersignature;

        CREATE POLICY tenant_isolation ON api_usersignature
            FOR ALL
            USING (
                user_id IN (
                    SELECT u.id FROM api_user u
                    WHERE u.current_company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_usersignature FORCE ROW LEVEL SECURITY;
    """)

    # FacilityLocation - direct company_id
    sql_statements.append("""
        ALTER TABLE api_facilitylocation ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_facilitylocation;

        CREATE POLICY tenant_isolation ON api_facilitylocation
            FOR ALL
            USING (
                company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
            );

        ALTER TABLE api_facilitylocation FORCE ROW LEVEL SECURITY;
    """)

    # FacilityCleaningLog - via facility.company_id
    sql_statements.append("""
        ALTER TABLE api_facilitycleaninglog ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_facilitycleaninglog;

        CREATE POLICY tenant_isolation ON api_facilitycleaninglog
            FOR ALL
            USING (
                facility_id IN (
                    SELECT id FROM api_facilitylocation
                    WHERE company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_facilitycleaninglog FORCE ROW LEVEL SECURITY;
    """)

    # VisitorLog - direct company_id
    sql_statements.append("""
        ALTER TABLE api_visitorlog ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_visitorlog;

        CREATE POLICY tenant_isolation ON api_visitorlog
            FOR ALL
            USING (
                company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
            );

        ALTER TABLE api_visitorlog FORCE ROW LEVEL SECURITY;
    """)

    # SafetyMeeting - direct company_id
    sql_statements.append("""
        ALTER TABLE api_safetymeeting ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_safetymeeting;

        CREATE POLICY tenant_isolation ON api_safetymeeting
            FOR ALL
            USING (
                company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
            );

        ALTER TABLE api_safetymeeting FORCE ROW LEVEL SECURITY;
    """)

    # SafetyMeetingAttendee - via meeting.company_id
    sql_statements.append("""
        ALTER TABLE api_safetymeetingattendee ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_safetymeetingattendee;

        CREATE POLICY tenant_isolation ON api_safetymeetingattendee
            FOR ALL
            USING (
                meeting_id IN (
                    SELECT id FROM api_safetymeeting
                    WHERE company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_safetymeetingattendee FORCE ROW LEVEL SECURITY;
    """)

    # FertilizerInventory - direct company_id
    sql_statements.append("""
        ALTER TABLE api_fertilizerinventory ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_fertilizerinventory;

        CREATE POLICY tenant_isolation ON api_fertilizerinventory
            FOR ALL
            USING (
                company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
            );

        ALTER TABLE api_fertilizerinventory FORCE ROW LEVEL SECURITY;
    """)

    # FertilizerInventoryTransaction - via inventory.company_id
    sql_statements.append("""
        ALTER TABLE api_fertilizerinventorytransaction ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_fertilizerinventorytransaction;

        CREATE POLICY tenant_isolation ON api_fertilizerinventorytransaction
            FOR ALL
            USING (
                inventory_id IN (
                    SELECT id FROM api_fertilizerinventory
                    WHERE company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_fertilizerinventorytransaction FORCE ROW LEVEL SECURITY;
    """)

    # MonthlyInventorySnapshot - direct company_id
    sql_statements.append("""
        ALTER TABLE api_monthlyinventorysnapshot ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_monthlyinventorysnapshot;

        CREATE POLICY tenant_isolation ON api_monthlyinventorysnapshot
            FOR ALL
            USING (
                company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
            );

        ALTER TABLE api_monthlyinventorysnapshot FORCE ROW LEVEL SECURITY;
    """)

    # PHIComplianceCheck - via harvest.field.farm.company_id
    sql_statements.append("""
        ALTER TABLE api_phicompliancecheck ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_phicompliancecheck;

        CREATE POLICY tenant_isolation ON api_phicompliancecheck
            FOR ALL
            USING (
                harvest_id IN (
                    SELECT h.id FROM api_harvest h
                    JOIN api_field f ON h.field_id = f.id
                    JOIN api_farm fa ON f.farm_id = fa.id
                    WHERE fa.company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
                )
            );

        ALTER TABLE api_phicompliancecheck FORCE ROW LEVEL SECURITY;
    """)

    # AuditBinder - direct company_id
    sql_statements.append("""
        ALTER TABLE api_auditbinder ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS tenant_isolation ON api_auditbinder;

        CREATE POLICY tenant_isolation ON api_auditbinder
            FOR ALL
            USING (
                company_id = NULLIF(current_setting('app.current_company_id', true), '')::integer
            );

        ALTER TABLE api_auditbinder FORCE ROW LEVEL SECURITY;
    """)

    return "\n".join(sql_statements)


def build_disable_rls_sql():
    """Generate SQL to remove all RLS policies (for rollback)."""
    tables = [
        'api_usersignature',
        'api_facilitylocation',
        'api_facilitycleaninglog',
        'api_visitorlog',
        'api_safetymeeting',
        'api_safetymeetingattendee',
        'api_fertilizerinventory',
        'api_fertilizerinventorytransaction',
        'api_monthlyinventorysnapshot',
        'api_phicompliancecheck',
        'api_auditbinder',
    ]

    statements = []
    for table in tables:
        statements.append(f"""
            DROP POLICY IF EXISTS tenant_isolation ON {table};
            ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;
        """)

    return "\n".join(statements)


def apply_rls_policies(apps, schema_editor):
    """Apply RLS policies using raw SQL."""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(build_rls_policies_sql())


def remove_rls_policies(apps, schema_editor):
    """Remove RLS policies for rollback."""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(build_disable_rls_sql())


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_fix_packinghouse_rls_policies'),
    ]

    operations = [
        # =================================================================
        # UserSignature - stored digital signatures for reuse
        # =================================================================
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_data', models.TextField(help_text='Base64 encoded PNG signature image')),
                ('signature_hash', models.CharField(blank=True, help_text='SHA256 hash for verification', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_signature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Signature',
                'verbose_name_plural': 'User Signatures',
            },
        ),

        # =================================================================
        # FacilityLocation - facilities requiring cleaning tracking
        # =================================================================
        migrations.CreateModel(
            name='FacilityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Facility name (e.g., 'Main Packing Shed', 'North Field Restroom')", max_length=100)),
                ('facility_type', models.CharField(choices=[('packing_shed', 'Packing Shed'), ('cold_storage', 'Cold Storage'), ('processing_area', 'Processing Area'), ('restroom', 'Restroom/Portable Toilet'), ('break_room', 'Break Room'), ('equipment_storage', 'Equipment Storage'), ('chemical_storage', 'Chemical/Pesticide Storage'), ('loading_dock', 'Loading Dock'), ('field_station', 'Field Station'), ('other', 'Other')], default='packing_shed', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Additional description or notes')),
                ('cleaning_frequency', models.CharField(choices=[('daily', 'Daily'), ('twice_daily', 'Twice Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('as_needed', 'As Needed'), ('after_use', 'After Each Use')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive facilities won't appear in cleaning schedules")),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsma_facilities', to='api.company')),
                ('farm', models.ForeignKey(blank=True, help_text='Optional: Link to specific farm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fsma_facilities', to='api.farm')),
            ],
            options={
                'verbose_name': 'Facility Location',
                'verbose_name_plural': 'Facility Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='facilitylocation',
            index=models.Index(fields=['company', 'is_active'], name='idx_facility_company_active'),
        ),
        migrations.AddIndex(
            model_name='facilitylocation',
            index=models.Index(fields=['facility_type'], name='idx_facility_type'),
        ),

        # =================================================================
        # FacilityCleaningLog - cleaning event records
        # =================================================================
        migrations.CreateModel(
            name='FacilityCleaningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_date', models.DateField()),
                ('cleaning_time', models.TimeField()),
                ('cleaned_by_name', models.CharField(blank=True, help_text='Name if cleaned by non-system user', max_length=100)),
                ('surfaces_cleaned', models.BooleanField(default=False)),
                ('floors_cleaned', models.BooleanField(default=False)),
                ('trash_removed', models.BooleanField(default=False)),
                ('sanitizer_applied', models.BooleanField(default=False)),
                ('supplies_restocked', models.BooleanField(default=False)),
                ('equipment_cleaned', models.BooleanField(default=False)),
                ('additional_checklist', models.JSONField(blank=True, default=dict, help_text='Additional checklist items specific to facility type')),
                ('notes', models.TextField(blank=True)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded signature image')),
                ('signature_timestamp', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleaned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_logs_performed', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_logs', to='api.facilitylocation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_logs_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility Cleaning Log',
                'verbose_name_plural': 'Facility Cleaning Logs',
                'ordering': ['-cleaning_date', '-cleaning_time'],
            },
        ),
        migrations.AddIndex(
            model_name='facilitycleaninglog',
            index=models.Index(fields=['facility', '-cleaning_date'], name='idx_cleaning_facility_date'),
        ),
        migrations.AddIndex(
            model_name='facilitycleaninglog',
            index=models.Index(fields=['cleaning_date'], name='idx_cleaning_date'),
        ),

        # =================================================================
        # VisitorLog - farm visitor tracking
        # =================================================================
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=150)),
                ('visitor_company', models.CharField(blank=True, help_text="Visitor's company/organization", max_length=150)),
                ('visitor_type', models.CharField(choices=[('harvester', 'Harvest Crew'), ('buyer', 'Buyer/Inspector'), ('contractor', 'Contractor'), ('vendor', 'Vendor/Supplier'), ('government', 'Government Inspector'), ('auditor', 'Auditor'), ('consultant', 'Consultant/PCA'), ('delivery', 'Delivery Personnel'), ('maintenance', 'Maintenance'), ('visitor', 'General Visitor'), ('other', 'Other')], default='visitor', max_length=30)),
                ('visitor_phone', models.CharField(blank=True, max_length=20)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visit_date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of visit')),
                ('areas_visited', models.TextField(blank=True, help_text='Free text for non-field areas visited')),
                ('vehicle_info', models.CharField(blank=True, help_text='Vehicle description/license plate', max_length=100)),
                ('auto_linked', models.BooleanField(default=False, help_text='Whether harvest was auto-linked by date match')),
                ('health_screening_passed', models.BooleanField(default=True, help_text='Did visitor pass health screening?')),
                ('screening_notes', models.TextField(blank=True)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded visitor signature')),
                ('signature_timestamp', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_logs', to='api.company')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_logs', to='api.farm')),
                ('fields_visited', models.ManyToManyField(blank=True, related_name='visitor_logs', to='api.field')),
                ('linked_harvest', models.ForeignKey(blank=True, help_text='Linked harvest event (for harvest crews)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to='api.harvest')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor Log',
                'verbose_name_plural': 'Visitor Logs',
                'ordering': ['-visit_date', '-time_in'],
            },
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['company', '-visit_date'], name='idx_visitor_company_date'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['farm', '-visit_date'], name='idx_visitor_farm_date'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['visitor_type'], name='idx_visitor_type'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['linked_harvest'], name='idx_visitor_harvest'),
        ),

        # =================================================================
        # SafetyMeeting - company-wide safety meetings
        # =================================================================
        migrations.CreateModel(
            name='SafetyMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('quarterly_fsma', 'Quarterly FSMA Training'), ('annual_food_safety', 'Annual Food Safety Training'), ('wps_initial', 'WPS Initial Training'), ('wps_annual', 'WPS Annual Refresher'), ('heat_illness', 'Heat Illness Prevention'), ('pesticide_safety', 'Pesticide Safety'), ('equipment_operation', 'Equipment Operation'), ('emergency_procedures', 'Emergency Procedures'), ('ppe_usage', 'PPE Usage Training'), ('other', 'Other Safety Meeting')], default='quarterly_fsma', max_length=30)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('topics_covered', models.JSONField(default=list, help_text='List of topics covered in this meeting')),
                ('description', models.TextField(blank=True, help_text='Meeting description or agenda')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Meeting duration in minutes', null=True)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, help_text='Quarter number (1-4)', null=True)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year for quarterly tracking', null=True)),
                ('trainer_name', models.CharField(blank=True, max_length=150)),
                ('trainer_credentials', models.CharField(blank=True, max_length=200)),
                ('materials_provided', models.TextField(blank=True, help_text='Description of training materials provided')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_meetings', to='api.company')),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_meetings_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Meeting',
                'verbose_name_plural': 'Safety Meetings',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.AddIndex(
            model_name='safetymeeting',
            index=models.Index(fields=['company', '-meeting_date'], name='idx_safety_meeting_company'),
        ),
        migrations.AddIndex(
            model_name='safetymeeting',
            index=models.Index(fields=['meeting_type'], name='idx_safety_meeting_type'),
        ),
        migrations.AddIndex(
            model_name='safetymeeting',
            index=models.Index(fields=['company', 'year', 'quarter'], name='idx_safety_meeting_quarter'),
        ),
        migrations.AlterUniqueTogether(
            name='safetymeeting',
            unique_together={('company', 'meeting_type', 'year', 'quarter')},
        ),

        # =================================================================
        # SafetyMeetingAttendee - meeting attendance records
        # =================================================================
        migrations.CreateModel(
            name='SafetyMeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(help_text='Attendee name (auto-filled from user if linked)', max_length=150)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded signature')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='api.safetymeeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_meeting_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Meeting Attendee',
                'verbose_name_plural': 'Safety Meeting Attendees',
                'ordering': ['attendee_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='safetymeetingattendee',
            unique_together={('meeting', 'attendee_name')},
        ),

        # =================================================================
        # FertilizerInventory - current inventory levels
        # =================================================================
        migrations.CreateModel(
            name='FertilizerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, help_text='Current quantity on hand', max_digits=12, validators=[MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(default='lbs', help_text='Unit of measurement (lbs, gallons, tons, etc.)', max_length=20)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=2, help_text='Alert when inventory falls below this level', max_digits=12, null=True)),
                ('storage_location', models.CharField(blank=True, help_text='Where this product is stored', max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_inventory', to='api.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='api.fertilizerproduct')),
            ],
            options={
                'verbose_name': 'Fertilizer Inventory',
                'verbose_name_plural': 'Fertilizer Inventories',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fertilizerinventory',
            unique_together={('company', 'product')},
        ),
        migrations.AddIndex(
            model_name='fertilizerinventory',
            index=models.Index(fields=['company', 'product'], name='idx_fert_inv_company_product'),
        ),

        # =================================================================
        # FertilizerInventoryTransaction - inventory movements
        # =================================================================
        migrations.CreateModel(
            name='FertilizerInventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase/Received'), ('application', 'Application Used'), ('adjustment', 'Manual Adjustment'), ('return', 'Returned to Supplier'), ('disposed', 'Disposed/Expired'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive for additions, negative for deductions', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Inventory balance after this transaction', max_digits=12)),
                ('transaction_date', models.DateTimeField()),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.fertilizerinventory')),
                ('nutrient_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='api.nutrientapplication')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='fertilizerinventorytransaction',
            index=models.Index(fields=['inventory', '-transaction_date'], name='idx_inv_trans_inv_date'),
        ),
        migrations.AddIndex(
            model_name='fertilizerinventorytransaction',
            index=models.Index(fields=['transaction_type'], name='idx_inv_trans_type'),
        ),

        # =================================================================
        # MonthlyInventorySnapshot - monthly reports
        # =================================================================
        migrations.CreateModel(
            name='MonthlyInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Month (1-12)')),
                ('year', models.PositiveIntegerField()),
                ('inventory_data', models.JSONField(default=list, help_text='Snapshot of all inventory levels')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_stock_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='api.company')),
            ],
            options={
                'verbose_name': 'Monthly Inventory Snapshot',
                'verbose_name_plural': 'Monthly Inventory Snapshots',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='monthlyinventorysnapshot',
            unique_together={('company', 'year', 'month')},
        ),

        # =================================================================
        # PHIComplianceCheck - PHI validation per harvest
        # =================================================================
        migrations.CreateModel(
            name='PHIComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Check'), ('compliant', 'Compliant'), ('warning', 'Warning - Near PHI'), ('non_compliant', 'Non-Compliant'), ('override', 'Override Applied')], default='pending', max_length=20)),
                ('applications_checked', models.JSONField(default=list, help_text='List of pesticide applications checked with PHI details')),
                ('warnings', models.JSONField(default=list, help_text='List of warning messages')),
                ('earliest_safe_harvest', models.DateField(blank=True, help_text='Earliest date harvest would be compliant', null=True)),
                ('override_reason', models.TextField(blank=True, help_text='Reason if status was overridden')),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phi_compliance_check', to='api.harvest')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phi_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PHI Compliance Check',
                'verbose_name_plural': 'PHI Compliance Checks',
            },
        ),
        migrations.AddIndex(
            model_name='phicompliancecheck',
            index=models.Index(fields=['status'], name='idx_phi_status'),
        ),

        # =================================================================
        # AuditBinder - generated audit binder PDFs
        # =================================================================
        migrations.CreateModel(
            name='AuditBinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('include_visitor_logs', models.BooleanField(default=True)),
                ('include_cleaning_logs', models.BooleanField(default=True)),
                ('include_safety_meetings', models.BooleanField(default=True)),
                ('include_fertilizer_inventory', models.BooleanField(default=True)),
                ('include_phi_reports', models.BooleanField(default=True)),
                ('include_harvest_records', models.BooleanField(default=True)),
                ('farm_ids', models.JSONField(blank=True, default=list, help_text='Filter to specific farms (empty = all farms)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='audit_binders/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Generation'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generation_started', models.DateTimeField(blank=True, null=True)),
                ('generation_completed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_binders', to='api.company')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_binders_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Binder',
                'verbose_name_plural': 'Audit Binders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditbinder',
            index=models.Index(fields=['company', '-created_at'], name='idx_audit_binder_company'),
        ),
        migrations.AddIndex(
            model_name='auditbinder',
            index=models.Index(fields=['status'], name='idx_audit_binder_status'),
        ),

        # =================================================================
        # Apply RLS Policies
        # =================================================================
        migrations.RunPython(apply_rls_policies, remove_rls_policies),
    ]
