# Generated by Django 4.2 on 2026-01-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_batch_upload_and_grower_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinghousestatement',
            name='packinghouse',
            field=models.ForeignKey(blank=True, help_text='Packinghouse this statement is from (auto-detected if not specified)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='api.packinghouse'),
        ),
        migrations.AlterField(
            model_name='statementbatchupload',
            name='packinghouse',
            field=models.ForeignKey(blank=True, help_text='Default packinghouse (null for mixed uploads with auto-detection)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_uploads', to='api.packinghouse'),
        ),
    ]
