# Generated by Django 4.2 on 2026-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_batch_upload_and_grower_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersource',
            name='base_extraction_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base extraction rate $/AF (e.g., OBGMA $25, UWCD $192.34)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='domestic_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Domestic usage rate $/AF (e.g., UWCD $214.22)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='fixed_quarterly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed quarterly fee (e.g., OBGMA $70)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='gsp_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GSP/SGMA fee rate $/AF (e.g., OBGMA $100)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='is_domestic_well',
            field=models.BooleanField(default=False, help_text='Well is primarily for domestic use (different rate applies)'),
        ),
        migrations.AddField(
            model_name='watersource',
            name='owner_code',
            field=models.CharField(blank=True, help_text='Owner identifier code (e.g., JPF, FF, RMLF)', max_length=20),
        ),
        migrations.AddField(
            model_name='wellreading',
            name='base_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated base extraction fee', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wellreading',
            name='domestic_extraction_af',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Domestic portion of extraction (acre-feet)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wellreading',
            name='domestic_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated domestic fee', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wellreading',
            name='fixed_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed quarterly fee', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wellreading',
            name='gsp_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated GSP/SGMA fee', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wellreading',
            name='irrigation_extraction_af',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Irrigation portion of extraction (acre-feet)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wellreading',
            name='meter_rollover',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Meter rollover value if meter reset (e.g., 1000000)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='wellreading',
            name='total_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total fees due this period', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='watersource',
            name='gsa',
            field=models.CharField(blank=True, choices=[('obgma', 'Ojai Basin Groundwater Management Agency (OBGMA)'), ('uwcd', 'United Water Conservation District (UWCD)'), ('fpbgsa', 'Fillmore and Piru Basins GSA'), ('uvrga', 'Upper Ventura River Groundwater Agency'), ('fcgma', 'Fox Canyon Groundwater Management Agency'), ('other', 'Other'), ('none', 'Not in GSA Jurisdiction')], help_text='Groundwater Sustainability Agency', max_length=20),
        ),
    ]
