# Generated by Django 4.2 on 2026-01-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_add_gsa_fee_and_wellreading_fields'),
        ('api', '0037_auto_detect_packinghouse'),
    ]

    operations = [
    ]
