# Generated by Django 4.2 on 2026-01-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merge_20260127_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packoutreport',
            name='field',
            field=models.ForeignKey(blank=True, help_text='Field this packout is from (optional - packouts may aggregate multiple fields)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packout_reports', to='api.field'),
        ),
    ]
