# Generated by Django 4.2 on 2026-01-28 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_optional_field_on_packout'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSMAEnvironmentalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flooding_risk', models.CharField(choices=[('none', 'No Flooding Risk'), ('low', 'Low - Rare flooding'), ('medium', 'Medium - Occasional flooding'), ('high', 'High - Frequent flooding')], default='none', max_length=20)),
                ('flooding_history', models.BooleanField(default=False)),
                ('last_flood_date', models.DateField(blank=True, null=True)),
                ('flood_frequency', models.CharField(blank=True, max_length=50)),
                ('heavy_rain_frequency', models.CharField(blank=True, help_text='Description of heavy rain patterns', max_length=100)),
                ('extreme_weather_notes', models.TextField(blank=True)),
                ('adjacent_land_uses', models.JSONField(blank=True, default=list, help_text='List of adjacent land uses')),
                ('animal_operations_nearby', models.BooleanField(default=False)),
                ('animal_operation_type', models.CharField(blank=True, help_text='Type of animal operation (dairy, poultry, etc.)', max_length=100)),
                ('animal_operation_distance_ft', models.IntegerField(blank=True, help_text='Distance to animal operation in feet', null=True)),
                ('nearest_cafo_distance', models.CharField(blank=True, choices=[('within_100ft', 'Within 100 feet'), ('100_400ft', '100-400 feet'), ('400_1000ft', '400-1000 feet'), ('over_1000ft', 'Over 1000 feet'), ('none_nearby', 'None in Vicinity')], max_length=20)),
                ('nearest_grazing_distance', models.CharField(blank=True, choices=[('within_100ft', 'Within 100 feet'), ('100_400ft', '100-400 feet'), ('400_1000ft', '400-1000 feet'), ('over_1000ft', 'Over 1000 feet'), ('none_nearby', 'None in Vicinity')], max_length=20)),
                ('animal_intrusion_history', models.BooleanField(default=False)),
                ('animal_intrusion_notes', models.TextField(blank=True)),
                ('manure_application_nearby', models.BooleanField(default=False)),
                ('manure_notes', models.TextField(blank=True)),
                ('human_waste_nearby', models.BooleanField(default=False)),
                ('human_waste_type', models.CharField(blank=True, help_text='Type (septic, portable toilets, etc.)', max_length=100)),
                ('nearest_septic_distance', models.CharField(blank=True, choices=[('within_100ft', 'Within 100 feet'), ('100_400ft', '100-400 feet'), ('400_1000ft', '400-1000 feet'), ('over_1000ft', 'Over 1000 feet'), ('none_nearby', 'None in Vicinity')], max_length=20)),
                ('septic_system_status', models.CharField(blank=True, max_length=50)),
                ('upslope_land_uses', models.TextField(blank=True)),
                ('runoff_management_in_place', models.BooleanField(default=False)),
                ('runoff_management_description', models.TextField(blank=True)),
                ('wildlife_pressure', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('wildlife_types_observed', models.TextField(blank=True)),
                ('wildlife_exclusion_measures', models.TextField(blank=True)),
                ('other_water_users', models.TextField(blank=True, help_text='Description of other users of water system')),
                ('other_hazards', models.TextField(blank=True, help_text='Any other identified hazards')),
                ('previous_contamination', models.BooleanField(default=False)),
                ('contamination_details', models.TextField(blank=True)),
                ('environmental_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('adjacent_land_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('environmental_risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('has_adjacent_land_hazards', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FSMA Environmental Assessment',
                'verbose_name_plural': 'FSMA Environmental Assessments',
            },
        ),
        migrations.CreateModel(
            name='FSMAFieldAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_method', models.CharField(blank=True, choices=[('overhead', 'Overhead Sprinkler'), ('drip', 'Drip/Micro-irrigation'), ('micro_sprinkler', 'Micro-Sprinkler'), ('furrow', 'Furrow/Flood'), ('subsurface', 'Subsurface Drip'), ('hand_watering', 'Hand Watering'), ('none', 'No Irrigation')], max_length=30)),
                ('crop_contact_type', models.CharField(blank=True, choices=[('direct', 'Water Directly Contacts Harvestable Portion'), ('indirect', 'Water Contacts Non-Harvestable Portions Only'), ('soil_only', 'Water Applied to Soil Only')], max_length=20)),
                ('typical_days_before_harvest', models.IntegerField(blank=True, help_text='Typical days between last irrigation and harvest', null=True)),
                ('minimum_days_before_harvest', models.IntegerField(blank=True, help_text='Minimum days between last irrigation and harvest', null=True)),
                ('foliar_applications', models.BooleanField(default=False, help_text='Any foliar spray applications using this water?')),
                ('crop_growth_position', models.CharField(choices=[('tree', 'Tree Fruit (Elevated)'), ('vine', 'Vine'), ('ground', 'Ground Level'), ('root', 'Root Crop')], default='tree', max_length=20)),
                ('crop_surface_type', models.CharField(choices=[('smooth', 'Smooth'), ('rough', 'Rough/Textured'), ('netted', 'Netted'), ('leafy', 'Leafy')], default='smooth', max_length=20)),
                ('internalization_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Susceptibility to pathogen internalization', max_length=20)),
                ('die_off_period_adequate', models.BooleanField(blank=True, null=True)),
                ('die_off_conditions_notes', models.TextField(blank=True, help_text='UV exposure, temperature, drying conditions, etc.')),
                ('practice_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('crop_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('field_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('field_risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FSMA Field Assessment',
                'verbose_name_plural': 'FSMA Field Assessments',
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='adjacent_land_uses',
            field=models.JSONField(blank=True, default=list, help_text='List of adjacent/nearby land uses for FSMA assessment'),
        ),
        migrations.AddField(
            model_name='farm',
            name='flooding_history',
            field=models.BooleanField(default=False, help_text='Has this farm experienced flooding in production areas?'),
        ),
        migrations.AddField(
            model_name='farm',
            name='nearest_animal_operation_ft',
            field=models.IntegerField(blank=True, help_text='Distance to nearest animal operation in feet', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='septic_nearby',
            field=models.BooleanField(blank=True, help_text='Are septic systems located near production areas?', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='typical_days_before_harvest',
            field=models.IntegerField(blank=True, help_text='Typical days between last irrigation and harvest', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='water_contacts_harvestable',
            field=models.BooleanField(blank=True, help_text='Does irrigation water directly contact harvestable portion?', null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='fsma_animal_access_possible',
            field=models.BooleanField(default=False, help_text='Can animals access the water source?'),
        ),
        migrations.AddField(
            model_name='watersource',
            name='fsma_backflow_prevention',
            field=models.BooleanField(blank=True, help_text='Is backflow prevention device installed?', null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='fsma_debris_present',
            field=models.BooleanField(default=False, help_text='Is debris present at or near the water source?'),
        ),
        migrations.AddField(
            model_name='watersource',
            name='fsma_distribution_type',
            field=models.CharField(blank=True, choices=[('closed', 'Closed (Piped)'), ('open', 'Open (Canal/Ditch)'), ('mixed', 'Mixed')], default='closed', help_text='Type of water distribution system', max_length=20),
        ),
        migrations.AddField(
            model_name='watersource',
            name='fsma_last_physical_inspection',
            field=models.DateField(blank=True, help_text='Date of last physical inspection', null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='fsma_well_cap_secure',
            field=models.BooleanField(blank=True, help_text='Is the well cap securely in place?', null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='fsma_well_casing_intact',
            field=models.BooleanField(blank=True, help_text='Is the well casing intact without cracks?', null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='fsma_wellhead_condition',
            field=models.CharField(blank=True, choices=[('good', 'Good - No deficiencies'), ('fair', 'Fair - Minor issues'), ('poor', 'Poor - Significant deficiencies'), ('na', 'N/A - Not a well')], default='na', help_text='Physical condition of wellhead for FSMA assessment', max_length=20),
        ),
        migrations.CreateModel(
            name='FSMAWaterAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_year', models.IntegerField(help_text='Year this assessment covers')),
                ('assessment_date', models.DateField(help_text='Date assessment was conducted')),
                ('assessor_name', models.CharField(max_length=200)),
                ('assessor_title', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('overall_risk_score', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated overall risk score (0-100)', max_digits=5, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('fda_outcome', models.CharField(blank=True, choices=[('no_treatment', 'No Treatment Required'), ('treatment_required', 'Treatment Required'), ('die_off_required', 'Die-Off Period Required'), ('testing_required', 'Additional Testing Required')], max_length=30)),
                ('outcome_notes', models.TextField(blank=True, help_text='Written justification for the determination')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('assessor_signature', models.TextField(blank=True, help_text='Base64-encoded signature image or typed name')),
                ('assessor_signature_date', models.DateTimeField(blank=True, null=True)),
                ('approver_signature', models.TextField(blank=True, help_text='Base64-encoded signature image or typed name')),
                ('approver_signature_date', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='water_assessments/%Y/%m/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('general_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_water_assessments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_assessments', to='api.company')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_assessments', to='api.farm')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_water_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FSMA Water Assessment',
                'verbose_name_plural': 'FSMA Water Assessments',
                'ordering': ['-assessment_year', 'farm__name'],
            },
        ),
        migrations.CreateModel(
            name='FSMASourceAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_control_level', models.CharField(choices=[('full', 'Fully Under Control'), ('partial', 'Partially Under Control'), ('minimal', 'Minimal Control')], default='full', max_length=20)),
                ('distribution_control_level', models.CharField(choices=[('full', 'Fully Under Control'), ('partial', 'Partially Under Control'), ('minimal', 'Minimal Control')], default='full', max_length=20)),
                ('wellhead_condition', models.CharField(blank=True, choices=[('good', 'Good - No deficiencies'), ('fair', 'Fair - Minor issues'), ('poor', 'Poor - Significant deficiencies'), ('critical', 'Critical - Immediate action needed')], max_length=20)),
                ('well_cap_secure', models.BooleanField(blank=True, null=True)),
                ('well_casing_intact', models.BooleanField(blank=True, null=True)),
                ('backflow_prevention', models.BooleanField(blank=True, null=True)),
                ('distribution_type', models.CharField(blank=True, choices=[('direct_contact', 'Direct Contact with Harvestable Portion'), ('indirect_contact', 'Indirect Contact'), ('no_contact', 'No Contact with Harvestable Portion')], max_length=30)),
                ('animal_access_possible', models.BooleanField(default=False)),
                ('debris_present', models.BooleanField(default=False)),
                ('standing_water_near_source', models.BooleanField(default=False)),
                ('runoff_exposure', models.BooleanField(default=False)),
                ('inspected_this_year', models.BooleanField(default=False)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('inspection_findings', models.TextField(blank=True)),
                ('overall_condition', models.CharField(choices=[('good', 'Good - No deficiencies'), ('fair', 'Fair - Minor issues'), ('poor', 'Poor - Significant deficiencies'), ('critical', 'Critical - Immediate action needed')], default='good', max_length=20)),
                ('protection_description', models.TextField(blank=True, help_text='Describe how source is protected from contamination')),
                ('last_test_date', models.DateField(blank=True, null=True)),
                ('last_e_coli_result', models.DecimalField(blank=True, decimal_places=2, help_text='Most recent E. coli result (CFU/100mL)', max_digits=10, null=True)),
                ('last_generic_ecoli_gm', models.DecimalField(blank=True, decimal_places=2, help_text='Geometric Mean E. coli (CFU/100mL)', max_digits=10, null=True)),
                ('last_generic_ecoli_stv', models.DecimalField(blank=True, decimal_places=2, help_text='Statistical Threshold Value (CFU/100mL)', max_digits=10, null=True)),
                ('meets_quality_standard', models.BooleanField(blank=True, null=True)),
                ('treatment_applied', models.CharField(blank=True, max_length=100)),
                ('treatment_log_available', models.BooleanField(default=False)),
                ('source_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source_risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('risk_factors', models.JSONField(default=list, help_text='List of risk factors identified during assessment')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='water_assessment_photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='water_assessment_photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_assessments', to='api.fsmawaterassessment')),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsma_source_assessments', to='api.watersource')),
            ],
            options={
                'verbose_name': 'FSMA Source Assessment',
                'verbose_name_plural': 'FSMA Source Assessments',
            },
        ),
        migrations.CreateModel(
            name='FSMAMitigationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure Repair/Improvement'), ('testing', 'Additional Testing'), ('treatment', 'Water Treatment'), ('exclusion', 'Animal/Wildlife Exclusion'), ('operational', 'Operational Change'), ('documentation', 'Documentation/Training'), ('other', 'Other')], max_length=30)),
                ('hazard_source', models.CharField(blank=True, choices=[('adjacent_animal', 'Adjacent Land - Animal Activity'), ('adjacent_manure', 'Adjacent Land - Manure/BSAAO'), ('adjacent_human_waste', 'Adjacent Land - Human Waste'), ('on_farm', 'On-Farm Hazard'), ('water_system', 'Water System Issue'), ('environmental', 'Environmental Condition')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('hazard_description', models.TextField(blank=True, help_text='Description of the hazard being mitigated')),
                ('mitigation_description', models.TextField(help_text='Description of the mitigation action')),
                ('priority', models.CharField(choices=[('critical', 'Critical - Immediate Action Required'), ('high', 'High - Action Required Within 7 Days'), ('medium', 'Medium - Action Required Within 30 Days'), ('low', 'Low - Action Required Before Next Assessment')], max_length=20)),
                ('due_date', models.DateField()),
                ('requires_same_season', models.BooleanField(default=False, help_text='True if hazard from adjacent land (requires same-season action)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('not_required', 'No Longer Required')], default='pending', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('verification_required', models.BooleanField(default=False)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='mitigation_evidence/')),
                ('evidence_photo', models.ImageField(blank=True, null=True, upload_to='mitigation_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_actions', to='api.fsmawaterassessment')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_water_mitigations', to=settings.AUTH_USER_MODEL)),
                ('environmental_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigation_actions', to='api.fsmaenvironmentalassessment')),
                ('field_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigation_actions', to='api.fsmafieldassessment')),
                ('source_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigation_actions', to='api.fsmasourceassessment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_water_mitigations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FSMA Mitigation Action',
                'verbose_name_plural': 'FSMA Mitigation Actions',
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.AddField(
            model_name='fsmafieldassessment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_assessments', to='api.fsmawaterassessment'),
        ),
        migrations.AddField(
            model_name='fsmafieldassessment',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsma_water_assessments', to='api.field'),
        ),
        migrations.AddField(
            model_name='fsmafieldassessment',
            name='water_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fsma_field_assessments', to='api.watersource'),
        ),
        migrations.AddField(
            model_name='fsmaenvironmentalassessment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_assessments', to='api.fsmawaterassessment'),
        ),
        migrations.AddIndex(
            model_name='fsmawaterassessment',
            index=models.Index(fields=['company', '-assessment_year'], name='idx_water_asmt_company_year'),
        ),
        migrations.AddIndex(
            model_name='fsmawaterassessment',
            index=models.Index(fields=['status'], name='idx_water_asmt_status'),
        ),
        migrations.AddIndex(
            model_name='fsmawaterassessment',
            index=models.Index(fields=['valid_until'], name='idx_water_asmt_valid_until'),
        ),
        migrations.AlterUniqueTogether(
            name='fsmawaterassessment',
            unique_together={('farm', 'assessment_year')},
        ),
        migrations.AlterUniqueTogether(
            name='fsmasourceassessment',
            unique_together={('assessment', 'water_source')},
        ),
        migrations.AddIndex(
            model_name='fsmamitigationaction',
            index=models.Index(fields=['status', 'due_date'], name='idx_mitigation_status_due'),
        ),
        migrations.AlterUniqueTogether(
            name='fsmafieldassessment',
            unique_together={('assessment', 'field')},
        ),
        # =================================================================
        # RLS POLICIES FOR FSMA WATER ASSESSMENT TABLES
        # =================================================================
        migrations.RunSQL(
            sql="""
            -- FSMAWaterAssessment RLS (direct company_id)
            ALTER TABLE api_fsmawaterassessment ENABLE ROW LEVEL SECURITY;
            CREATE POLICY fsmawaterassessment_company_policy ON api_fsmawaterassessment
                USING (company_id::text = current_setting('app.current_company_id', true));

            -- FSMASourceAssessment RLS (through assessment -> company)
            ALTER TABLE api_fsmasourceassessment ENABLE ROW LEVEL SECURITY;
            CREATE POLICY fsmasourceassessment_company_policy ON api_fsmasourceassessment
                USING (assessment_id IN (
                    SELECT id FROM api_fsmawaterassessment
                    WHERE company_id::text = current_setting('app.current_company_id', true)
                ));

            -- FSMAFieldAssessment RLS (through assessment -> company)
            ALTER TABLE api_fsmafieldassessment ENABLE ROW LEVEL SECURITY;
            CREATE POLICY fsmafieldassessment_company_policy ON api_fsmafieldassessment
                USING (assessment_id IN (
                    SELECT id FROM api_fsmawaterassessment
                    WHERE company_id::text = current_setting('app.current_company_id', true)
                ));

            -- FSMAEnvironmentalAssessment RLS (through assessment -> company)
            ALTER TABLE api_fsmaenvironmentalassessment ENABLE ROW LEVEL SECURITY;
            CREATE POLICY fsmaenvironmentalassessment_company_policy ON api_fsmaenvironmentalassessment
                USING (assessment_id IN (
                    SELECT id FROM api_fsmawaterassessment
                    WHERE company_id::text = current_setting('app.current_company_id', true)
                ));

            -- FSMAMitigationAction RLS (through assessment -> company)
            ALTER TABLE api_fsmamitigationaction ENABLE ROW LEVEL SECURITY;
            CREATE POLICY fsmamitigationaction_company_policy ON api_fsmamitigationaction
                USING (assessment_id IN (
                    SELECT id FROM api_fsmawaterassessment
                    WHERE company_id::text = current_setting('app.current_company_id', true)
                ));
            """,
            reverse_sql="""
            -- Reverse RLS for FSMAWaterAssessment
            DROP POLICY IF EXISTS fsmawaterassessment_company_policy ON api_fsmawaterassessment;
            ALTER TABLE api_fsmawaterassessment DISABLE ROW LEVEL SECURITY;

            -- Reverse RLS for FSMASourceAssessment
            DROP POLICY IF EXISTS fsmasourceassessment_company_policy ON api_fsmasourceassessment;
            ALTER TABLE api_fsmasourceassessment DISABLE ROW LEVEL SECURITY;

            -- Reverse RLS for FSMAFieldAssessment
            DROP POLICY IF EXISTS fsmafieldassessment_company_policy ON api_fsmafieldassessment;
            ALTER TABLE api_fsmafieldassessment DISABLE ROW LEVEL SECURITY;

            -- Reverse RLS for FSMAEnvironmentalAssessment
            DROP POLICY IF EXISTS fsmaenvironmentalassessment_company_policy ON api_fsmaenvironmentalassessment;
            ALTER TABLE api_fsmaenvironmentalassessment DISABLE ROW LEVEL SECURITY;

            -- Reverse RLS for FSMAMitigationAction
            DROP POLICY IF EXISTS fsmamitigationaction_company_policy ON api_fsmamitigationaction;
            ALTER TABLE api_fsmamitigationaction DISABLE ROW LEVEL SECURITY;
            """
        ),
    ]
