# Generated by Django 4.2 on 2026-01-28 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_fsma_water_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsmawaterassessment',
            name='assessor',
            field=models.ForeignKey(blank=True, help_text='User who conducted the assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_assessments_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fsmawaterassessment',
            name='assessment_date',
            field=models.DateField(blank=True, help_text='Date assessment was conducted', null=True),
        ),
        migrations.AlterField(
            model_name='fsmawaterassessment',
            name='assessor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
