# Generated by Django 4.2 on 2026-01-28 19:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_fix_water_assessment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='supports_multiple_cycles',
            field=models.BooleanField(default=False, help_text='True for crops with multiple harvests per year (lettuce, strawberries)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='typical_cycles_per_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Typical number of growing cycles per year (for multi-cycle crops)', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='typical_days_to_maturity',
            field=models.PositiveIntegerField(blank=True, help_text='Typical days from planting to harvest', null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='season_end',
            field=models.DateField(blank=True, help_text='Actual season end date', null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='season_start',
            field=models.DateField(blank=True, help_text='Actual season start date', null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='season',
            field=models.CharField(help_text='Legacy season string (e.g., "2024-2025")', max_length=20),
        ),
        migrations.CreateModel(
            name='SeasonTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'California Citrus', 'Calendar Year')", max_length=100)),
                ('season_type', models.CharField(choices=[('calendar_year', 'Calendar Year (Jan-Dec)'), ('citrus', 'Citrus Season (Oct-Sep)'), ('almond', 'Almond Season (Feb-Oct)'), ('grape', 'Grape Season (Mar-Nov)'), ('multiple_cycle', 'Multiple Cycles Per Year'), ('custom', 'Custom Date Range')], default='calendar_year', help_text='Season calculation type', max_length=30)),
                ('start_month', models.PositiveSmallIntegerField(help_text='Month season starts (1=January, 12=December)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month season starts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('duration_months', models.PositiveSmallIntegerField(default=12, help_text='Duration in months (typically 12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('crosses_calendar_year', models.BooleanField(default=False, help_text='True if season spans two calendar years (e.g., citrus Oct-Sep)')),
                ('label_format', models.CharField(default='{start_year}', help_text='Label format using {start_year} and/or {end_year} placeholders', max_length=50)),
                ('applicable_categories', models.JSONField(blank=True, default=list, help_text="List of CropCategory values this template applies to (e.g., ['citrus', 'subtropical'])")),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Null for system defaults, set for company-specific templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_templates', to='api.company')),
            ],
            options={
                'verbose_name': 'Season Template',
                'verbose_name_plural': 'Season Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrowingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, help_text='Cycle number within the year (1, 2, 3...)')),
                ('year', models.PositiveIntegerField(help_text='Calendar year this cycle occurs in')),
                ('planting_date', models.DateField(blank=True, help_text='Actual or planned planting date', null=True)),
                ('expected_harvest_start', models.DateField(blank=True, help_text='Expected start of harvest window', null=True)),
                ('expected_harvest_end', models.DateField(blank=True, help_text='Expected end of harvest window', null=True)),
                ('actual_harvest_date', models.DateField(blank=True, help_text='Actual harvest completion date', null=True)),
                ('days_to_maturity', models.PositiveIntegerField(blank=True, help_text='Expected days from planting to harvest (can override crop default)', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('planted', 'Planted'), ('growing', 'Growing'), ('harvesting', 'Harvesting'), ('complete', 'Complete'), ('abandoned', 'Abandoned')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, help_text="Crop for this cycle (optional, defaults to field's crop)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='growing_cycles', to='api.crop')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growing_cycles', to='api.field')),
            ],
            options={
                'verbose_name': 'Growing Cycle',
                'verbose_name_plural': 'Growing Cycles',
                'ordering': ['year', 'cycle_number'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='season_template',
            field=models.ForeignKey(blank=True, help_text='Default season template for this crop type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='api.seasontemplate'),
        ),
        migrations.AddField(
            model_name='field',
            name='current_growing_cycle',
            field=models.ForeignKey(blank=True, help_text='Currently active growing cycle (for multi-cycle crops)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.growingcycle'),
        ),
        migrations.AddField(
            model_name='field',
            name='season_template',
            field=models.ForeignKey(blank=True, help_text="Override season template for this field (defaults to crop's template)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='api.seasontemplate'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='growing_cycle',
            field=models.ForeignKey(blank=True, help_text='Associated growing cycle (for multi-cycle crops)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='api.growingcycle'),
        ),
        migrations.AddField(
            model_name='pesticideapplication',
            name='growing_cycle',
            field=models.ForeignKey(blank=True, help_text='Associated growing cycle (for multi-cycle crops like lettuce)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='api.growingcycle'),
        ),
        migrations.AddField(
            model_name='pool',
            name='season_template',
            field=models.ForeignKey(blank=True, help_text='Season template used for this pool', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='api.seasontemplate'),
        ),
        migrations.AddIndex(
            model_name='seasontemplate',
            index=models.Index(fields=['company', 'active'], name='api_seasont_company_834c87_idx'),
        ),
        migrations.AddIndex(
            model_name='seasontemplate',
            index=models.Index(fields=['season_type'], name='api_seasont_season__16e004_idx'),
        ),
        migrations.AddConstraint(
            model_name='seasontemplate',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_season_template_per_company'),
        ),
        migrations.AddIndex(
            model_name='growingcycle',
            index=models.Index(fields=['field', 'year'], name='api_growing_field_i_fd2d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='growingcycle',
            index=models.Index(fields=['status', 'year'], name='api_growing_status_6a0c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='growingcycle',
            index=models.Index(fields=['planting_date'], name='api_growing_plantin_e89539_idx'),
        ),
        migrations.AddConstraint(
            model_name='growingcycle',
            constraint=models.UniqueConstraint(fields=('field', 'year', 'cycle_number'), name='unique_cycle_per_field_year'),
        ),
    ]
