# Generated by Django 4.2 on 2026-01-28

from django.db import migrations


def seed_season_templates(apps, schema_editor):
    """
    Seed the default system-wide season templates.

    Season timing research (California):

    CITRUS (Oct 1 - Sep 30):
    - Industry uses October-September marketing/fiscal year
    - Navel oranges: Nov-June (peak Jan-Feb)
    - Valencia oranges: Mar-Oct (peak May-Aug)
    - Lemons: Year-round (peak late winter-early summer)
    - Mandarins: Nov-May
    - Oct 1 start captures the full marketing year

    AVOCADOS (Nov 1 - Oct 31):
    - California Avocado Commission fiscal year: November-October
    - Assessment period: Nov 1 through Oct 31
    - Harvest builds Feb/Mar, peaks Apr-Aug, ends Sep/Oct
    - Nov 1 start aligns with CAC reporting and captures full crop cycle

    ALMONDS (Feb 1 - Oct 31):
    - Bloom: February
    - Harvest: Aug-Oct
    - 9-month growing cycle

    GRAPES (Mar 1 - Dec 31):
    - Bud break: March
    - Harvest: Aug-Nov (varies by variety)
    - 10-month growing season
    """
    SeasonTemplate = apps.get_model('api', 'SeasonTemplate')

    templates = [
        # =======================================================================
        # CITRUS - Oct 1 to Sep 30 (industry standard marketing year)
        # =======================================================================
        {
            'name': 'California Citrus',
            'season_type': 'citrus',
            'start_month': 10,
            'start_day': 1,
            'duration_months': 12,
            'crosses_calendar_year': True,
            'label_format': '{start_year}-{end_year}',
            'applicable_categories': ['citrus'],
            'description': 'Standard California citrus marketing year (Oct-Sep). Used for oranges, lemons, mandarins, grapefruit.',
        },

        # =======================================================================
        # AVOCADOS - Nov 1 to Oct 31 (CAC fiscal year)
        # =======================================================================
        {
            'name': 'California Avocado',
            'season_type': 'avocado',
            'start_month': 11,
            'start_day': 1,
            'duration_months': 12,
            'crosses_calendar_year': True,
            'label_format': '{start_year}-{end_year}',
            'applicable_categories': ['subtropical'],
            'description': 'California Avocado Commission fiscal year (Nov-Oct). Aligns with CAC assessment periods and reporting.',
        },

        # =======================================================================
        # CALENDAR YEAR - Jan 1 to Dec 31
        # =======================================================================
        {
            'name': 'Calendar Year',
            'season_type': 'calendar_year',
            'start_month': 1,
            'start_day': 1,
            'duration_months': 12,
            'crosses_calendar_year': False,
            'label_format': '{start_year}',
            'applicable_categories': ['deciduous_fruit', 'berry', 'other'],
            'description': 'Standard calendar year (Jan-Dec). Default for deciduous fruit, berries, and general use.',
        },

        # =======================================================================
        # ALMONDS - Feb 1 to Oct 31 (bloom to harvest)
        # =======================================================================
        {
            'name': 'California Almond',
            'season_type': 'almond',
            'start_month': 2,
            'start_day': 1,
            'duration_months': 9,
            'crosses_calendar_year': False,
            'label_format': '{start_year}',
            'applicable_categories': ['nut'],
            'description': 'California almond growing season (Feb-Oct). From bloom through harvest.',
        },

        # =======================================================================
        # GRAPES - Mar 1 to Dec 31 (bud break to post-harvest)
        # =======================================================================
        {
            'name': 'California Grape',
            'season_type': 'grape',
            'start_month': 3,
            'start_day': 1,
            'duration_months': 10,
            'crosses_calendar_year': False,
            'label_format': '{start_year}',
            'applicable_categories': ['vine'],
            'description': 'California grape growing season (Mar-Dec). From bud break through harvest and dormancy prep.',
        },

        # =======================================================================
        # ROW CROPS - Calendar year (supports multiple cycles)
        # =======================================================================
        {
            'name': 'Row Crop / Vegetable',
            'season_type': 'multiple_cycle',
            'start_month': 1,
            'start_day': 1,
            'duration_months': 12,
            'crosses_calendar_year': False,
            'label_format': '{start_year}',
            'applicable_categories': ['row_crop', 'vegetable'],
            'description': 'Calendar year for row crops and vegetables. Individual growing cycles tracked separately.',
        },
    ]

    for template_data in templates:
        # Pop description since it may not be in model yet
        description = template_data.pop('description', '')

        SeasonTemplate.objects.get_or_create(
            name=template_data['name'],
            company=None,  # System default
            defaults=template_data
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded templates on reverse migration."""
    SeasonTemplate = apps.get_model('api', 'SeasonTemplate')
    SeasonTemplate.objects.filter(company__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_season_management'),
    ]

    operations = [
        migrations.RunPython(seed_season_templates, reverse_seed),
    ]
