# Generated by Django 4.2 on 2026-01-28 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_seed_season_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasontemplate',
            name='season_type',
            field=models.CharField(choices=[('calendar_year', 'Calendar Year (Jan-Dec)'), ('citrus', 'Citrus Season (Oct-Sep)'), ('avocado', 'Avocado Season (Nov-Oct)'), ('almond', 'Almond Season (Feb-Oct)'), ('grape', 'Grape Season (Mar-Dec)'), ('multiple_cycle', 'Multiple Cycles Per Year'), ('custom', 'Custom Date Range')], default='calendar_year', help_text='Season calculation type', max_length=30),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
