# Generated by Django 4.2 on 2026-01-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_add_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementdeduction',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='UNIT', help_text='Unit (BIN, CTN, LBS, etc.)', max_length=20),
        ),
    ]
