# Generated by Django 4.2 on 2026-02-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_normalize_pool_commodities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellreading',
            name='extraction_acre_feet',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Extraction converted to acre-feet', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='wellreading',
            name='extraction_gallons',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Extraction converted to gallons', max_digits=20, null=True),
        ),
    ]
