# Generated by Django 4.2 on 2026-02-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_increase_extraction_field_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellreading',
            name='domestic_extraction_af',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Domestic portion of extraction (acre-feet)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='wellreading',
            name='irrigation_extraction_af',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Irrigation portion of extraction (acre-feet)', max_digits=20, null=True),
        ),
    ]
