# Generated by Django 4.2 on 2026-02-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_increase_split_extraction_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersource',
            name='flowmeter_units',
            field=models.CharField(choices=[('acre_feet', 'Acre-Feet'), ('gallons', 'Gallons'), ('hundred_gallons', 'Hundred Gallons'), ('thousand_gallons', 'Thousand Gallons'), ('cubic_feet', 'Cubic Feet'), ('hundred_cubic_feet', 'Hundred Cubic Feet (CCF)')], default='gallons', max_length=20),
        ),
    ]
