# Generated by Django 4.2 on 2026-02-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_change_default_flowmeter_units_to_gallons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packoutgradeline',
            name='size',
            field=models.CharField(blank=True, help_text='Size code (e.g., "075", "088", "113")', max_length=20),
        ),
        migrations.AlterField(
            model_name='settlementgradeline',
            name='size',
            field=models.CharField(blank=True, help_text='Size code (e.g., "048", "056", "072")', max_length=20),
        ),
    ]
