# Generated by Django 4.2 on 2026-02-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_widen_grade_line_size_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='crop_variety',
            field=models.CharField(choices=[('navel_orange', 'Navel Orange'), ('valencia_orange', 'Valencia Orange'), ('cara_cara', 'Cara Cara Orange'), ('blood_orange', 'Blood Orange'), ('meyer_lemon', 'Meyer Lemon'), ('eureka_lemon', 'Eureka Lemon'), ('lisbon_lemon', 'Lisbon Lemon'), ('lime', 'Lime'), ('grapefruit_white', 'White Grapefruit'), ('grapefruit_ruby', 'Ruby Red Grapefruit'), ('mandarin', 'Mandarin'), ('tangerine', 'Tangerine'), ('clementine', 'Clementine'), ('satsuma', 'Satsuma'), ('tangelo', 'Tangelo'), ('kumquat', 'Kumquat'), ('hass_avocado', 'Hass Avocado'), ('lamb_hass_avocado', 'Lamb Hass Avocado'), ('gem_avocado', 'GEM Avocado'), ('reed_avocado', 'Reed Avocado'), ('fuerte_avocado', 'Fuerte Avocado'), ('bacon_avocado', 'Bacon Avocado'), ('other', 'Other')], default='navel_orange', max_length=30),
        ),
        migrations.AlterField(
            model_name='poolsettlement',
            name='total_bins',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total bins in settlement (primary for citrus)', max_digits=10, null=True),
        ),
    ]
