# Generated by Django 4.2 on 2026-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_yield_forecast_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['farm', '-incident_date'], name='idx_incident_farm_date'),
        ),
        migrations.AddIndex(
            model_name='irrigationevent',
            index=models.Index(fields=['field', '-irrigation_date'], name='idx_irrig_field_date'),
        ),
        migrations.AddIndex(
            model_name='irrigationevent',
            index=models.Index(fields=['zone', '-irrigation_date'], name='idx_irrig_zone_date'),
        ),
        migrations.AddIndex(
            model_name='metercalibration',
            index=models.Index(fields=['water_source', '-calibration_date'], name='idx_metercal_source_date'),
        ),
        migrations.AddIndex(
            model_name='metercalibration',
            index=models.Index(fields=['water_source', 'next_calibration_due'], name='idx_metercal_source_nextdue'),
        ),
        migrations.AddIndex(
            model_name='pesticideapplication',
            index=models.Index(fields=['field', 'application_date'], name='idx_pestapp_field_date'),
        ),
        migrations.AddIndex(
            model_name='pesticideapplication',
            index=models.Index(fields=['product', 'application_date'], name='idx_pestapp_product_date'),
        ),
        migrations.AddIndex(
            model_name='scoutingreport',
            index=models.Index(fields=['farm', '-observed_date'], name='idx_scout_farm_date'),
        ),
        migrations.AddIndex(
            model_name='scoutingreport',
            index=models.Index(fields=['field', '-observed_date'], name='idx_scout_field_date'),
        ),
        migrations.AddIndex(
            model_name='soilmoisturereading',
            index=models.Index(fields=['zone', '-reading_datetime'], name='idx_soilmoist_zone_datetime'),
        ),
        migrations.AddIndex(
            model_name='watertest',
            index=models.Index(fields=['water_source', '-test_date'], name='idx_watertest_source_date'),
        ),
    ]
