# Generated by Django 4.2 on 2026-02-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_add_composite_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='yieldforecast',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('field', 'season_label', 'forecast_date', 'status'), name='unique_published_forecast_per_field_season_date'),
        ),
    ]
