# Generated by Django 4.2 on 2026-02-11 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_yield_forecast_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_number', models.CharField(max_length=20)),
                ('primus_module', models.CharField(blank=True, choices=[('food_safety_management', 'Food Safety Management System'), ('good_agricultural_practices', 'Good Agricultural Practices'), ('pest_management', 'Pest Management'), ('water_management', 'Water Management'), ('worker_hygiene', 'Worker Hygiene & Sanitation'), ('traceability', 'Traceability & Recall'), ('supplier_management', 'Supplier Management'), ('food_defense', 'Food Defense'), ('land_assessment', 'Land Assessment'), ('equipment_calibration', 'Equipment Calibration'), ('general', 'General')], max_length=50)),
                ('primus_clause', models.CharField(blank=True, help_text='e.g., 2.01.01', max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical Non-Conformance'), ('major', 'Major Non-Conformance'), ('minor', 'Minor Non-Conformance'), ('observation', 'Observation'), ('opportunity', 'Improvement Opportunity')], max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True)),
                ('area_location', models.CharField(blank=True, max_length=200)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['finding_number'],
            },
        ),
        migrations.CreateModel(
            name='ControlledDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(help_text='e.g., SOP-GAP-001', max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('sop', 'Standard Operating Procedure'), ('policy', 'Policy'), ('manual', 'Manual'), ('form', 'Form/Template'), ('record', 'Record'), ('plan', 'Plan'), ('work_instruction', 'Work Instruction'), ('external', 'External Document')], max_length=30)),
                ('primus_module', models.CharField(choices=[('food_safety_management', 'Food Safety Management System'), ('good_agricultural_practices', 'Good Agricultural Practices'), ('pest_management', 'Pest Management'), ('water_management', 'Water Management'), ('worker_hygiene', 'Worker Hygiene & Sanitation'), ('traceability', 'Traceability & Recall'), ('supplier_management', 'Supplier Management'), ('food_defense', 'Food Defense'), ('land_assessment', 'Land Assessment'), ('equipment_calibration', 'Equipment Calibration'), ('general', 'General')], default='general', max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('revision_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('review_due_date', models.DateField(help_text='Next mandatory review date')),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='controlled_documents/%Y/%m/')),
                ('content_text', models.TextField(blank=True, help_text='Plain text content for searchability')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('distribution_list', models.JSONField(blank=True, default=list, help_text='User IDs or role names')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_documents', to='api.company')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_prepared', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_reviewed', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='api.controlleddocument')),
            ],
            options={
                'verbose_name': 'Controlled Document',
                'ordering': ['document_number'],
            },
        ),
        migrations.CreateModel(
            name='LandHistoryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('land_use_history', models.JSONField(default=list, help_text='[{"year_start": 2019, "year_end": 2024, "land_use": "agriculture", "details": "...", "operator": "..."}]')),
                ('previous_pesticide_use', models.BooleanField(blank=True, null=True)),
                ('previous_chemical_storage', models.BooleanField(blank=True, null=True)),
                ('previous_waste_disposal', models.BooleanField(blank=True, null=True)),
                ('previous_mining', models.BooleanField(blank=True, null=True)),
                ('flood_zone', models.BooleanField(blank=True, null=True)),
                ('adjacent_contamination_risk', models.BooleanField(blank=True, null=True)),
                ('soil_testing_conducted', models.BooleanField(default=False)),
                ('soil_test_date', models.DateField(blank=True, null=True)),
                ('soil_test_results', models.JSONField(blank=True, default=dict, help_text='{"heavy_metals": "pass", "pH": 6.8, "contaminants": "none detected"}')),
                ('soil_test_passed', models.BooleanField(blank=True, null=True)),
                ('contamination_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown - Requires Investigation')], default='unknown', max_length=20)),
                ('risk_justification', models.TextField(blank=True)),
                ('mitigation_measures', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_assessments_approved', to=settings.AUTH_USER_MODEL)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_assessments_conducted', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_assessments', to='api.company')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_assessments', to='api.field')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.controlleddocument')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='InternalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_number', models.CharField(help_text='e.g., IA-2026-001', max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('audit_type', models.CharField(choices=[('internal', 'Internal Audit'), ('gap', 'GAP Audit Prep'), ('management_review', 'Management Review'), ('mock_audit', 'Mock Audit'), ('follow_up', 'Follow-Up Audit')], default='internal', max_length=30)),
                ('primus_modules_covered', models.JSONField(default=list, help_text='List of PRIMUS_MODULE_CHOICES values audited')),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('scope_description', models.TextField(blank=True)),
                ('auditor_name', models.CharField(blank=True, max_length=200)),
                ('audit_team', models.JSONField(blank=True, default=list, help_text='[{"name": "...", "role": "..."}]')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('executive_summary', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='audit_reports/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_audits', to='api.company')),
                ('farms_audited', models.ManyToManyField(blank=True, related_name='internal_audits', to='api.farm')),
                ('lead_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_led', to=settings.AUTH_USER_MODEL)),
                ('related_documents', models.ManyToManyField(blank=True, related_name='related_audits', to='api.controlleddocument')),
            ],
            options={
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('change_description', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('previous_file', models.FileField(blank=True, null=True, upload_to='document_revisions/%Y/%m/')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_history', to='api.controlleddocument')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(default='audit', help_text='audit, mock_recall, inspection, incident', max_length=50)),
                ('source_id', models.IntegerField(blank=True, help_text='ID of source object', null=True)),
                ('ca_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_steps', models.TextField(blank=True)),
                ('preventive_steps', models.TextField(blank=True)),
                ('assigned_to_name', models.CharField(blank=True, max_length=200)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('verified', 'Verified & Closed'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('implemented_date', models.DateField(blank=True, null=True)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('evidence_files', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='api.company')),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='api.auditfinding')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_corrective_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.internalaudit'),
        ),
        migrations.AddIndex(
            model_name='landhistoryassessment',
            index=models.Index(fields=['company', 'field'], name='idx_landassess_company_field'),
        ),
        migrations.AddIndex(
            model_name='landhistoryassessment',
            index=models.Index(fields=['contamination_risk'], name='idx_landassess_risk'),
        ),
        migrations.AddConstraint(
            model_name='landhistoryassessment',
            constraint=models.UniqueConstraint(fields=('field', 'assessment_date'), name='unique_land_assess_per_field_date'),
        ),
        migrations.AddIndex(
            model_name='internalaudit',
            index=models.Index(fields=['company', 'status'], name='idx_audit_company_status'),
        ),
        migrations.AddIndex(
            model_name='internalaudit',
            index=models.Index(fields=['company', '-planned_date'], name='idx_audit_company_date'),
        ),
        migrations.AddIndex(
            model_name='documentrevisionhistory',
            index=models.Index(fields=['document', '-changed_at'], name='idx_docrev_doc_date'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['company', 'status'], name='idx_ca_company_status'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['due_date', 'status'], name='idx_ca_due_status'),
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['company', 'status'], name='idx_cdoc_company_status'),
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['company', 'document_type'], name='idx_cdoc_company_type'),
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['company', 'primus_module'], name='idx_cdoc_company_module'),
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['review_due_date'], name='idx_cdoc_review_due'),
        ),
        migrations.AddConstraint(
            model_name='controlleddocument',
            constraint=models.UniqueConstraint(fields=('company', 'document_number', 'version'), name='unique_doc_version'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['audit', 'severity'], name='idx_finding_audit_sev'),
        ),
    ]
