# Generated by Django 4.2 on 2026-02-11 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_primusgfs_phase1_documents_audits_land'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=300)),
                ('supplier_code', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('material_types', models.JSONField(default=list, help_text='List of MATERIAL_TYPE_CHOICES values')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('conditional', 'Conditionally Approved'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='pending_approval', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('last_audit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_suppliers', to='api.company')),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='MockRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recall_number', models.CharField(max_length=50)),
                ('exercise_date', models.DateField()),
                ('scenario_description', models.TextField()),
                ('trigger_reason', models.CharField(help_text='e.g., Pathogen detection, Chemical contamination', max_length=200)),
                ('target_product', models.CharField(max_length=200)),
                ('target_lot_numbers', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed - Follow-Up Required')], default='planned', max_length=20)),
                ('trace_start_time', models.DateTimeField(blank=True, null=True)),
                ('trace_end_time', models.DateTimeField(blank=True, null=True)),
                ('trace_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('product_accounted_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lots_traced_forward', models.JSONField(blank=True, default=list, help_text='Buyers/destinations reached')),
                ('lots_traced_backward', models.JSONField(blank=True, default=list, help_text='Suppliers/fields traced back to')),
                ('effectiveness_score', models.DecimalField(blank=True, decimal_places=2, help_text='0-100', max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('participants', models.JSONField(blank=True, default=list, help_text='[{"name": "...", "role": "..."}]')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='mock_recalls/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_recalls', to='api.company')),
                ('led_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_recalls_led', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exercise_date'],
            },
        ),
        migrations.CreateModel(
            name='IncomingMaterialVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField()),
                ('material_type', models.CharField(choices=[('seed', 'Seeds/Seedlings'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('packaging', 'Packaging Material'), ('water_treatment', 'Water Treatment Chemical'), ('cleaning_chemical', 'Cleaning Chemical'), ('equipment', 'Equipment'), ('soil_amendment', 'Soil Amendment'), ('other', 'Other')], max_length=30)),
                ('material_description', models.CharField(max_length=300)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('condition_acceptable', models.BooleanField(null=True)),
                ('labeling_correct', models.BooleanField(null=True)),
                ('certificate_verified', models.BooleanField(null=True)),
                ('temperature_acceptable', models.BooleanField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_verifications', to='api.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_verifications', to='api.approvedsupplier')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='FoodDefensePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_year', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('review_date', models.DateField(help_text='Next mandatory review')),
                ('vulnerability_assessment', models.JSONField(default=list, help_text='[{"area": "...", "threat_type": "...", "likelihood": 1-5, "severity": 1-5, "risk_score": 1-25, "mitigation": "..."}]')),
                ('overall_threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('security_measures', models.JSONField(default=list, help_text='[{"measure": "...", "responsible_person": "...", "frequency": "...", "location": "..."}]')),
                ('perimeter_security', models.TextField(blank=True)),
                ('access_points', models.JSONField(blank=True, default=list)),
                ('key_control_procedure', models.TextField(blank=True)),
                ('food_defense_coordinator', models.CharField(blank=True, max_length=200)),
                ('emergency_contacts', models.JSONField(blank=True, default=list)),
                ('tampering_response_procedure', models.TextField(blank=True)),
                ('reporting_procedure', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_defense_plans', to='api.company')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.controlleddocument')),
            ],
            options={
                'ordering': ['-plan_year'],
            },
        ),
        migrations.CreateModel(
            name='FieldSanitationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('worker_count', models.IntegerField()),
                ('units_required', models.IntegerField(help_text='Auto-calculated: ceil(worker_count / 20)')),
                ('units_deployed', models.IntegerField()),
                ('hand_wash_stations', models.IntegerField(default=0)),
                ('soap_available', models.BooleanField(default=False)),
                ('paper_towels_available', models.BooleanField(default=False)),
                ('potable_water_available', models.BooleanField(default=False)),
                ('sanitizer_available', models.BooleanField(default=False)),
                ('units_clean', models.BooleanField(default=False)),
                ('service_needed', models.BooleanField(default=False)),
                ('service_requested_date', models.DateField(blank=True, null=True)),
                ('compliant', models.BooleanField(default=False)),
                ('deficiency_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanitation_logs', to='api.company')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanitation_logs', to='api.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanitation_logs', to='api.field')),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.AddIndex(
            model_name='mockrecall',
            index=models.Index(fields=['company', '-exercise_date'], name='idx_mockrecall_company_date'),
        ),
        migrations.AddIndex(
            model_name='mockrecall',
            index=models.Index(fields=['company', 'status'], name='idx_mockrecall_company_status'),
        ),
        migrations.AddIndex(
            model_name='incomingmaterialverification',
            index=models.Index(fields=['company', '-receipt_date'], name='idx_matverify_company_date'),
        ),
        migrations.AddIndex(
            model_name='incomingmaterialverification',
            index=models.Index(fields=['supplier', '-receipt_date'], name='idx_matverify_supplier_date'),
        ),
        migrations.AddIndex(
            model_name='fooddefenseplan',
            index=models.Index(fields=['company', '-plan_year'], name='idx_fooddef_company_year'),
        ),
        migrations.AddConstraint(
            model_name='fooddefenseplan',
            constraint=models.UniqueConstraint(fields=('company', 'plan_year'), name='unique_food_defense_per_year'),
        ),
        migrations.AddIndex(
            model_name='fieldsanitationlog',
            index=models.Index(fields=['company', '-log_date'], name='idx_sanitation_company_date'),
        ),
        migrations.AddIndex(
            model_name='fieldsanitationlog',
            index=models.Index(fields=['farm', '-log_date'], name='idx_sanitation_farm_date'),
        ),
        migrations.AddIndex(
            model_name='fieldsanitationlog',
            index=models.Index(fields=['compliant'], name='idx_sanitation_compliant'),
        ),
        migrations.AddIndex(
            model_name='approvedsupplier',
            index=models.Index(fields=['company', 'status'], name='idx_supplier_company_status'),
        ),
        migrations.AddIndex(
            model_name='approvedsupplier',
            index=models.Index(fields=['company', 'next_review_date'], name='idx_supplier_review_due'),
        ),
    ]
