# Generated by Django 4.2 on 2026-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_primusgfs_phase3_calibration_pest_preharvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='landhistoryassessment',
            name='animal_operation_details',
            field=models.TextField(blank=True, help_text='Type of animals, manure management, duration'),
        ),
        migrations.AddField(
            model_name='landhistoryassessment',
            name='buffer_period_adequate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landhistoryassessment',
            name='buffer_period_months',
            field=models.IntegerField(blank=True, help_text='Months between prior non-ag use cessation and current production', null=True),
        ),
        migrations.AddField(
            model_name='landhistoryassessment',
            name='information_source',
            field=models.CharField(blank=True, help_text='How land history was obtained (county records, owner interview, deed research, etc.)', max_length=200),
        ),
        migrations.AddField(
            model_name='landhistoryassessment',
            name='previous_animal_operations',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landhistoryassessment',
            name='remediation_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landhistoryassessment',
            name='remediation_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landhistoryassessment',
            name='remediation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landhistoryassessment',
            name='remediation_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landhistoryassessment',
            name='soil_test_lab',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='landhistoryassessment',
            name='soil_test_parameters_tested',
            field=models.JSONField(blank=True, default=list, help_text='["heavy_metals", "pH", "e_coli", "salmonella", "nitrates"]'),
        ),
    ]
