# Generated by Django 4.2 on 2026-02-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_land_history_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='landhistoryassessment',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload supporting evidence (soil test PDF, county record, deed photo, etc.)', null=True, upload_to='land_assessments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='landhistoryassessment',
            name='supporting_document_name',
            field=models.CharField(blank=True, help_text='Original filename of the uploaded document', max_length=255),
        ),
    ]
