# Generated by Django 4.2 on 2026-02-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_land_history_document_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfinding',
            name='finding_number',
            field=models.CharField(blank=True, help_text='Auto-generated if blank', max_length=20),
        ),
        migrations.AlterField(
            model_name='controlleddocument',
            name='document_number',
            field=models.CharField(blank=True, help_text='Auto-generated if blank, e.g., SOP-GAP-001', max_length=50),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='ca_number',
            field=models.CharField(blank=True, help_text='Auto-generated if blank, e.g., CA-001', max_length=50),
        ),
        migrations.AlterField(
            model_name='internalaudit',
            name='audit_number',
            field=models.CharField(blank=True, help_text='Auto-generated if blank, e.g., IA-2026-001', max_length=50),
        ),
        migrations.AlterField(
            model_name='mockrecall',
            name='recall_number',
            field=models.CharField(blank=True, help_text='Auto-generated if blank, e.g., MR-2026-001', max_length=50),
        ),
    ]
