# Generated by Django 4.2 on 2026-02-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_number_fields_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementdeduction',
            name='block_id',
            field=models.CharField(blank=True, default='', help_text='Block/grove ID this deduction belongs to (e.g., "002", "003"). Blank if not block-specific.', max_length=20),
        ),
        migrations.AddField(
            model_name='settlementgradeline',
            name='block_id',
            field=models.CharField(blank=True, default='', help_text='Block/grove ID this line belongs to (e.g., "002", "003"). Blank if no block breakdown.', max_length=20),
        ),
        migrations.AlterField(
            model_name='packinghousestatement',
            name='packinghouse_format',
            field=models.CharField(choices=[('vpoa', 'Villa Park Orchards (VPOA)'), ('sla', 'Saticoy Lemon Association (SLA)'), ('mission', 'Mission Produce'), ('generic', 'Generic/Other')], default='generic', help_text='Format/template used by packinghouse (auto-detected)', max_length=20),
        ),
    ]
