# Generated by Django 4.2 on 2026-02-13 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_create_tree_survey'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detectedtree',
            new_name='api_detecte_survey__2ce87c_idx',
            old_name='api_dettree_survey_idx',
        ),
        migrations.RenameIndex(
            model_name='detectedtree',
            new_name='api_detecte_health__e3dcf7_idx',
            old_name='api_dettree_health_idx',
        ),
        migrations.RenameIndex(
            model_name='detectedtree',
            new_name='api_detecte_latitud_a264e3_idx',
            old_name='api_dettree_latlon_idx',
        ),
        migrations.RenameIndex(
            model_name='treesurvey',
            new_name='api_treesur_company_6672df_idx',
            old_name='api_treesur_company_idx',
        ),
        migrations.RenameIndex(
            model_name='treesurvey',
            new_name='api_treesur_field_i_402f0e_idx',
            old_name='api_treesur_field_s_idx',
        ),
        migrations.RenameIndex(
            model_name='treesurvey',
            new_name='api_treesur_capture_009a93_idx',
            old_name='api_treesur_capture_idx',
        ),
    ]
