# Generated by Django 4.2 on 2026-02-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_add_block_id_and_mission_format'),
        ('api', '0067_rename_api_dettree_survey_idx_api_detecte_survey__2ce87c_idx_and_more'),
    ]

    operations = [
    ]
