# Generated by Django 4.2 on 2026-02-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_merge_20260218_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditBinderInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. '2026 Pre-Season Audit Binder'", max_length=200)),
                ('season_year', models.IntegerField(help_text='Audit season year')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ready', 'Ready for Audit'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('generated_pdf', models.FileField(blank=True, help_text='Final assembled PDF for audit', null=True, upload_to='audit_binders/generated/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_binder_instances', to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_binders', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, help_text='Optional: scope binder to a specific farm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_binders', to='api.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.IntegerField(help_text='Document number (1-39) in the CAC manual')),
                ('title', models.CharField(max_length=200)),
                ('section_group', models.CharField(choices=[('management', 'Food Safety Management System'), ('field_sanitation', 'Field Sanitation & Hygiene'), ('agricultural_inputs', 'Agricultural Inputs'), ('worker_health', 'Worker Health, Hygiene & Training'), ('training', 'Training'), ('audit_checklists', 'Audit Checklists'), ('risk_assessment', 'Risk Assessment')], max_length=30)),
                ('doc_type', models.CharField(choices=[('auto_fill', 'Auto-Fill from System Data'), ('partial_fill', 'Partial Auto-Fill'), ('sop', 'Standard Operating Procedure'), ('blank_template', 'Blank On-Site Template'), ('reference', 'Static Reference Material')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=20)),
                ('sop_content', models.TextField(blank=True, help_text='Rich text content for SOP/policy documents')),
                ('auto_fill_source', models.CharField(blank=True, help_text='Registry key for auto-fill data source', max_length=50)),
                ('auto_fill_data', models.JSONField(blank=True, help_text='Cached auto-fill data from system models', null=True)),
                ('manual_overrides', models.JSONField(blank=True, help_text='User edits on top of auto-filled data', null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('binder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.auditbinderinstance')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_binder_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_number'],
            },
        ),
        migrations.CreateModel(
            name='CACBinderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Template version, e.g. '5.0'", max_length=20)),
                ('name', models.CharField(help_text="e.g. 'CAC Food Safety Manual Version 5'", max_length=200)),
                ('pdf_file', models.FileField(blank=True, help_text='The fillable PDF template file', null=True, upload_to='cac_templates/')),
                ('section_definitions', models.JSONField(default=list, help_text='List of section defs: [{doc_number, title, section_group, doc_type, auto_fill_source}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_binder_templates', to='api.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinderSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audit_binders/supporting/')),
                ('file_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='api.bindersection')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_binder_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditbinderinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='api.cacbindertemplate'),
        ),
        migrations.AddIndex(
            model_name='cacbindertemplate',
            index=models.Index(fields=['company', 'is_active'], name='api_cacbind_company_a5cd37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bindersection',
            unique_together={('binder', 'doc_number')},
        ),
        migrations.AddIndex(
            model_name='auditbinderinstance',
            index=models.Index(fields=['company', 'status'], name='api_auditbi_company_ac50fb_idx'),
        ),
    ]
