# Generated by Django 4.2 on 2026-02-19 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_correctiveaction_is_nuoca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CACDocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(help_text="CAC document number, e.g., '01', '04', '09A'", max_length=10)),
                ('page_number', models.IntegerField(help_text='PDF page number where signature appears')),
                ('signer_role', models.CharField(choices=[('coordinator', 'Food Safety Coordinator'), ('owner', 'Owner / Grower'), ('reviewer', 'Reviewer'), ('assessor', 'Assessor'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('attendee', 'Attendee')], max_length=50)),
                ('signer_name', models.CharField(max_length=200)),
                ('signer_order', models.IntegerField(default=0, help_text='Order for multi-signature pages (e.g., attendee 1, 2, 3)')),
                ('signed', models.BooleanField(default=False)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 PNG, copied from UserSignature at signing time')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('season_year', models.IntegerField()),
                ('source_model', models.CharField(blank=True, help_text="e.g., 'FoodSafetyCommitteeMeeting', 'MockRecall'", max_length=100)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_signatures', to='api.company')),
                ('signer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_number', 'page_number', 'signer_order'],
            },
        ),
        migrations.AddIndex(
            model_name='cacdocumentsignature',
            index=models.Index(fields=['company', 'season_year', 'doc_number'], name='idx_cacsig_company_year_doc'),
        ),
    ]
