# Generated by Django 4.2 on 2026-02-22 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_add_cac_document_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOISubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_application_date', models.DateField(help_text='Planned date of application')),
                ('planned_acres', models.DecimalField(blank=True, decimal_places=2, help_text='Planned acres to treat', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted to County'), ('confirmed', 'Confirmed/Approved by County'), ('denied', 'Denied by County'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('county', models.CharField(help_text='County Agricultural Commissioner office', max_length=100)),
                ('filed_date', models.DateField(blank=True, help_text='Date NOI was filed with county', null=True)),
                ('confirmation_number', models.CharField(blank=True, help_text='County confirmation/permit number', max_length=100)),
                ('submission_method', models.CharField(blank=True, help_text='How submitted (CalAgPermits, fax, in-person, email)', max_length=50)),
                ('county_response_date', models.DateField(blank=True, null=True)),
                ('county_response_notes', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True, help_text='Any conditions imposed by the county')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noi_submissions', to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noi_submissions', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noi_submissions', to='api.field')),
                ('pesticide_application', models.ForeignKey(blank=True, help_text='The application this NOI covers (may be set after application)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noi_submissions', to='api.pesticideapplication')),
                ('product', models.ForeignKey(help_text='Restricted use product requiring NOI', on_delete=django.db.models.deletion.CASCADE, related_name='noi_submissions', to='api.pesticideproduct')),
            ],
            options={
                'verbose_name': 'NOI Submission',
                'verbose_name_plural': 'NOI Submissions',
                'ordering': ['-planned_application_date'],
            },
        ),
        migrations.AddIndex(
            model_name='noisubmission',
            index=models.Index(fields=['company', 'status'], name='idx_noi_company_status'),
        ),
        migrations.AddIndex(
            model_name='noisubmission',
            index=models.Index(fields=['field', 'planned_application_date'], name='idx_noi_field_date'),
        ),
    ]
