# Generated by Django 4.2 on 2026-02-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_add_noi_submission_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceprofile',
            name='deadlines_auto_populated',
            field=models.BooleanField(default=False, help_text='True after deadlines have been auto-generated on first dashboard visit'),
        ),
    ]
