# Generated by Django 4.2 on 2026-02-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_add_deadlines_auto_populated_to_compliance_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditbinder',
            name='include_primus_audits',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditbinder',
            name='include_primus_findings',
            field=models.BooleanField(default=True),
        ),
    ]
