# Generated by Django 4.2 on 2026-02-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_cac_audit_binder'),
        ('api', '0073_add_primus_sections_to_audit_binder'),
    ]

    operations = [
    ]
