# Generated by Django 4.2 on 2026-02-24 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_bindersection_pdf_field_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_number', models.CharField(blank=True, help_text="TELUS/County PUR ID, e.g., '833-15766184'", max_length=50)),
                ('pur_status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to County'), ('unsent', 'Unsent'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('recommendation_number', models.CharField(blank=True, help_text="PCA recommendation number, e.g., 'REC9307633'", max_length=50)),
                ('county', models.CharField(default='Ventura', max_length=50)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('township', models.CharField(blank=True, max_length=10)),
                ('range_field', models.CharField(blank=True, db_column='range', max_length=10)),
                ('baseline', models.CharField(blank=True, default='S', max_length=5)),
                ('permit_number', models.CharField(blank=True, help_text="e.g., '56P0049'", max_length=20)),
                ('site_id', models.CharField(blank=True, help_text="Ag Commissioner site ID, e.g., 'FINCH FARMS, LLC 02C'", max_length=100)),
                ('date_started', models.DateTimeField(help_text='Application start date/time')),
                ('date_completed', models.DateTimeField(blank=True, help_text='Application end date/time', null=True)),
                ('planted_area_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('treated_area_acres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commodity_name', models.CharField(blank=True, help_text="e.g., 'LEMON'", max_length=100)),
                ('commodity_code', models.CharField(blank=True, help_text="DPR code, e.g., '2004-00'", max_length=20)),
                ('application_method', models.CharField(choices=[('ground', 'Ground'), ('air', 'Air (Aerial)'), ('chemigation', 'Chemigation'), ('hand', 'Hand Application'), ('other', 'Other')], default='ground', max_length=20)),
                ('dilution_gallons', models.DecimalField(blank=True, decimal_places=1, help_text='Total spray volume per acre in gallons', max_digits=8, null=True)),
                ('wind_direction_degrees', models.IntegerField(blank=True, null=True)),
                ('wind_velocity_mph', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temperature_start_f', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temperature_finish_f', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('rei_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum REI across all products in tank mix', max_digits=6, null=True)),
                ('phi_days', models.IntegerField(blank=True, help_text='Maximum PHI across all products in tank mix', null=True)),
                ('applied_by', models.CharField(blank=True, help_text="Person who applied, e.g., 'Ag Rx/Armando'", max_length=200)),
                ('supervised_by', models.CharField(blank=True, max_length=200)),
                ('is_nursery', models.BooleanField(default=False)),
                ('is_organic', models.BooleanField(default=False)),
                ('is_pre_plant', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('restrictions', models.TextField(blank=True, help_text='Label restrictions noted on PUR')),
                ('imported_from', models.CharField(blank=True, help_text="Source: 'telus_pdf', 'manual', 'csv'", max_length=50)),
                ('import_batch_id', models.CharField(blank=True, help_text='Batch ID for grouped imports', max_length=100)),
                ('source_pdf_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_started'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('pesticide', 'Pesticide'), ('fertilizer', 'Fertilizer'), ('adjuvant', 'Adjuvant / Surfactant'), ('growth_regulator', 'Plant Growth Regulator'), ('biological', 'Biological'), ('other', 'Other')], default='pesticide', max_length=20)),
                ('product_name', models.CharField(max_length=300)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('epa_registration_number', models.CharField(blank=True, help_text="EPA reg number with state suffix, e.g., '71058-5-ZA'. Empty for fertilizers.", max_length=50)),
                ('active_ingredients', models.JSONField(blank=True, default=list, help_text='List of {name, percent} objects')),
                ('active_ingredient', models.CharField(blank=True, help_text='Primary active ingredient name', max_length=200)),
                ('active_ingredient_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('restricted_use', models.BooleanField(default=False)),
                ('signal_word', models.CharField(blank=True, choices=[('DANGER', 'Danger'), ('WARNING', 'Warning'), ('CAUTION', 'Caution'), ('NONE', 'None')], max_length=20)),
                ('phi_days', models.IntegerField(blank=True, help_text='Pre-Harvest Interval in days', null=True)),
                ('rei_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Re-Entry Interval in hours', max_digits=6, null=True)),
                ('formulation_code', models.CharField(blank=True, help_text='EC, WP, SC, WDG, G, etc.', max_length=10)),
                ('n_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('k_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_organic_approved', models.BooleanField(default=False)),
                ('label_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Null = system/global product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.company')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='dpr_commodity_code',
            field=models.CharField(blank=True, help_text="California DPR commodity code, e.g., '2004-00' for lemon", max_length=20),
        ),
        migrations.AddField(
            model_name='field',
            name='pur_site_id',
            field=models.CharField(blank=True, help_text="Ag Commissioner site ID for PUR matching, e.g., 'FINCH FARMS, LLC 02C'", max_length=100),
        ),
        migrations.CreateModel(
            name='TankMixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=3, help_text='Total product used for this application', max_digits=12)),
                ('amount_unit', models.CharField(choices=[('Ga', 'Gallons'), ('Floz', 'Fluid Ounces'), ('Qt', 'Quarts'), ('Pt', 'Pints'), ('Lb', 'Pounds'), ('Oz', 'Ounces')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Rate per acre', max_digits=10)),
                ('rate_unit', models.CharField(choices=[('Ga/A', 'Gallons per Acre'), ('Floz/A', 'Fluid Ounces per Acre'), ('Qt/A', 'Quarts per Acre'), ('Pt/A', 'Pints per Acre'), ('Lb/A', 'Pounds per Acre'), ('Oz/A', 'Ounces per Acre')], max_length=10)),
                ('dilution_gallons', models.DecimalField(blank=True, decimal_places=1, help_text='Spray solution volume in gallons (e.g., 500, 250, 75)', max_digits=8, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('application_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_mix_items', to='api.applicationevent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tank_mix_uses', to='api.product')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Applicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Business name, e.g., 'Ag Rx', 'Hansen Pest Control'", max_length=200)),
                ('applicator_type', models.CharField(choices=[('pco', 'Pest Control Operator (PCO)'), ('pca', 'Pest Control Advisor (PCA)'), ('grower', 'Grower-Applicator'), ('aerial', 'Aerial Applicator')], default='pco', max_length=20)),
                ('applicator_id', models.CharField(blank=True, help_text="County applicator ID number, e.g., '30889'", max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicators', to='api.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='applicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_events', to='api.applicator'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_events', to='api.company'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_events', to='api.field'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['epa_registration_number'], name='api_product_epa_reg_6689d5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='api_product_product_ba7a03_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='api_product_is_acti_b97ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['pur_number'], name='api_applica_pur_num_904031_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['date_started'], name='api_applica_date_st_110570_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['pur_status'], name='api_applica_pur_sta_0d2bdf_idx'),
        ),
    ]
