# Generated by Django 4.2 on 2026-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_purimportbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='boundary_geojson',
            field=models.JSONField(blank=True, help_text='Farm boundary polygon in GeoJSON format', null=True, verbose_name='Boundary GeoJSON'),
        ),
        migrations.AddField(
            model_name='farm',
            name='calculated_acres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acreage calculated from drawn boundary', max_digits=10, null=True, verbose_name='Calculated Acres'),
        ),
    ]
