# Generated by Django 4.2 on 2026-04-12 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_add_farm_boundary_fields'),
        ('api', '0080_fsma_rule204_traceability'),
    ]

    operations = [
    ]
