# Generated by Django 4.2 on 2026-04-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_merge_20260412_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticideproduct',
            name='cost_unit',
            field=models.CharField(blank=True, choices=[('gal', 'Gallons'), ('lbs', 'Pounds'), ('oz', 'Ounces'), ('pt', 'Pints'), ('qt', 'Quarts')], help_text='Unit of measure for cost_per_unit (must match application unit to auto-compute cost)', max_length=20),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='moa_code',
            field=models.CharField(blank=True, db_index=True, help_text="IRAC/FRAC/HRAC mode-of-action code (e.g. 'IRAC-4A', 'FRAC-11', 'HRAC-9')", max_length=20),
        ),
        migrations.AddField(
            model_name='pesticideproduct',
            name='moa_group_name',
            field=models.CharField(blank=True, help_text="Human-readable MOA group (e.g. 'Neonicotinoids', 'Strobilurins', 'EPSP synthase inhibitors')", max_length=120),
        ),
    ]
