# Generated by Django 4.2 on 2026-04-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_add_moa_and_cost_unit_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dollar cost per unit (unit defined by cost_unit)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_unit',
            field=models.CharField(blank=True, help_text='Unit of measure for cost_per_unit (Lb, Oz, Ga, Qt, Pt, Fl Oz, Kg, L)', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='moa_code',
            field=models.CharField(blank=True, db_index=True, help_text="IRAC/FRAC/HRAC mode-of-action code (e.g. 'IRAC-4A', 'FRAC-11', 'HRAC-9')", max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='moa_group_name',
            field=models.CharField(blank=True, help_text="Human-readable MOA group (e.g. 'Neonicotinoids', 'Strobilurins')", max_length=120),
        ),
    ]
