# Generated by Django 5.2.16 on 2026-07-30 18:25
#
# Increment 0 — the foundation the Finch operations work sits on:
#   * LegalEntity + Farm.owning_entity / finch_ownership_pct
#   * Field acreage provenance (acres_source / acres_confidence / acres_as_of)
#   * RanchCropAcreage — the shared per-acre denominator
#   * WellReading.af_source / is_billing_row / billing_period_start
#
# It also stamps af_source on existing readings, which is the part that matters
# most: without it the new save() guard would not protect a single row already
# in production. See mark_imported_readings_as_agency_billed below.

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def mark_imported_readings_as_agency_billed(apps, schema_editor):
    """Protect readings whose acre-feet came from the water agency.

    WellReading.save() recomputes extraction_acre_feet from the meter delta.
    That is correct for a reading someone types in, and destructive for one
    loaded from an agency spreadsheet: the registers behind those figures are
    not in acre-feet (x0.001, x0.01, gallons, or cubic-feet x10 depending on
    the well) and they roll at 1,000,000. Recomputing Saticoy FIN0010's
    2025-12-31 row turns the billed 59.14 AF into 18,386 AF.

    Fingerprint: loaddata writes through DeserializedObject.save(), which calls
    save_base() and never runs the model's save(). So a reading that has an
    extraction figure but no previous_reading was loaded from a fixture or an
    importer and still carries its source value. A reading with previous_reading
    set went through save() and is already meter-derived by definition.

    On the production database this stamps all 343 readings (every one has
    previous_reading NULL) as agency_billed.
    """
    WellReading = apps.get_model('api', 'WellReading')
    WellReading.objects.filter(
        previous_reading__isnull=True,
        extraction_acre_feet__isnull=False,
    ).update(af_source='agency_billed')


def unmark_agency_billed(apps, schema_editor):
    """Reverse: put everything back to the field default."""
    WellReading = apps.get_model('api', 'WellReading')
    WellReading.objects.update(af_source='meter_derived')


def add_rls_policies(apps, schema_editor):
    """Row-level security for the two new tables.

    RLS is Postgres-only defence in depth; the Django-level company filtering
    is the primary control and is what the test suite asserts. Skipping on
    other vendors keeps the SQLite dev and test paths working — same guard as
    0077_pur_rls_policies.
    """
    if schema_editor.connection.vendor != 'postgresql':
        return

    statements = [
        # LegalEntity — direct company_id.
        """
        ALTER TABLE api_legalentity ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS tenant_isolation ON api_legalentity;
        CREATE POLICY tenant_isolation ON api_legalentity
            FOR ALL
            USING (company_id::text = current_setting('app.current_company_id', true));
        """,
        # RanchCropAcreage — company reached through farm.
        """
        ALTER TABLE api_ranchcropacreage ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS tenant_isolation ON api_ranchcropacreage;
        CREATE POLICY tenant_isolation ON api_ranchcropacreage
            FOR ALL
            USING (
                farm_id IN (
                    SELECT id FROM api_farm
                    WHERE company_id::text = current_setting('app.current_company_id', true)
                )
            );
        """,
    ]
    for sql in statements:
        schema_editor.execute(sql)


def drop_rls_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table in ('api_legalentity', 'api_ranchcropacreage'):
        schema_editor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
        schema_editor.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_rei_posting_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='finch_ownership_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text="Family ownership share as a fraction, e.g. 0.9000 for 90%. Used to present an owner's-share view alongside 100% gross. Per-ACRE and per-unit metrics are never scaled by this — a share of the income is still earned on the whole acre.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='field',
            name='acres_as_of',
            field=models.DateField(blank=True, help_text='Date the acreage figure was established', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='acres_confidence',
            field=models.CharField(choices=[('surveyed', 'Surveyed / legally described'), ('statement', 'Derived from packinghouse statement'), ('pnl', 'From the ranch P&L acreage tab'), ('even_split', 'Ranch acreage divided evenly across blocks'), ('placeholder', 'Placeholder — not a real measurement')], db_index=True, default='placeholder', help_text='How much weight total_acres can carry', max_length=20),
        ),
        migrations.AddField(
            model_name='field',
            name='acres_source',
            field=models.CharField(blank=True, help_text="Specific origin, e.g. 'V6.17 Setup - Acreage' or 'SLA pool statement 2025'", max_length=200),
        ),
        migrations.AddField(
            model_name='wellreading',
            name='af_source',
            field=models.CharField(choices=[('agency_billed', 'Agency-billed (authoritative — never recomputed)'), ('meter_derived', 'Derived from meter delta'), ('estimated', 'Estimated')], db_index=True, default='meter_derived', help_text="Where extraction_acre_feet came from. 'agency_billed' figures are authoritative and are never recomputed from the meter delta.", max_length=20),
        ),
        migrations.AddField(
            model_name='wellreading',
            name='billing_period_start',
            field=models.DateField(blank=True, help_text='First day covered by this billing row (null if unknown)', null=True),
        ),
        migrations.AddField(
            model_name='wellreading',
            name='is_billing_row',
            field=models.BooleanField(db_index=True, default=True, help_text='True if this reading closes a billing period and its extraction may be summed into period totals. False for interim reads whose usage is already contained in a later billing row.'),
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Thacher Creek LLC'", max_length=200)),
                ('short_code', models.CharField(help_text="Short code used in workbooks and QuickBooks, e.g. 'TCC'", max_length=20)),
                ('entity_type', models.CharField(choices=[('llc', 'LLC'), ('trust', 'Trust'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('individual', 'Individual'), ('other', 'Other')], default='llc', max_length=20)),
                ('qb_file_name', models.CharField(blank=True, help_text="QuickBooks company file this entity's books live in", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='api.company')),
            ],
            options={
                'verbose_name_plural': 'legal entities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='owning_entity',
            field=models.ForeignKey(blank=True, help_text='Legal entity holding title to this ranch (its QuickBooks file)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='api.legalentity'),
        ),
        migrations.CreateModel(
            name='RanchCropAcreage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_code', models.CharField(choices=[('lemons', 'Lemons'), ('avocados', 'Avocados'), ('valencias', 'Valencias'), ('mandarins', 'Mandarins'), ('pixies', 'Pixies'), ('navels', 'Navels'), ('cara_cara', 'Cara Cara'), ('other_fruit', 'Other Fruit'), ('grazing', 'Grazing / non-orchard')], max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('bearing_acres', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Acres in production — the denominator for yield and revenue rates', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('non_bearing_acres', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Planted but not yet producing (development acreage)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('grazing_acres', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Non-orchard ground. Takes no irrigation water.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('source', models.CharField(choices=[('pnl_setup_acreage', 'Ranch P&L — Setup - Acreage tab'), ('plantings', 'Block plantings schedule'), ('statement', 'Packinghouse statement derived'), ('surveyed', 'Surveyed / legally described'), ('estimated', 'Estimated')], default='pnl_setup_acreage', max_length=30)),
                ('is_superseded', models.BooleanField(db_index=True, default=False, help_text='True when a better figure has replaced this one. Superseded rows are kept so a published number can still be traced to what it was computed against, but they are excluded from every roll-up.')),
                ('note', models.TextField(blank=True, help_text='Why this figure is what it is, especially where sources conflict')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_acreage', to='api.farm')),
            ],
            options={
                'verbose_name': 'ranch crop acreage',
                'verbose_name_plural': 'ranch crop acreage',
                'ordering': ['farm__name', 'crop_code', '-year'],
            },
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.UniqueConstraint(fields=('company', 'short_code'), name='uniq_legalentity_company_shortcode'),
        ),
        migrations.AddIndex(
            model_name='ranchcropacreage',
            index=models.Index(fields=['farm', 'year'], name='api_ranchcr_farm_id_f5d2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='ranchcropacreage',
            index=models.Index(fields=['year', 'crop_code'], name='api_ranchcr_year_4654b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='ranchcropacreage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_superseded', False)), fields=('farm', 'crop_code', 'year'), name='uniq_active_ranch_crop_year_acreage'),
        ),
        migrations.RunPython(
            mark_imported_readings_as_agency_billed,
            unmark_agency_billed,
        ),
        migrations.RunPython(
            add_rls_policies,
            drop_rls_policies,
        ),
    ]
