# Generated by Django 5.2.16 on 2026-07-30 18:53
#
# Block report card storage. The grades are imported from the scoring engine,
# never computed here — see api/models/block_scoring.py for why.

import django.db.models.deletion
from django.db import migrations, models

# Tables reaching company through their snapshot.
_VIA_SNAPSHOT = (
    'api_blockscorecard',
    'api_blockseasonmetric',
    'api_blockscoregate',
    'api_blockscorebenchmark',
    'api_blockevidenceref',
)


def add_rls_policies(apps, schema_editor):
    """Postgres-only defence in depth, matching 0077 and 0085."""
    if schema_editor.connection.vendor != 'postgresql':
        return

    for table in ('api_blockscoresnapshot', 'api_scoringunit'):
        schema_editor.execute(f"""
            ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON {table};
            CREATE POLICY tenant_isolation ON {table}
                FOR ALL
                USING (company_id::text = current_setting('app.current_company_id', true));
        """)

    for table in _VIA_SNAPSHOT:
        schema_editor.execute(f"""
            ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON {table};
            CREATE POLICY tenant_isolation ON {table}
                FOR ALL
                USING (
                    snapshot_id IN (
                        SELECT id FROM api_blockscoresnapshot
                        WHERE company_id::text = current_setting('app.current_company_id', true)
                    )
                );
        """)


def drop_rls_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table in ('api_blockscoresnapshot', 'api_scoringunit') + _VIA_SNAPSHOT:
        schema_editor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
        schema_editor.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_finch_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('engine_version', models.CharField(blank=True, max_length=50)),
                ('bundle_generated_at', models.DateTimeField(blank=True, help_text='When the exporting side built this bundle', null=True)),
                ('pack_db_sha256', models.CharField(blank=True, help_text='Hash of the source database, so a card traces to an exact build', max_length=64)),
                ('verify_checks_passed', models.PositiveSmallIntegerField(default=0)),
                ('verify_checks_total', models.PositiveSmallIntegerField(default=0)),
                ('forced', models.BooleanField(default=False, help_text='Imported despite failing verification. Badge every figure.')),
                ('grade_window_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_window_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('trend_window_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('trend_window_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Only one snapshot is published at a time; it is what the UI shows')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_score_snapshots', to='api.company')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockScoreBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(max_length=16)),
                ('parameter', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('source', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, help_text='LOCKED / VERIFIED / DEFAULT / REFERENCE / NOTE / PLACEHOLDER', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='api.blockscoresnapshot')),
            ],
            options={
                'ordering': ['factor', 'parameter'],
            },
        ),
        migrations.CreateModel(
            name='ScoringUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Engine unit id, {RANCH3}-{CROP}-{Block}', max_length=64)),
                ('display_name', models.CharField(blank=True, help_text="e.g. 'Saticoy · Block 1B'", max_length=200)),
                ('ranch_code', models.CharField(blank=True, max_length=8)),
                ('crop_code', models.CharField(blank=True, max_length=8)),
                ('block_label', models.CharField(blank=True, max_length=64)),
                ('mapping_confirmed', models.BooleanField(default=False, help_text='A person confirmed this unit is that Field. Imports never overwrite a confirmed mapping.')),
                ('is_active', models.BooleanField(default=True)),
                ('first_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_units', to='api.company')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_units', to='api.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_units', to='api.field')),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
        migrations.CreateModel(
            name='BlockSeasonMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField()),
                ('packed_cartons', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('cartons_per_acre', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('pct_of_standard', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('pool_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('revenue_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('season_standard_rev_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fresh_packout_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('avg_size', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('money_size_share_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('timing_score', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('pick_rounds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pick_months', models.CharField(blank=True, max_length=120)),
                ('revenue_note', models.CharField(blank=True, help_text='Non-empty means the revenue figure did NOT come from a reconciled charge tail', max_length=200)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_metrics', to='api.blockscoresnapshot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_metrics', to='api.scoringunit')),
            ],
            options={
                'ordering': ['unit__uid', 'season'],
            },
        ),
        migrations.CreateModel(
            name='BlockScoreGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscore', models.CharField(help_text='P1..P5, PERF, or a sub-factor like P3a', max_length=8)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('value_basis', models.CharField(blank=True, max_length=200)),
                ('gate_reason', models.TextField(blank=True, help_text='Verbatim from the engine. Never rewritten.')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='api.blockscoresnapshot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='api.scoringunit')),
            ],
            options={
                'ordering': ['unit__uid', 'subscore'],
            },
        ),
        migrations.CreateModel(
            name='BlockScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.CharField(blank=True, help_text="Letter with +/-, e.g. 'A−', 'B+'", max_length=3)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('grades_on_file', models.PositiveSmallIntegerField(default=0, help_text='How many of the five graded — the GPA denominator')),
                ('acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acres_basis', models.CharField(blank=True, help_text='What acreage the grades were computed against, frozen at import', max_length=200)),
                ('yield_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('yield_ctn_ac', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('yield_pct_of_standard', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('revenue_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('revenue_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('revenue_pct_of_standard', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('fresh_packout_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('quality_trend_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('quality_trend_pts_yr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('size_trend_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('money_share_trend_pts_yr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg_size', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('money_size_share_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('avg_size_drift_counts_yr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('timing_score', models.DecimalField(blank=True, decimal_places=1, help_text="Volume-weighted value of the block's pick months (100 = season average)", max_digits=6, null=True)),
                ('peak_share_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('strong_share_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('soft_share_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('flush_share_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('picks_per_season', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('note', models.TextField(blank=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='api.blockscoresnapshot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='api.scoringunit')),
            ],
            options={
                'ordering': ['-gpa', 'unit__uid'],
            },
        ),
        migrations.CreateModel(
            name='BlockEvidenceRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(help_text='Engine document id')),
                ('family', models.CharField(blank=True, help_text='pool / wash / pick', max_length=24)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relpath', models.CharField(blank=True, max_length=500)),
                ('page_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('canonical', models.BooleanField(default=True)),
                ('needs_review', models.BooleanField(db_index=True, default=False, help_text="Counted deliberately, but flagged by the engine's reconciliation")),
                ('cartons', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('statement', models.ForeignKey(blank=True, help_text='Future seam: links a citation to a statement held in the platform', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_evidence', to='api.packinghousestatement')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='api.blockscoresnapshot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='api.scoringunit')),
            ],
            options={
                'ordering': ['unit__uid', '-year', 'doc_id'],
            },
        ),
        migrations.AddIndex(
            model_name='blockscoresnapshot',
            index=models.Index(fields=['company', '-imported_at'], name='api_blocksc_company_170c99_idx'),
        ),
        migrations.AddConstraint(
            model_name='blockscorebenchmark',
            constraint=models.UniqueConstraint(fields=('snapshot', 'factor', 'parameter'), name='uniq_benchmark_snapshot_factor_parameter'),
        ),
        migrations.AddConstraint(
            model_name='scoringunit',
            constraint=models.UniqueConstraint(fields=('company', 'uid'), name='uniq_scoring_unit_company_uid'),
        ),
        migrations.AddIndex(
            model_name='blockseasonmetric',
            index=models.Index(fields=['snapshot', 'season'], name='api_blockse_snapsho_bd75b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='blockseasonmetric',
            constraint=models.UniqueConstraint(fields=('snapshot', 'unit', 'season'), name='uniq_season_metric_snapshot_unit_season'),
        ),
        migrations.AddIndex(
            model_name='blockscoregate',
            index=models.Index(fields=['snapshot', 'subscore'], name='api_blocksc_snapsho_0b6672_idx'),
        ),
        migrations.AddConstraint(
            model_name='blockscoregate',
            constraint=models.UniqueConstraint(fields=('snapshot', 'unit', 'subscore'), name='uniq_gate_snapshot_unit_subscore'),
        ),
        migrations.AddIndex(
            model_name='blockscorecard',
            index=models.Index(fields=['snapshot', '-gpa'], name='api_blocksc_snapsho_4cd080_idx'),
        ),
        migrations.AddConstraint(
            model_name='blockscorecard',
            constraint=models.UniqueConstraint(fields=('snapshot', 'unit'), name='uniq_scorecard_snapshot_unit'),
        ),
        migrations.AddIndex(
            model_name='blockevidenceref',
            index=models.Index(fields=['snapshot', 'unit'], name='api_blockev_snapsho_eba03c_idx'),
        ),
        migrations.AddIndex(
            model_name='blockevidenceref',
            index=models.Index(fields=['snapshot', 'needs_review'], name='api_blockev_snapsho_ba2d64_idx'),
        ),
        migrations.RunPython(
            add_rls_policies,
            drop_rls_policies,
        ),
    ]
