# Generated by Django 5.2.16 on 2026-07-30 20:14
#
# Pick & haul storage: sync-owned receipts/charges/pulls pushed from the local
# pipeline, platform-owned invoices/manual picks entered by the accountant.
# See api/models/pickhaul.py for the ownership rules.

import django.db.models.deletion
import django.db.models.functions.comparison
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

# Tables carrying a direct company_id.
_DIRECT_COMPANY = (
    'api_machineapitoken',
    'api_pickhaulsyncbatch',
    'api_pickhaulpull',
    'api_pickhaulreceipt',
    'api_pickhauldirectcharge',
    'api_pickhaulinvoice',
    'api_pickhaulmanualpick',
    'api_pickhaulcheckresult',
)

# Tables reaching company through their invoice.
_VIA_INVOICE = (
    'api_pickhaulinvoicereceipt',
    'api_pickhaulchargematch',
)


def add_rls_policies(apps, schema_editor):
    """Postgres-only defence in depth, matching 0077 / 0085 / 0086."""
    if schema_editor.connection.vendor != 'postgresql':
        return

    for table in _DIRECT_COMPANY:
        schema_editor.execute(f"""
            ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON {table};
            CREATE POLICY tenant_isolation ON {table}
                FOR ALL
                USING (company_id::text = current_setting('app.current_company_id', true));
        """)

    for table in _VIA_INVOICE:
        schema_editor.execute(f"""
            ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON {table};
            CREATE POLICY tenant_isolation ON {table}
                FOR ALL
                USING (
                    invoice_id IN (
                        SELECT id FROM api_pickhaulinvoice
                        WHERE company_id::text = current_setting('app.current_company_id', true)
                    )
                );
        """)


def drop_rls_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table in _DIRECT_COMPANY + _VIA_INVOICE:
        schema_editor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
        schema_editor.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_block_scoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(default='pickhaul:push', max_length=50)),
                ('token_prefix', models.CharField(db_index=True, help_text="First characters of the secret, e.g. 'pht_ab12cd34' — safe to display", max_length=12)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_tokens', to='api.company')),
                ('user', models.ForeignKey(help_text='Service account this token authenticates as', on_delete=django.db.models.deletion.PROTECT, related_name='machine_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickHaulDirectCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField()),
                ('pool', models.CharField(blank=True, max_length=100)),
                ('block_raw', models.CharField(blank=True, max_length=200)),
                ('charge_date', models.DateField(blank=True, null=True)),
                ('charge_date_raw', models.CharField(blank=True, max_length=40)),
                ('charge_desc', models.CharField(blank=True, help_text="As printed: 'PICKING CHARGES' / 'HAULING-GWR ADV' / …", max_length=100)),
                ('kind', models.CharField(choices=[('PICK', 'Pick'), ('HAUL', 'Haul'), ('OTHER', 'Other')], max_length=8)),
                ('txn_desc', models.CharField(blank=True, max_length=200)),
                ('ap_reference', models.CharField(blank=True, help_text="e.g. 'APM-SL-00500'", max_length=50)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickhaul_charges', to='api.company')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickhaul_charges', to='api.legalentity')),
                ('packinghouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickhaul_charges', to='api.packinghouse')),
            ],
            options={
                'ordering': ['charge_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PickHaulInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('PICK', 'Pick'), ('HAUL', 'Haul')], max_length=8)),
                ('contractor', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('block_raw', models.CharField(blank=True, max_length=200)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('date_emailed', models.DateField(blank=True, null=True)),
                ('date_rec_from_ph', models.DateField(blank=True, help_text='When WE received the money. Human record only; nothing derives it.', null=True)),
                ('charge_posted', models.DateField(blank=True, help_text='When the HOUSE posted the charge. Written only by reconciliation.', null=True)),
                ('ap_reference', models.CharField(blank=True, max_length=50)),
                ('match_method', models.CharField(blank=True, help_text='exact / reference / block / subset (+combined) / unmatched', max_length=30)),
                ('amount_formula', models.CharField(blank=True, help_text="Preserves amounts typed as formulas, e.g. '=672+125'", max_length=200)),
                ('conflict_fields', models.CharField(blank=True, help_text='Migration-era record of fields that disagreed across retyped rows', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('entry', 'Entry workbook'), ('migrated', 'Migrated'), ('platform', 'Platform')], default='platform', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickhaul_invoices', to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickhaul_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickhaul_invoices', to='api.legalentity')),
                ('packinghouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickhaul_invoices', to='api.packinghouse')),
            ],
            options={
                'ordering': ['-date_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PickHaulChargeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30)),
                ('matched_at', models.DateTimeField(auto_now=True)),
                ('charge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='api.pickhauldirectcharge')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_matches', to='api.pickhaulinvoice')),
            ],
            options={
                'verbose_name_plural': 'pick haul charge matches',
            },
        ),
        migrations.CreateModel(
            name='PickHaulManualPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField()),
                ('sheet', models.CharField(blank=True, help_text="Legacy source-sheet label, e.g. 'JPF Avo's' — provenance and grouping", max_length=50)),
                ('ranch', models.CharField(blank=True, max_length=100)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('varietal', models.CharField(blank=True, max_length=100)),
                ('pick_date', models.DateField(blank=True, null=True)),
                ('date_label', models.CharField(blank=True, help_text="Some sheets print a range like '4/13-4/15'", max_length=40)),
                ('bins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('harvester', models.CharField(blank=True, max_length=100)),
                ('hauler', models.CharField(blank=True, max_length=100)),
                ('invoice_no', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('haul_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('packing_house_text', models.CharField(blank=True, help_text="The sheet's own 'PH' column, distinct from the FK", max_length=50)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('po_received', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('row_no', models.PositiveIntegerField(blank=True, help_text='Preserves the order rows were entered in', null=True)),
                ('count_cost', models.BooleanField(default=True)),
                ('count_haul', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickhaul_manual_picks', to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickhaul_manual_picks_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickhaul_manual_picks', to='api.legalentity')),
                ('packinghouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickhaul_manual_picks', to='api.packinghouse')),
            ],
            options={
                'ordering': ['sheet', 'row_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PickHaulReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField()),
                ('receipt_no', models.CharField(max_length=50)),
                ('pool', models.CharField(blank=True, max_length=100)),
                ('block_raw', models.CharField(blank=True, help_text="As the house prints it, e.g. 'JP FINCH SESPE BLOCK'. Deliberately unmapped.", max_length=200)),
                ('pick_date', models.DateField(blank=True, null=True)),
                ('pick_date_raw', models.CharField(blank=True, help_text='Kept verbatim when the export printed text the local pipeline could not parse', max_length=40)),
                ('pick_time', models.CharField(blank=True, max_length=20)),
                ('variety_code', models.CharField(blank=True, max_length=20)),
                ('commodity_code', models.CharField(blank=True, max_length=20)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('uom2', models.CharField(blank=True, max_length=20)),
                ('qty2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extra_12', models.CharField(blank=True, max_length=100)),
                ('extra_13', models.CharField(blank=True, max_length=100)),
                ('bins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False = vanished from a later portal pull. Flagged, never deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickhaul_receipts', to='api.company')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickhaul_receipts', to='api.legalentity')),
                ('field', models.ForeignKey(blank=True, help_text='Future seam: block_raw resolved to a real Field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickhaul_receipts', to='api.field')),
                ('packinghouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickhaul_receipts', to='api.packinghouse')),
            ],
            options={
                'ordering': ['-pick_date', 'receipt_no'],
            },
        ),
        migrations.CreateModel(
            name='PickHaulInvoiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.CharField(choices=[('rule', 'Rule'), ('manual', 'Manual'), ('migrated', 'Migrated')], default='rule', max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_links', to='api.pickhaulinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_links', to='api.pickhaulreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='PickHaulSyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.PositiveSmallIntegerField()),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(choices=[('push', 'Push'), ('seed', 'Seed')], default='push', max_length=10)),
                ('generated_at', models.DateTimeField(blank=True, help_text='When the local pipeline built this bundle', null=True)),
                ('bundle_sha256', models.CharField(blank=True, max_length=64)),
                ('config_sha256', models.CharField(blank=True, max_length=64)),
                ('source_label', models.CharField(blank=True, help_text="e.g. 'pickhaul-local @ DESKTOP-XXXX'", max_length=100)),
                ('gate_errors', models.PositiveSmallIntegerField(default=0)),
                ('gate_warns', models.PositiveSmallIntegerField(default=0)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], max_length=12)),
                ('reject_reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickhaul_batches', to='api.company')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='api.machineapitoken')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='pickhaulreceipt',
            name='first_seen_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pickhaulsyncbatch'),
        ),
        migrations.AddField(
            model_name='pickhaulreceipt',
            name='last_seen_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pickhaulsyncbatch'),
        ),
        migrations.CreateModel(
            name='PickHaulPull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField()),
                ('pulled_at', models.DateTimeField()),
                ('file_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('header_text', models.CharField(blank=True, max_length=300)),
                ('header_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='ok', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickhaul_pulls', to='api.company')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickhaul_pulls', to='api.legalentity')),
                ('packinghouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickhaul_pulls', to='api.packinghouse')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulls', to='api.pickhaulsyncbatch')),
            ],
            options={
                'ordering': ['-pulled_at'],
            },
        ),
        migrations.AddField(
            model_name='pickhauldirectcharge',
            name='first_seen_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pickhaulsyncbatch'),
        ),
        migrations.CreateModel(
            name='PickHaulCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField()),
                ('origin', models.CharField(choices=[('local', 'Local'), ('platform', 'Platform')], max_length=10)),
                ('gate', models.PositiveSmallIntegerField()),
                ('gate_name', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warn', 'Warning'), ('info', 'Info')], max_length=8)),
                ('season', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('detail', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickhaul_checks', to='api.company')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.legalentity')),
                ('packinghouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.packinghouse')),
                ('invoice', models.ForeignKey(blank=True, help_text='Set when the finding is about one invoice, so the UI can link to it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_results', to='api.pickhaulinvoice')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='api.pickhaulsyncbatch')),
            ],
            options={
                'ordering': ['-run_at', 'gate'],
            },
        ),
        migrations.AddIndex(
            model_name='pickhaulinvoice',
            index=models.Index(fields=['company', 'season', 'kind'], name='api_pickhau_company_f50fab_idx'),
        ),
        migrations.AddIndex(
            model_name='pickhaulinvoice',
            index=models.Index(fields=['company', 'season', 'date_emailed'], name='api_pickhau_company_32ea65_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickhaulinvoice',
            constraint=models.UniqueConstraint(models.F('packinghouse'), models.F('entity'), models.F('season'), models.F('kind'), django.db.models.functions.comparison.Coalesce('contractor', models.Value('')), django.db.models.functions.comparison.Coalesce('invoice_no', models.Value('')), django.db.models.functions.comparison.Coalesce('amount', models.Value(Decimal('-1'))), name='uniq_pickhaul_invoice_identity'),
        ),
        migrations.AddIndex(
            model_name='pickhaulmanualpick',
            index=models.Index(fields=['company', 'season', 'packinghouse'], name='api_pickhau_company_9f2f7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickhaulinvoicereceipt',
            constraint=models.UniqueConstraint(fields=('invoice', 'receipt'), name='uniq_pickhaul_invoice_receipt'),
        ),
        migrations.AddIndex(
            model_name='pickhaulsyncbatch',
            index=models.Index(fields=['company', '-received_at'], name='api_pickhau_company_8e22e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickhaulsyncbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'applied')), fields=('company', 'bundle_sha256'), name='uniq_pickhaul_bundle_applied'),
        ),
        migrations.AddIndex(
            model_name='pickhaulreceipt',
            index=models.Index(fields=['company', 'season', 'block_raw', 'pick_date'], name='api_pickhau_company_a524a7_idx'),
        ),
        migrations.AddIndex(
            model_name='pickhaulreceipt',
            index=models.Index(fields=['company', 'season', 'is_active'], name='api_pickhau_company_c366a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickhaulreceipt',
            constraint=models.UniqueConstraint(fields=('packinghouse', 'entity', 'season', 'receipt_no'), name='uniq_pickhaul_receipt'),
        ),
        migrations.AddIndex(
            model_name='pickhaulpull',
            index=models.Index(fields=['company', 'season', 'packinghouse', 'entity'], name='api_pickhau_company_6a5012_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickhaulpull',
            constraint=models.UniqueConstraint(fields=('packinghouse', 'entity', 'season', 'pulled_at', 'sha256'), name='uniq_pickhaul_pull'),
        ),
        migrations.AddIndex(
            model_name='pickhauldirectcharge',
            index=models.Index(fields=['company', 'season', 'kind', 'block_raw'], name='api_pickhau_company_b43e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='pickhauldirectcharge',
            index=models.Index(fields=['company', 'ap_reference'], name='api_pickhau_company_323b3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickhauldirectcharge',
            constraint=models.UniqueConstraint(fields=('packinghouse', 'entity', 'season', 'row_hash'), name='uniq_pickhaul_charge_hash'),
        ),
        migrations.AddIndex(
            model_name='pickhaulcheckresult',
            index=models.Index(fields=['company', '-run_at', 'severity'], name='api_pickhau_company_324183_idx'),
        ),
        migrations.AddIndex(
            model_name='pickhaulcheckresult',
            index=models.Index(fields=['company', 'season', 'gate'], name='api_pickhau_company_21e39c_idx'),
        ),
        migrations.RunPython(add_rls_policies, drop_rls_policies),
    ]
