# Generated by Django 5.2.16 on 2026-07-30 21:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_pickhaul'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Utilities', 'Property Tax'", max_length=100)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('qb_account_name', models.CharField(blank=True, help_text='Source account label, so an unmapped line can still be traced', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_categories', to='api.company')),
            ],
            options={
                'verbose_name_plural': 'rental categories',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="As it appears in the books, e.g. '1553 Rio Vista House Rental'", max_length=200)),
                ('location_type', models.CharField(choices=[('on_ranch', 'On-ranch — stands on ground we farm'), ('off_ranch', 'Off-ranch — standalone investment property')], db_index=True, help_text='Location rule, not entity rule. Never derive this from whether farm is null.', max_length=20)),
                ('property_type', models.CharField(choices=[('dwelling', 'Dwelling'), ('commercial', 'Commercial'), ('yard', 'Yard / barn / storage'), ('land', 'Land lease'), ('other', 'Other')], default='dwelling', help_text="Not everything that earns rent is a house — Saticoy's Barn/Yard Rental is the largest single line in Finch Farms LLC at $12,480.", max_length=20)),
                ('pnl_treatment', models.CharField(choices=[('non_operating', 'Non-operating income — outside every farming margin'), ('ranch_other_income', 'Ranch other income — shown on the ranch, still outside the crop margin')], default='non_operating', help_text='Defaults to non_operating so the farming boundary holds by default', max_length=30)),
                ('qb_class_path', models.CharField(blank=True, help_text="Full QuickBooks class tree path, e.g. 'Income > Ranches > Rentals > Office > 956 Orange'. Nesting depth in the exports is encoded by column index, not by the label.", max_length=300)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, default='CA', max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False for sold or no-longer-rented property. Excluded from roll-ups.')),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('disposed_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Reconciliation notes, especially where a property is double-booked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_properties', to='api.company')),
                ('farm', models.ForeignKey(blank=True, help_text='The ranch this property stands on. Required when on-ranch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_properties', to='api.farm')),
                ('owning_entity', models.ForeignKey(blank=True, help_text='Entity holding title. Deliberately independent of location_type — Thacher Creek LLC owns both an on-ranch house and an off-ranch 13-unit building.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_properties', to='api.legalentity')),
                ('parcel', models.ForeignKey(blank=True, help_text='APN this property sits on, where known', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_properties', to='api.farmparcel')),
            ],
            options={
                'verbose_name_plural': 'rental properties',
                'ordering': ['farm__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_label', models.CharField(help_text="As the manager keys it, e.g. '359'. Use 'whole' for single-unit property.", max_length=50)),
                ('bedrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('is_rent_controlled', models.BooleanField(default=False, help_text='Ojai rent control applies to the Ventura St building. Drives turnover-decontrol sequencing, so it must be per-unit.')),
                ('is_available', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.rentalproperty')),
            ],
            options={
                'ordering': ['rental_property__name', 'unit_label'],
            },
        ),
        migrations.CreateModel(
            name='RentalLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(db_index=True)),
                ('period_month', models.PositiveSmallIntegerField(blank=True, help_text='Null means this row is the annual figure for period_year', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('amount_charged', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='What was billed. One row per period — never one row per split payment.', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='What was collected, summed across split payments', max_digits=12)),
                ('source', models.CharField(choices=[('manager_statement', 'Property manager statement'), ('qb_pnl', 'QuickBooks P&L export'), ('rent_roll', 'Rent roll workbook'), ('manual', 'Entered by hand')], default='manual', max_length=30)),
                ('is_flagged', models.BooleanField(db_index=True, default=False, help_text='Import could not fully trust this row. $3,916.90 appears as the annual figure for three different properties across two entities and two years — flagged, not silently cleaned.')),
                ('flag_reason', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='api.rentalcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_ledger_entries', to='api.company')),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.rentalproperty')),
                ('unit', models.ForeignKey(blank=True, help_text='Null when the figure is whole-property grain', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.rentalunit')),
            ],
            options={
                'verbose_name_plural': 'rental ledger entries',
                'ordering': ['-period_year', '-period_month', 'rental_property__name'],
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupant_label', models.CharField(blank=True, help_text="Free-text occupant reference as the manager keys it, e.g. 'Vasquez'. Deliberately not a Tenant record — see module docstring.", max_length=200)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Contract rent for this unit. The only place rent is stored.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Null means open-ended or simply unknown', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='api.rentalunit')),
            ],
            options={
                'ordering': ['unit__rental_property__name', 'unit__unit_label', '-start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='rentalcategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_rentalcategory_company_name'),
        ),
        migrations.AddIndex(
            model_name='rentalproperty',
            index=models.Index(fields=['company', 'location_type'], name='api_rentalp_company_720aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalproperty',
            index=models.Index(fields=['farm', 'is_active'], name='api_rentalp_farm_id_8c2c88_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentalproperty',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('farm__isnull', False), ('location_type', 'on_ranch')), ('location_type', 'off_ranch'), _connector='OR'), name='rentalproperty_on_ranch_requires_farm'),
        ),
        migrations.AddConstraint(
            model_name='rentalunit',
            constraint=models.UniqueConstraint(fields=('rental_property', 'unit_label'), name='uniq_rentalunit_property_label'),
        ),
        migrations.AddIndex(
            model_name='rentalledgerentry',
            index=models.Index(fields=['company', 'period_year'], name='api_rentall_company_b3bafe_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalledgerentry',
            index=models.Index(fields=['rental_property', 'period_year', 'period_month'], name='api_rentall_rental__053beb_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalledgerentry',
            index=models.Index(fields=['is_flagged'], name='api_rentall_is_flag_136af5_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['unit', 'is_active'], name='api_lease_unit_id_e5c9a5_idx'),
        ),
    ]
