# Generated by Django 5.2.16 on 2026-07-31 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_remove_fsma_primusgfs_traceability_facility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CIMISDataCache',
        ),
        migrations.RemoveField(
            model_name='cropcoefficientprofile',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='fertilizerproduct',
            name='company',
        ),
        migrations.RemoveField(
            model_name='nutrientapplication',
            name='product',
        ),
        migrations.RemoveField(
            model_name='irrigationrecommendation',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='irrigationevent',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='irrigationzone',
            name='field',
        ),
        migrations.RemoveField(
            model_name='irrigationzone',
            name='water_source',
        ),
        migrations.RemoveField(
            model_name='soilmoisturereading',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='irrigationevent',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='nutrientapplication',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='nutrientapplication',
            name='field',
        ),
        migrations.RemoveField(
            model_name='nutrientapplication',
            name='water_source',
        ),
        migrations.AlterUniqueTogether(
            name='nutrientplan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nutrientplan',
            name='field',
        ),
        migrations.RemoveIndex(
            model_name='irrigationevent',
            name='idx_irrig_zone_date',
        ),
        migrations.RemoveField(
            model_name='irrigationevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='irrigationevent',
            name='depth_inches',
        ),
        migrations.RemoveField(
            model_name='irrigationevent',
            name='method',
        ),
        migrations.RemoveField(
            model_name='irrigationevent',
            name='source',
        ),
        migrations.AlterField(
            model_name='irrigationevent',
            name='field',
            field=models.ForeignKey(blank=True, help_text='Field irrigated', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_events', to='api.field'),
        ),
        migrations.DeleteModel(
            name='CropCoefficientProfile',
        ),
        migrations.DeleteModel(
            name='FertilizerProduct',
        ),
        migrations.DeleteModel(
            name='IrrigationRecommendation',
        ),
        migrations.DeleteModel(
            name='SoilMoistureReading',
        ),
        migrations.DeleteModel(
            name='IrrigationZone',
        ),
        migrations.DeleteModel(
            name='NutrientApplication',
        ),
        migrations.DeleteModel(
            name='NutrientPlan',
        ),
    ]
