# Generated by Django 5.2.16 on 2026-07-31 17:37
#
# Per-invoice billing mode (grower-paid vs house-billed) and the charge
# acknowledgment satellite table. The ack is a separate table because
# PickHaulDirectCharge is sync-owned append-only — the web never writes a
# column on a sync-owned row. See api/models/pickhaul.py.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_rls_policy(apps, schema_editor):
    """Postgres-only defence in depth, matching 0087."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("""
        ALTER TABLE api_pickhaulchargeack ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS tenant_isolation ON api_pickhaulchargeack;
        CREATE POLICY tenant_isolation ON api_pickhaulchargeack
            FOR ALL
            USING (company_id::text = current_setting('app.current_company_id', true));
    """)


def drop_rls_policy(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        "DROP POLICY IF EXISTS tenant_isolation ON api_pickhaulchargeack;"
    )
    schema_editor.execute(
        "ALTER TABLE api_pickhaulchargeack DISABLE ROW LEVEL SECURITY;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_remove_irrigation_scheduling_and_nutrients'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickhaulinvoice',
            name='billing',
            field=models.CharField(choices=[('direct', 'Grower-paid'), ('house_billed', 'House-billed')], default='direct', help_text='direct = grower pays the contractor and chases reimbursement; house_billed = the contractor bills the packinghouse and it is charged against sales (nothing to chase).', max_length=12),
        ),
        migrations.CreateModel(
            name='PickHaulChargeAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('house_billed', 'Expected house-billed'), ('disputed', 'Disputed'), ('other', 'Other')], default='house_billed', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ack', to='api.pickhauldirectcharge')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickhaul_charge_acks', to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickhaul_charge_acks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'pick haul charge acks',
            },
        ),
        migrations.RunPython(add_rls_policy, drop_rls_policy),
    ]
