# Generated by Django 5.2.16 on 2026-07-31 17:48
#
# The season plan: commodity-level packer commitments with block overrides.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_rls_policy(apps, schema_editor):
    """Postgres-only defence in depth, matching 0087/0093."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("""
        ALTER TABLE api_packercommitment ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS tenant_isolation ON api_packercommitment;
        CREATE POLICY tenant_isolation ON api_packercommitment
            FOR ALL
            USING (company_id::text = current_setting('app.current_company_id', true));
    """)


def drop_rls_policy(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        "DROP POLICY IF EXISTS tenant_isolation ON api_packercommitment;"
    )
    schema_editor.execute(
        "ALTER TABLE api_packercommitment DISABLE ROW LEVEL SECURITY;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_pickhaul_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackerCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField(help_text='End year of the season (2026 = the 2025-2026 season)')),
                ('commodity', models.CharField(help_text='Canonical commodity (normalized, e.g. LEMONS, AVOCADOS)', max_length=50)),
                ('flex', models.BooleanField(default=False, help_text='Destination decided per pick — mismatches are expected')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packer_commitments', to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packer_commitments_created', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(blank=True, help_text='Block-level override; null = commodity default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packer_commitments', to='api.field')),
                ('packinghouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='api.packinghouse')),
            ],
            options={
                'ordering': ['-season', 'commodity', 'field_id'],
                'indexes': [models.Index(fields=['company', 'season'], name='api_packerc_company_c6b585_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('field__isnull', True)), fields=('company', 'season', 'commodity'), name='uniq_commitment_default'), models.UniqueConstraint(condition=models.Q(('field__isnull', False)), fields=('company', 'season', 'commodity', 'field'), name='uniq_commitment_block')],
            },
        ),
        migrations.RunPython(add_rls_policy, drop_rls_policy),
    ]
