/**
 * Centralized route configuration
 * Maps view IDs (used internally) to URL paths and metadata
 */

// View ID -> URL path mapping
export const VIEW_TO_PATH = {
  'dashboard': '/dashboard',
  'farms': '/dashboard/farms',
  'weather': '/dashboard/weather',
  'analytics': '/dashboard/analytics',
  'water': '/dashboard/water',
  'nutrients': '/dashboard/nutrients',
  'harvests': '/dashboard/harvests',
  'yield-forecast': '/dashboard/yield-forecast',
  'compliance': '/dashboard/compliance',
  'compliance-deadlines': '/dashboard/compliance/deadlines',
  'compliance-licenses': '/dashboard/compliance/licenses',
  'compliance-wps': '/dashboard/compliance/wps',
  'compliance-reports': '/dashboard/compliance/reports',
  'compliance-settings': '/dashboard/compliance/settings',
  'compliance-fsma': '/dashboard/compliance/fsma',
  'compliance-fsma-visitors': '/dashboard/compliance/fsma/visitors',
  'compliance-fsma-cleaning': '/dashboard/compliance/fsma/cleaning',
  'compliance-fsma-meetings': '/dashboard/compliance/fsma/meetings',
  'compliance-fsma-inventory': '/dashboard/compliance/fsma/inventory',
  'compliance-fsma-phi': '/dashboard/compliance/fsma/phi',
  'compliance-fsma-audit': '/dashboard/compliance/fsma/audit',
  'compliance-pesticide': '/dashboard/compliance/pesticide',
  'compliance-inspector-checklist': '/dashboard/compliance/inspector-checklist',
  'compliance-primusgfs': '/dashboard/compliance/primusgfs',
  'compliance-primusgfs-documents': '/dashboard/compliance/primusgfs/documents',
  'compliance-primusgfs-audits': '/dashboard/compliance/primusgfs/audits',
  'compliance-primusgfs-corrective-actions': '/dashboard/compliance/primusgfs/corrective-actions',
  'compliance-primusgfs-land': '/dashboard/compliance/primusgfs/land',
  'compliance-primusgfs-suppliers': '/dashboard/compliance/primusgfs/suppliers',
  'compliance-primusgfs-recalls': '/dashboard/compliance/primusgfs/recalls',
  'compliance-primusgfs-food-defense': '/dashboard/compliance/primusgfs/food-defense',
  'compliance-primusgfs-sanitation': '/dashboard/compliance/primusgfs/sanitation',
  'compliance-primusgfs-calibration': '/dashboard/compliance/primusgfs/calibration',
  'compliance-primusgfs-pest-control': '/dashboard/compliance/primusgfs/pest-control',
  'compliance-primusgfs-pre-harvest': '/dashboard/compliance/primusgfs/pre-harvest',
  // CAC Food Safety Manual V5.0 tab routes
  'compliance-primusgfs-profile': '/dashboard/compliance/primusgfs/profile',
  'compliance-primusgfs-org-roles': '/dashboard/compliance/primusgfs/org-roles',
  'compliance-primusgfs-committee': '/dashboard/compliance/primusgfs/committee',
  'compliance-primusgfs-mgmt-review': '/dashboard/compliance/primusgfs/mgmt-review',
  'compliance-primusgfs-training-matrix': '/dashboard/compliance/primusgfs/training-matrix',
  'compliance-primusgfs-training-sessions': '/dashboard/compliance/primusgfs/training-sessions',
  'compliance-primusgfs-perimeter': '/dashboard/compliance/primusgfs/perimeter',
  'compliance-primusgfs-pre-season': '/dashboard/compliance/primusgfs/pre-season',
  'compliance-primusgfs-field-risk': '/dashboard/compliance/primusgfs/field-risk',
  'compliance-primusgfs-non-conformance': '/dashboard/compliance/primusgfs/non-conformance',
  'compliance-primusgfs-product-holds': '/dashboard/compliance/primusgfs/product-holds',
  'compliance-primusgfs-supplier-verify': '/dashboard/compliance/primusgfs/supplier-verify',
  'compliance-primusgfs-food-fraud': '/dashboard/compliance/primusgfs/food-fraud',
  'compliance-primusgfs-emergency': '/dashboard/compliance/primusgfs/emergency',
  'compliance-primusgfs-chemical-inv': '/dashboard/compliance/primusgfs/chemical-inv',
  'compliance-primusgfs-sanitation-maint': '/dashboard/compliance/primusgfs/sanitation-maint',
  'compliance-primusgfs-cac-manual': '/dashboard/compliance/primusgfs/cac-manual',
  'compliance-primusgfs-audit-binder': '/dashboard/compliance/primusgfs/audit-binder',
  'applications': '/dashboard/applications',
  'pur-import': '/dashboard/pur-import',
  'tree-detection': '/dashboard/tree-detection',
  'disease': '/dashboard/disease',
  'reports': '/dashboard/reports',
  'activity': '/dashboard/activity',
  'team': '/dashboard/team',
  'company': '/dashboard/company',
  'profile': '/dashboard/profile',
};

// Reverse mapping: URL path -> view ID
export const PATH_TO_VIEW = Object.fromEntries(
  Object.entries(VIEW_TO_PATH).map(([viewId, path]) => [path, viewId])
);

// Display names for breadcrumbs and page titles
export const VIEW_NAMES = {
  dashboard: 'Dashboard',
  farms: 'Farms & Fields',
  weather: 'Weather',
  analytics: 'Analytics',
  water: 'Water Management',
  nutrients: 'Nutrients',
  harvests: 'Harvest & Packing',
  'yield-forecast': 'Yield Forecast',
  compliance: 'Compliance',
  'compliance-deadlines': 'Deadlines',
  'compliance-licenses': 'Licenses',
  'compliance-wps': 'WPS Compliance',
  'compliance-reports': 'Reports',
  'compliance-settings': 'Settings',
  'compliance-fsma': 'FSMA',
  'compliance-fsma-visitors': 'Visitors',
  'compliance-fsma-cleaning': 'Cleaning',
  'compliance-fsma-meetings': 'Meetings',
  'compliance-fsma-inventory': 'Inventory',
  'compliance-fsma-phi': 'PHI',
  'compliance-fsma-audit': 'Audit',
  'compliance-pesticide': 'Pesticide',
  'compliance-inspector-checklist': 'Inspector Checklist',
  'compliance-primusgfs': 'Primus GFS',
  'compliance-primusgfs-documents': 'Documents',
  'compliance-primusgfs-audits': 'Audits',
  'compliance-primusgfs-corrective-actions': 'Corrective Actions',
  'compliance-primusgfs-land': 'Land History',
  'compliance-primusgfs-suppliers': 'Suppliers',
  'compliance-primusgfs-recalls': 'Mock Recalls',
  'compliance-primusgfs-food-defense': 'Food Defense',
  'compliance-primusgfs-sanitation': 'Field Sanitation',
  'compliance-primusgfs-calibration': 'Equipment Calibration',
  'compliance-primusgfs-pest-control': 'Pest Control',
  'compliance-primusgfs-pre-harvest': 'Pre-Harvest Inspections',
  'compliance-primusgfs-profile': 'Food Safety Profile',
  'compliance-primusgfs-org-roles': 'Org Roles',
  'compliance-primusgfs-committee': 'Committee Meetings',
  'compliance-primusgfs-mgmt-review': 'Management Review',
  'compliance-primusgfs-training-matrix': 'Training Matrix',
  'compliance-primusgfs-training-sessions': 'Training Sessions',
  'compliance-primusgfs-perimeter': 'Perimeter Monitoring',
  'compliance-primusgfs-pre-season': 'Pre-Season Checklist',
  'compliance-primusgfs-field-risk': 'Field Risk Assessment',
  'compliance-primusgfs-non-conformance': 'Non-Conformance',
  'compliance-primusgfs-product-holds': 'Product Holds',
  'compliance-primusgfs-supplier-verify': 'Supplier Verification',
  'compliance-primusgfs-food-fraud': 'Food Fraud Assessment',
  'compliance-primusgfs-emergency': 'Emergency Contacts',
  'compliance-primusgfs-chemical-inv': 'Chemical Inventory',
  'compliance-primusgfs-sanitation-maint': 'Sanitation Maintenance',
  'compliance-primusgfs-cac-manual': 'CAC Manual',
  'compliance-primusgfs-audit-binder': 'Audit Binder',
  applications: 'Applications',
  'pur-import': 'PUR Import',
  'tree-detection': 'Tree Detection',
  disease: 'Disease Prevention',
  reports: 'Reports',
  activity: 'Activity Log',
  team: 'Team',
  company: 'Company Settings',
  profile: 'Profile',
};

// Parent view mappings for breadcrumbs
export const PARENT_VIEWS = {
  'pur-import': 'applications',
  'compliance-deadlines': 'compliance',
  'compliance-licenses': 'compliance',
  'compliance-wps': 'compliance',
  'compliance-reports': 'compliance',
  'compliance-settings': 'compliance',
  'compliance-fsma': 'compliance',
  'compliance-fsma-visitors': 'compliance-fsma',
  'compliance-fsma-cleaning': 'compliance-fsma',
  'compliance-fsma-meetings': 'compliance-fsma',
  'compliance-fsma-inventory': 'compliance-fsma',
  'compliance-fsma-phi': 'compliance-fsma',
  'compliance-fsma-audit': 'compliance-fsma',
  'compliance-pesticide': 'compliance',
  'compliance-inspector-checklist': 'compliance',
  'compliance-primusgfs': 'compliance',
  'compliance-primusgfs-documents': 'compliance-primusgfs',
  'compliance-primusgfs-audits': 'compliance-primusgfs',
  'compliance-primusgfs-corrective-actions': 'compliance-primusgfs',
  'compliance-primusgfs-land': 'compliance-primusgfs',
  'compliance-primusgfs-suppliers': 'compliance-primusgfs',
  'compliance-primusgfs-recalls': 'compliance-primusgfs',
  'compliance-primusgfs-food-defense': 'compliance-primusgfs',
  'compliance-primusgfs-sanitation': 'compliance-primusgfs',
  'compliance-primusgfs-calibration': 'compliance-primusgfs',
  'compliance-primusgfs-pest-control': 'compliance-primusgfs',
  'compliance-primusgfs-pre-harvest': 'compliance-primusgfs',
  'compliance-primusgfs-profile': 'compliance-primusgfs',
  'compliance-primusgfs-org-roles': 'compliance-primusgfs',
  'compliance-primusgfs-committee': 'compliance-primusgfs',
  'compliance-primusgfs-mgmt-review': 'compliance-primusgfs',
  'compliance-primusgfs-training-matrix': 'compliance-primusgfs',
  'compliance-primusgfs-training-sessions': 'compliance-primusgfs',
  'compliance-primusgfs-perimeter': 'compliance-primusgfs',
  'compliance-primusgfs-pre-season': 'compliance-primusgfs',
  'compliance-primusgfs-field-risk': 'compliance-primusgfs',
  'compliance-primusgfs-non-conformance': 'compliance-primusgfs',
  'compliance-primusgfs-product-holds': 'compliance-primusgfs',
  'compliance-primusgfs-supplier-verify': 'compliance-primusgfs',
  'compliance-primusgfs-food-fraud': 'compliance-primusgfs',
  'compliance-primusgfs-emergency': 'compliance-primusgfs',
  'compliance-primusgfs-chemical-inv': 'compliance-primusgfs',
  'compliance-primusgfs-sanitation-maint': 'compliance-primusgfs',
  'compliance-primusgfs-audit-binder': 'compliance-primusgfs',
};
